### ISSUE TITLE
Using maps with blazor preview4 error

### ISSUE THREAD

**Issue by valentasm1** [rungwiroon/BlazorGoogleMaps#1]
Is it possible to update google maps to work with 3.0.0-preview4 version?
I got errors like this and it looks just as beginning. 
The type 'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by rungwiroon** [comment]
I will try to upgrade it, if it not works. I will create new project and migrate old code.

**Comment by valentasm1** [comment]
If you need any help let me know. I am new to Blazor, but have some exp in .net, so  for repetitive boring tasks i could help.

**Comment by rungwiroon** [comment]
@valentasm1 Thanks for your help, this project still have a lot of API waiting for implement and test.
We should create list of tasks, so we can keep track things going here.

**Comment by valentasm1** [comment]
I see that you updated library. Thank you.

**Comment by valentasm1** [comment]
Sorry to write in closed, but could you update Nuget?
Also you could include it in https://github.com/AdrienTorris/awesome-blazor/ and maybe would find more support

**Comment by rungwiroon** [comment]
Sure, I will update it.
