### ISSUE TITLE
Serverside project : add/remove elements, based on zoom level

### ISSUE THREAD

**Issue by SamVanhoutte** [rungwiroon/BlazorGoogleMaps#100]
Hello, 

I have a situation, where I need to plot around 1000 `Polyline`s on a map, with a `Marker` at the start of the Polyline.  

I use the clustering feature, which helps to remove some clutter, which I like.
But now, I would love to be able to only show the polylines, when the user has zoomed in deep enough (a certain level-threshold I set).

I am wondering how to handle and implement that, as it's not very clear to me.  I assumed to catch the zoom event handler and add the polylines, when zoom level is small enough.

I don't know why, but it seems that listener is not being called.  It looks like the event handler delegate is a sync method and when I call the `_currentzoom = map1.GetZoom().Result;` line, it looks like it hangs (as the last log information does not get written)

```csharp
private async Task OnAfterInitAsync()
{
    var zoom = await map1.GetZoom();
    await map1.AddListener("zoom_changed", OnZoomChanged);
    Logger.LogInformation("Enabled zoom change listener, current zoom {zoom}");
}

private void OnZoomChanged()
{
    Logger.LogInformation("Zoom");
    _currentzoom = map1.GetZoom().Result;
    Logger.LogInformation("Zoom result: {_currentzoom}");
}

```

**Comment by valentasm1** [comment]
It has nothing to do with map. MS tells that all calls to js MUST be async. I wont search for source, but it is mentioned couple times.
What you do is (trying) making js call synchronous. 

Havent tested but it should work or be very similar

```
private async Task OnAfterInitAsync()
{
    var zoom = await map1.GetZoom();
    await map1.AddListener("zoom_changed", OnZoomChanged);
    Logger.LogInformation("Enabled zoom change listener, current zoom {zoom}");
}

private async void OnZoomChanged()
{
    Logger.LogInformation("Zoom");
    _currentzoom = await map1.GetZoom();
    Logger.LogInformation("Zoom result: {_currentzoom}");
}
```

**Comment by valentasm1** [comment]
Even more you could just debug and see that debug stops at line _currentzoom = map1.GetZoom().Result; and never reach last line

**Comment by SamVanhoutte** [comment]
Thanks for the pointer.  I always understood it's better/recommended to avoid having an `async void` , and rather use an `async Task` signature.  Regarding the Blazor async stuff : thanks for pointing that out (as you can guess, I'm new to Blazor/frontend and am more of a backend guy).

Cheers
