### ISSUE TITLE
Render a list of points

### ISSUE THREAD

**Issue by yiyoMX** [rungwiroon/BlazorGoogleMaps#101]
Is there a way to render a list of points all at once?, I have a method to render several points but it does it one by one, which visually looks odd.

**Comment by valentasm1** [comment]
Probably no.
Do you have some example of how you are doing now?

**Comment by SamVanhoutte** [comment]
I think this is also something I am looking for. 
Imagine you have 1000 `LatLngLiteral`s and you want to add a `Marker` for each point.
What I do is something like : 

```csharp
List<LatLngLiteral> pointList = await GetPoints();
var tasks = new List<Task>{};
tasks.AddRange(pointList.Select(
foreach(var latLng in pointList)
{
  tasks.Add(pt => Marker.CreateAsync(jsRuntime, new MarkerOptions{ Position = pt, Map = map1}));
}
await Task.WhenAll(tasks);
```

When doing that (I am using ServerSide Blazor) you indeed see all the marker appear in parallel and not at once.  And that is what @yiyoMX probably means with "visually looks odd"

**Comment by valentasm1** [comment]
@SamVanhoutte  You should use marker list functionality.
Example
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarkerListPage.razor.cs

**Comment by SamVanhoutte** [comment]
Wow, I should not have missed that.  Thanks for pointing it out!  Totally what I need
