### ISSUE TITLE
How to execute create and remove Circle in sequence

### ISSUE THREAD

**Issue by djkikimarseille** [rungwiroon/BlazorGoogleMaps#102]
Hello

I would like to on my map : 
- Add circle1
- wait 1 second
- Remove circle1
- Add circle2
- wait 1 second
- Remove circle2

But result is : 
- Add circle1
- wait 1 second
- Add circle2
- wait 1 second
- Remove circle1
- Remove circle2

Because "Circle.CreateAsync" is async method, it's normal ... But I don't know how I could reach my goal.

Thanks in advance

My code : 
```
private GoogleMap map1 = default!;

private List<Circle> circleslist = new List<Circle>();

LatLngLiteral position_scan1 = new LatLngLiteral { Lat = 42.16678995808851, Lng = 9.164563395062487};

void DoStuff(ChangeEventArgs e)
{
    for (int i = 1; i < 4; i++)
    {
        Task.Run(async () => await AddBeaconCircle(position_scan1, i * 5));

        var t = Task.Run(async delegate
        {
            await Task.Delay(1000);
            return 42;
        });
        t.Wait();

        Task.Run(async () => await RemoveCirclesList());
    }
}

private async Task AddBeaconCircle(LatLngLiteral calculatedposition, int radius)
{
    var position = new LatLngLiteral()
    {
        Lat = calculatedposition.Lat,
        Lng = calculatedposition.Lng
    };

    var circle = await Circle.CreateAsync(map1.JsRuntime, new CircleOptions()
    {
        Center = position,
        Map = map1.InteropObject,
        Radius = radius,
        FillColor = "purple",
        FillOpacity = (float)0.5,
        StrokePosition = StrokePosition.Outside,
        StrokeColor = "white",
        StrokeOpacity = (float)0.5,
        StrokeWeight = 2
    });

    lock(circleslist)
    {
        circleslist.Add(circle);
    }
}

private async Task RemoveCirclesList()
{
    foreach (var circle in circleslist)
    {
        await circle.SetMap(null);
    }

    circleslist.Clear();
}
```

[New Text Document.txt](https://github.com/rungwiroon/BlazorGoogleMaps/files/5931768/New.Text.Document.txt)

**Comment by valentasm1** [comment]
Sorry but it has nothing to do with map component. Maybe one day when i will be not so lazy and i will try to find solution for you, but i think you should understand better of way Task works.

**Comment by valentasm1** [comment]
Why you want add and remove cirlce so fast? What is business case?

**Comment by djkikimarseille** [comment]
> 
> 
> Why you want add and remove cirlce so fast? What is business case?

Because I would like to show on map, evolution of variable with circle bigger and bigger ...

**Comment by valentasm1** [comment]
Map animations is very complicated thing even it sounds obvious. IMO even you archive hide/show logic it will look just strange.
You could create overlay over area or show some gif if possible.

**Comment by turner11** [comment]
Disclaimers:
1. @valentasm1 is right, this has nothing to do with map components.
2. I do not have any opinion if this is what you should or should not do.
3. This code was not tested.

Just for the fun of it, you can use this sketch for building a solution.
```C#
           //Create small cicrcle
            await Circle.CreateAsync(JsRuntime, smallCircleoptions)
            // Wait 1 second (make sure to pass on the circle)
            .ContinueWith(async createTask => 
            {
                await Task.Delay(1000);
                return createTask.Result;
            }).Unwrap()            
            // Remove small circle
            .ContinueWith(async circleTask => //remove small cicrcle
            {
                var circle = circleTask.Result;
                await circle.SetMap(null);
            })
            // Draw large circle
            .ContinueWith(async _ => await Circle.CreateAsync(JsRuntime, largeCircleoptions));
```
