### ISSUE TITLE
Best and most performant way to remove all items from a map 

### ISSUE THREAD

**Issue by SamVanhoutte** [rungwiroon/BlazorGoogleMaps#103]
Hello, 

I want to have my map behave differently, based on the zoom level.  
- On a high level, I just want to show different markers and enable clustering
- When zooming deeper than a certain level, I want to remove those markers and show the polylines with some icons
- And when I zoom out again (again passing that threshold), I want to remove the polylines and show the markers again.

Is there a good way to clean the map from all the additional items I have created on it, but still keep the map at the right zoom level and center as the user left it.

Now, I keep track of all the markers & polylines in a list, but I would assume there is something like : `Map.Clear()` 

Any idea? 

Thanks

**Comment by valentasm1** [comment]
If you find good solution on google maps JavaScript we could bring it here. 
I agree this one could be usefull.

**Comment by valentasm1** [comment]
Keeping some reference with google map prototype functions doesnt sound right solution. 
With MarkerList i think there is function remove all, but still you need keep references.
Right now i dont have solution

**Comment by SamVanhoutte** [comment]
I'm not a javascript person at all (that's why I use Blazor and I'm happy with your component), so I'm afraid I won't be able to come up with a JS-proposal.  
Thanks for the info, will close the issue

**Comment by valentasm1** [comment]
You dont need to get exact solution. Just go through internet and maybe someone will come with exact issue on stackoverflow.

**Comment by SamVanhoutte** [comment]
What would be your approach with the current code base? When I perform the following code now (using a `MarkerList`), it does not seem to work to remove the Markers (same behavior with the `PolylineList`).  

```csharp
if (_markerList != null)
{
    foreach (var markerListMarker in _markerList.Markers)
    {
        await markerListMarker.Value.SetMap(null);
    }
    await _markerList.RemoveMultipleAsync();
}
```

**Comment by valentasm1** [comment]
As you see method, that you need to pass ids which you need to remove.
I consider it as a bug. If no or null is passed everything should be removed.
Will realease fix nuget

```
public virtual async Task RemoveMultipleAsync(List<string> filterKeys = null)
        {
            if ((filterKeys != null) && (filterKeys.Count > 0))
            {
                List<string> foundKeys = BaseListableEntities.Keys.Intersect(filterKeys).ToList();
                if (foundKeys.Count > 0)
                {
                    List<Guid> foundGuids = BaseListableEntities.Where(e => foundKeys.Contains(e.Key)).Select(e => e.Value.Guid).ToList();
                    await _jsObjectRef.DisposeMultipleAsync(foundGuids);

                    foreach (string key in foundKeys)
                    {
                        //Marker object needs to dispose call due to previous DisposeMultipleAsync call
                        //Probably superfluous, but Garbage Collector may appreciate it... 
                        BaseListableEntities[key] = null;
                        BaseListableEntities.Remove(key);
                    }
                }
            }
        }
```

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.0.9

**Comment by SamVanhoutte** [comment]
That was fast :)  Much appreciated
But, I still have the same behavior.  (also with the 1.0.9)
And I even have it when I pass the id's of the markers in the Delete method, like the following statement:

```csharp
foreach (var markerListMarker in _markerList.Markers)
{
    await markerListMarker.Value.SetMap(null);
}
await _markerList.RemoveMultipleAsync(sections.Select(c=>c.Id).ToList());
```

**Comment by valentasm1** [comment]
Try ti 1.0.10 version and without passing anything. Or passing null.

**Comment by SamVanhoutte** [comment]
I'm sorry, but this still does not seem to work.  I really don't have an idea on what could be wrong here.
If I find time, I'll try to fork and stepthrough-debug your repo and see if can can get an idea

**Comment by valentasm1** [comment]
Yea. It works on demo.
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarkerListPage.razor.cs

**Comment by SamVanhoutte** [comment]
confirmed
