### ISSUE TITLE
InfoWindow Open doesn't pass on the optional anchor object

### ISSUE THREAD

**Issue by markschroeder77** [rungwiroon/BlazorGoogleMaps#104]
The open method doesn't pass on the optional anchor parameter.

This change to InfoWindow.cs fixes it:

`public Task Open(Map map, object anchor = null)`
`{`        
 `return _jsObjectRef.InvokeAsync("open", map, anchor);`
`}`

**Comment by valentasm1** [comment]
Havent tested.
https://github.com/rungwiroon/BlazorGoogleMaps/releases/tag/1.0.10

**Comment by markschroeder77** [comment]
Thanks, tested, working.

**Comment by valentasm1** [comment]
Could you give example of what object do you pass?
I would include it into exampels
