### ISSUE TITLE
PolylineList.SetMultipleAsync error : The given key was not present in the dictionary

### ISSUE THREAD

**Issue by SamVanhoutte** [rungwiroon/BlazorGoogleMaps#105]
Hello, 

I am calling the `SetMultipleAsync` method to create a `PolylineList` with multiple lines, that each have LineOptions.  Code is below.  But, when I call the function again with the same climbs, but with additional options, I get the error:

```csharp
await _lineList.SetMultipleAsync(sections.ToDictionary(s => s.Id, c => GetLine(c, showArrow, map1)));

private PolylineOptions GetLine(Section section, bool showArrow, Map map1)
{
    var path = section.GetPath();
    var options = new PolylineOptions()
    {
        StrokeColor = "#FD7D7A",
        Clickable = true,
        Draggable = false,
        Editable = false,
        Map = map1, Path = path
    };
    if (showArrow)
    {
        options.Icons = new[]
        {
            new IconSequence
            { // Start
                Icon = new Symbol {Path = SymbolPath.CIRCLE, Scale = 3f, StrokeColor = "green"},
                Offset = "0%"
            },
            new IconSequence
            { // End
                Icon = new Symbol {Path = SymbolPath.CIRCLE, Scale = 3f, StrokeColor = "red"},
                Offset = "100%"
            }
        };
    }

    return options;
}
```

So, if I call the above line with 1000 sections, it works.  But if I call the same function with the same 1000 sections (but with the bool `showArrow` set to `true` instead, I get the following error:

```
Unhandled exception rendering component: The given key '1' was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GoogleMapsComponents.Maps.Extension.ListableEntityListBase`2.<SetOptions>b__22_0(KeyValuePair`2 e)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at GoogleMapsComponents.Maps.Extension.ListableEntityListBase`2.SetOptions(Dictionary`2 options)
   at GoogleMapsComponents.Maps.Extension.ListableEntityListBase`2.SetMultipleAsync(Dictionary`2 opts, String googleMapListableEntityTypeName)
   at GoogleMapsComponents.Maps.Extension.PolylineList.SetMultipleAsync(Dictionary`2 opts)
....
```

**Comment by SamVanhoutte** [comment]
It is linked and related to a fix you did for the 0.10 version.
This line will remove all entities, because of the `if (filterKeys == null || !filterKeys.Any())`

https://github.com/rungwiroon/BlazorGoogleMaps/blob/c2fa551f3c5897bdb3b592da4a7ec0f2f3a23fff/GoogleMapsComponents/Maps/Extension/ListableEntityListBase.cs#L148

And that method is being called from the `SetMultipleAsync` method here `await this.RemoveMultipleAsync(lToRemove);`  But since I only want to "update" the items , the lToRemove is an empty List, and all base items get removed because of the previous line.

**Comment by SamVanhoutte** [comment]
So, I would expect that if I call `await RemoveMultipleAsync(new List<Marker>{});`, that actually nothing is removed, as I literally say : remove all marker in the list I pass (which is none). 

When the list is null, it's clear to the user that you're using the default parameter and that all items will be removed.

**Comment by valentasm1** [comment]
You damn right. I reverted that part changes. Added method RemoveAllAsync which removes all

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.0.11

**Comment by SamVanhoutte** [comment]
Hello @valentasm1 
I'm afraid the 1.0.11 of your package does not include the changes to your code (the changes in the method)
This is the code that I see when I use dotPeek to check your package:

```csharp
public virtual async Task RemoveMultipleAsync(List<string> filterKeys = null)
    {
      if (filterKeys == null || filterKeys.Count <= 0)
        return;
      List<string> foundKeys = this.BaseListableEntities.Keys.Intersect<string>((IEnumerable<string>) filterKeys).ToList<string>();
      if (foundKeys.Count > 0)
      {
        object obj = await this._jsObjectRef.DisposeMultipleAsync(this.BaseListableEntities.Where<KeyValuePair<string, TEntityBase>>((Func<KeyValuePair<string, TEntityBase>, bool>) (e => foundKeys.Contains(e.Key))).Select<KeyValuePair<string, TEntityBase>, Guid>((Func<KeyValuePair<string, TEntityBase>, Guid>) (e => e.Value.Guid)).ToList<Guid>());
        foreach (string key in foundKeys)
        {
          this.BaseListableEntities[key] = default (TEntityBase);
          this.BaseListableEntities.Remove(key);
        }
      }
    }
```

And that is different from here:
https://github.com/rungwiroon/BlazorGoogleMaps/blob/0a3f14e62d92f0c683fd8bc6facc872b7a32d53f/GoogleMapsComponents/Maps/Extension/ListableEntityListBase.cs#L154

**Comment by valentasm1** [comment]
Logically their are same
```
if (filterKeys == null || filterKeys.Count <= 0)
        return;
```

and 
```
if ((filterKeys != null) && (filterKeys.Count > 0))
            {

                List<string> foundKeys = BaseListableEntities.Keys.Intersect(filterKeys).ToList();
                if (foundKeys.Count > 0)
                {
                    List<Guid> foundGuids = BaseListableEntities.Where(e => foundKeys.Contains(e.Key)).Select(e => e.Value.Guid).ToList();
                    await _jsObjectRef.DisposeMultipleAsync(foundGuids);

                    foreach (string key in foundKeys)
                    {
                        //Marker object needs to dispose call due to previous DisposeMultipleAsync call
                        //Probably superfluous, but Garbage Collector may appreciate it... 
                        BaseListableEntities[key] = null;
                        BaseListableEntities.Remove(key);
                    }
                }
            }
```

**Comment by valentasm1** [comment]
Whats the problem?

**Comment by SamVanhoutte** [comment]
agreed, but I still have the above issue (missing key in dictionary) and therefore I was comparing the code and found out they were different.

to repro the issue, i think you can just apply the following logic:

- Create dictionary with 10 polylines (id's from 1 to 10)
- Create PolylineList with these 10 polylines and a set some options
- If you call `SetMultipleAsync` a second time on the same PolylineList with the same polylines/dictionary, then you get the exception as mentioned in the beginning of the issue.

**Comment by SamVanhoutte** [comment]
hold on for now : i might have a local nuget package issue and not use the latest one.  will update

**Comment by SamVanhoutte** [comment]
@valentasm1 : thanks for the fix.  I can confirm it works now (last part of the discussion was related to the fact that I had created a project reference to a local fork of your repo)
