### ISSUE TITLE
How to add onclick event handler in MarkerList or PolylineList

### ISSUE THREAD

**Issue by SamVanhoutte** [rungwiroon/BlazorGoogleMaps#106]
Hello, 

I am using `MarkerList` and `PolylineList` as they are much faster than adding markers myself.  So: good job !

Question I have though, is what the fastest possible way is to add an event handler in that method (an event handler that opens an infowindow).  I obviously can iterate through all items, but that will decrease performance, I guess.

Can be related to #76 ?  But I don't see the actual solution :)

Code when just using plain Markers: 

```csharp
InfoWindow infoWindow = await GetInfoWindowAsync(section, jsRuntime, section.Start);
await marker.AddListener("click", async () => { await infoWindow.Open(map1); });
```

What would be the code to achieve this for every marker I add in the MarkerList ?  Is there a better options than to iterate through the markers of my `MarkerList` ?? 

Thank you

**Comment by SamVanhoutte** [comment]
Answering myself: there is an AddListeners method on the MarkerList & PolylineList

**Comment by valentasm1** [comment]
It is called rubber duck debugging 
https://en.wikipedia.org/wiki/Rubber_duck_debugging#:~:text=In%20software%20engineering%2C%20rubber%20duck,-line%2C%20to%20the%20duck.

**Comment by valentasm1** [comment]
@SamVanhoutte could you give example of AddListeners ?
@yiyoMX  is keen to know how to use it.from #107

**Comment by SamVanhoutte** [comment]
here you go: 

```csharp
await _markerList.AddListeners(_markerList.Markers.Keys, "click", HandleMarkerClick);

private async void HandleMarkerClick<MouseEvent>(MouseEvent e, string sectionId)
{
    if (_existingWindow != null)
    {
        await _existingWindow.Close();
    }
    _existingWindow = await CreateInfoWindowAsync(MySections.First(c => c.Id.Equals(sectionId)), JsRuntime);
    await _existingWindow.Open(_map1);
}    
```
