### ISSUE TITLE
Breaking change : Code does not compile - dotnet.myget.org does not exists anymore

### ISSUE THREAD

**Issue by vd3d** [rungwiroon/BlazorGoogleMaps#109]
Hi,

The project does not compile anymore, the following NuGet feeds have been removed:

https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json;
https://dotnet.myget.org/F/blazor-dev/api/v3/index.json;

**Comment by valentasm1** [comment]
There are 4 projects in solution. Which one doesnt compile?
Could you give full error message?

**Comment by valentasm1** [comment]
I will closethis issue in week if i wont get answer.

**Comment by valentasm1** [comment]
Closed due innactivity.
