### ISSUE TITLE
google map marker  icon click Ievent

### ISSUE THREAD

**Issue by komirineni** [rungwiroon/BlazorGoogleMaps#11]

**Comment by komirineni** [comment]
I have attached a click event for the marker on the map. and click event also working fine but am not able to get the marker title info in the click event. could you please let me know how to get that?
below is the my code wrote:

 var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
            {
                Position = latlng,
                Clickable = true,
                Map = map1.InteropObject,
                //Label = ed.DeviceID.ToString(),
                Icon = new Icon()
                {
                    Url = ed.DeviceStatus == "Active" ? "images/Active.png" : "images/Void.png"
                },
                Title = "Device Id :" + ed.DeviceID.ToString()

            }); ;
            await marker.AddListener<MouseEvent>("click", async (e) => await DeviceClick(e));

   private async Task DeviceClick(MouseEvent e)
    {
        Console.WriteLine("device click.");
     
    }

**Comment by valentasm1** [comment]
I am not sure what do you mean. Maybe this example will help. This is from ClientSideDemo MapInfoWindowp page
```
private async Task AddMarker()
    {
        var position = await map1.InteropObject.GetCenter();

        var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
        {
            Position = position,
            Map = map1.InteropObject,
            Label = $"Test {markerCount}"
        });

        var infoWindow = await InfoWindow.CreateAsync(map1.JsRuntime, new InfoWindowOptions()
        {
            Position = new LatLngLiteral()
            {
                Lat = 13.505892,
                Lng = 100.8162
            },
            //Content = "Test"
        });

        var infoWindowContent = $"Test {markerCount}";

        await marker.AddListener("click", async () =>
        {
            await infoWindow.SetContent(infoWindowContent);
            await infoWindow.SetPosition(position);
            await infoWindow.Open(map1.InteropObject);
        });

        markerCount++;
    }
```

**Comment by komirineni** [comment]
the above code is to add an event to marker. that i have already done in my code by adding a mouse click event...  
on mouse click event, I have to get the marker info. currently, am getting only latlang info only, but not getting any other marker info i.e. like marker title, marker label info. I need an event/code to get marker data where the user clicks on marker position.

**Comment by valentasm1** [comment]
Found bug. Fixed. @rungwiroon  please update nuget. 
Then you could use like this.

```
await marker.AddListener<MouseEvent>("click", async e =>
        {
            var markerLabel = await marker.GetLabel();
            _events.Add("click on " + markerLabel);
            StateHasChanged();

            e.Stop();
        });
```

**Comment by komirineni** [comment]
Hi Thank for the fix and i will try. there was one more issue like the dispose of in mapcomponent .

I had fixed the code by adding below MapComponent class

  if(InteropObject!=null)
            InteropObject.Dispose();

please add this change also and release NuGet thank you!

**Comment by valentasm1** [comment]
@komirineni  you are right for bug. It was fixed but was lost somewhere in merges. Thank you.
You could rewrite like this
```
public void Dispose()
{
    InteropObject?.Dispose();
}
```

I couldnt release nuget so we need to wait a bit.

**Comment by komirineni** [comment]
if you do not release in NuGet. we have to take the google component project manually for the marker changes everytime.

**Comment by valentasm1** [comment]
I dont have rights to release. It should take at most 1d. Worst 2-3d.
@rungwiroon  maybe you could add me as owner to nuget. User https://www.nuget.org/profiles/valentasm

**Comment by komirineni** [comment]
ok take your time and release ASAP. and thanks for the prompt reply.

**Comment by rungwiroon** [comment]
@valentasm1 
I've sent you a request to be an owener of BlazorGoogleMaps nuget.

**Comment by valentasm1** [comment]
Thank you @rungwiroon I updated package. I am a bit new to opensource so let me know if you wont like some actions. I am always keen to learn.
@komirineni I updated package to 0.4.7-alpha

**Comment by komirineni** [comment]
Please release in to the main package: Vlasdkoqw

**Comment by valentasm1** [comment]
@komirineni no no. You get it wrong. Main package is this. Vlasdkoqw is package which i created as test/temporally while this one will be updated (not case now). Now i have rights to release and update this package so everything will be faster. You can change to this one.
I will deprecate Vlasdkoqw.

**Comment by komirineni** [comment]
May I know what is the name of the package to search in NuGet

**Comment by valentasm1** [comment]
Updated readme of this package. Nuget link is https://www.nuget.org/packages/BlazorGoogleMaps
