### ISSUE TITLE
Is there a way to get a callback function whenever the zoom level changes?

### ISSUE THREAD

**Issue by SeppPenner** [rungwiroon/BlazorGoogleMaps#110]
I'm looking for a way to get notified whenever the zoom level is changed, is this possible somehow?

The JS version of GoogleMaps has a event called `zoom_changed` for that: https://developers.google.com/maps/documentation/javascript/events. Can this be used?

**Comment by valentasm1** [comment]
I think you should check samples before asking such questions
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapEvents.razor

**Comment by SeppPenner** [comment]
Oh, sorry. You're right, I didn't see that example. Thanks.
