### ISSUE TITLE
MarkerClustering - Custom Cluster images

### ISSUE THREAD

**Issue by Nickztar** [rungwiroon/BlazorGoogleMaps#111]
Currently the Clusters are included with the project and I am unable to find a clear way to change this. Could it be possible to have a way to specify a ImagePath for the clustered image. Shouldn't be to big of a deal from what I can tell from code. 

If this is something that is wanted I might try and fix this if I get the time.

[Gist for JS Part](https://gist.github.com/Nickztar/f31928fd8e41e4176e159a6b4502bd12)
Something like this ^ (obviously needs to be set from Blazor side aswell)

**Comment by valentasm1** [comment]
I really though it is possible.
Will add this to lib in couple days

**Comment by Nickztar** [comment]
Perfect! There are also some other options that could be set for a cluster that might be worth adding. But probably requires some more work.

**Comment by valentasm1** [comment]
Let me know if it works.

**Comment by Nickztar** [comment]
Looks good! Closing this, there are also other options that could be set for a cluster but this will do fine. Thanks!

**Comment by valentasm1** [comment]
Just give me sample of code and i will implement other options too.

**Comment by Nickztar** [comment]
These options are directly taken from the google repo

[Gist of options](https://gist.github.com/Nickztar/024b7bc176d0d9967a761b242f724e4c)

[Google Repo](https://github.com/googlemaps/js-markerclustererplus/blob/main/src/markerclusterer.ts)

**Comment by valentasm1** [comment]
I mean not possible functionality but code which i copy paste to this solution.
I am lazy person and dont have time to look up and implement :)
