### ISSUE TITLE
Some support for 3rd party libraries to Google Maps

### ISSUE THREAD

**Issue by Nickztar** [rungwiroon/BlazorGoogleMaps#112]
Hi!
Would be really nice to support something like [https://github.com/googlemaps/js-markerwithlabel](https://github.com/googlemaps/js-markerwithlabel).

Not sure how much work something like this would be to implement but its something pretty nice to have, or maybe a clear way on a workaround for this.

**Comment by valentasm1** [comment]
Sorry i wont do. I am honest. You could try compile to js and then do some interop.

**Comment by Nickztar** [comment]
Understandable!
I will try getting it to work and maybe get back if I figure something out and other people can benefit from my work. 👍🏼
