### ISSUE TITLE
DrawingManager JSON.stringify not working for OverlayCompleteEvent

### ISSUE THREAD

**Issue by ahellrigl** [rungwiroon/BlazorGoogleMaps#113]
Good afternoon, the work you have done is very good, my congratulations.
I need to apply the overlaycomplete event when finishing drawing a polygon using drawingManager, as used in javascript, when finishing drawing a polygon I need to retrieve the coordinates.

![image](https://user-images.githubusercontent.com/51087271/113914304-c8e01180-97b3-11eb-8d97-82e23904f3ab.png)

On the other hand, when I want to show only the polygon option and center the tools, they disappear, throwing an error.

![image](https://user-images.githubusercontent.com/51087271/113914456-f462fc00-97b3-11eb-9b37-681256fee1ce.png)
![image](https://user-images.githubusercontent.com/51087271/113914838-5facce00-97b4-11eb-805c-dfceff5f1eba.png)

Thanks a lot.
Greetings.

**Comment by valentasm1** [comment]
Is it possible get full minimum working example?
There are no example of DrawingManager in solution.

**Comment by ahellrigl** [comment]
[BlazorGoogleMaps-master.zip](https://github.com/rungwiroon/BlazorGoogleMaps/files/6278593/BlazorGoogleMaps-master.zip)

Good morning, thanks for the prompt reply.
I attach the original project shared by you, I reduced it only to what I need, it is the ServerSideDemo project, MapPolyline.

I leave an image of the javascript code used in .net.
![image](https://user-images.githubusercontent.com/51087271/114026793-0c3a8e80-984d-11eb-97d5-9e0880741561.png)

Thanks a lot.

Greetings.

**Comment by valentasm1** [comment]
You are doing a bit wrong. Just a bit.
I added demo showing how it should be done.
Problem that when overlaycomplete triggers it return reference to dom element(???) which could not be serialized since it have circular structure. You need more debuging to find right way to do it. It is in objectManager.js:69. You could try to use simpleStringify from same file. Maybe it would help a bit.

My commit 
https://github.com/rungwiroon/BlazorGoogleMaps/commit/33aa964a228110a4e8fec5325cebbb31b0a78bc2

Please never again paste picture in github solutions. Respect others. If it is easy for you, but it is super hard for my to rewrite code. Pasting code in github issues is super easy. 
Read here
https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by valentasm1** [comment]
I could try again next time i will have some free time. Next or week after that. Summer is coming, so less free time :)

**Comment by ahellrigl** [comment]
Dear good morning.
Thank you very much for the help, I was able to recover the coordinates of the drawn polygon, it is exactly the functionality I needed.

In ```BlazorGoogleMaps-33aa964a228110a4e8fec5325cebbb31b0a78bc2\GoogleMapsComponents\wwwroot\objectManager.js```

replace:
```javascript
            var guid = googleMapsObjectManager.addObject (args [0]);

            await item.invokeMethodAsync ("Invoke", JSON.stringify (args), guid);
```
by:
```javascript
            var guid = googleMapsObjectManager.addObject (args [0]);

            var locations = args [0] .overlay.getPath (). getArray ();
            var coordinates = "";
            var array = [];

            for (var i = 0; i <locations.length; i ++) {
                coordinates + = locations [i] .lat (). toFixed (6) .toString () + "," + locations [i] .lng (). toFixed (6) .toString () + ";";
            }
            array.push (coordinates);

            await item.invokeMethodAsync ("Invoke", JSON.stringify (array), guid);
```

And in ```BlazorGoogleMaps-33aa964a228110a4e8fec5325cebbb31b0a78bc2\ServerSideDemo\Pages\DrawingManagerPage.razor.cs```

replace:
```c#
            await drawingManager.AddListener <OverlayCompleteEvent> ("overlaycomplete", (arg) =>
           {
               var ss = "asd" + arg.Overlay;
           });
```
by:
```c#
 await drawingManager.AddListener <string> ("overlaycomplete", async (Coordinates) => await OveralyComplete (Coordinates));
```

![image](https://user-images.githubusercontent.com/51087271/114208504-ed62f780-9933-11eb-8577-6f32e1004069.png)

I apologize for pasting the code into an image.

Again thank you very much.

**Comment by valentasm1** [comment]
It is not solution. It is hardcoded workaround. Also returning coordinates as string doesnt sound as good approach.
This solution solves your problem, but dont solves it as library should.
I dont know what to recommend. I will try to look at it in coming days.

**Comment by valentasm1** [comment]
The main reason why i solved since it is pleasure to work something very different than at work.
So i updated DrawingManagerPage demo page.
Now it works almost as expected. arg.Overlay is JObject so you could read, deserialize or do what you want to do. In your case extract coordinates. 

```
await drawingManager.AddListener<OverlayCompleteEvent>("overlaycomplete", (arg) =>
            {
                //Overlay object is JObject with all properties,
                //so need to serialize, extract required info depending on your needs
                var s = arg.Overlay.ToString();
                var ss = "asd" + arg;
            });
```

**Comment by valentasm1** [comment]
The main reason why i solved since it is pleasure to work something very different than at work.
So i updated DrawingManagerPage demo page.
Now it works almost as expected. arg.Overlay is JObject so you could read, deserialize or do what you want to do. In your case extract coordinates. 

```
await drawingManager.AddListener<OverlayCompleteEvent>("overlaycomplete", (arg) =>
            {
                //Overlay object is JObject with all properties,
                //so need to serialize, extract required info depending on your needs
                var s = arg.Overlay.ToString();
                var ss = "asd" + arg;
            });
```

**Comment by ahellrigl** [comment]
Dear thank you very much, with this change that you added I will be able to continue updating your library.

As you indicate, my modification only solved my need, it is excellent that it has been added to the library.

I thank you again for your support.

Greetings.
