### ISSUE TITLE
how to show a heat trail  like a truck or jogger

### ISSUE THREAD

**Issue by weedkiller** [rungwiroon/BlazorGoogleMaps#115]
hello is it possible to show a trail of a joggers, or trucks and have it autofade in say 10 mins to avoid taffic jams etc

**Comment by valentasm1** [comment]
I think you could use polylines with you custom logic in you component. For my knowledge google don't have such things out of the box.
Or you could use Heatmap which would look better but it is not so much flexible.

**Comment by valentasm1** [comment]
Maybe this could help
https://github.com/rungwiroon/BlazorGoogleMaps/issues/102

**Comment by weedkiller** [comment]
ok thanks I understand it doesn't have anything to do with google.. just that this is a _common map feature_ that developers have to implement on their own repeatedly.

the other concern is the frame rate and any leaks
