### ISSUE TITLE
Binding Height to a variable does not work.

### ISSUE THREAD

**Issue by kevonh** [rungwiroon/BlazorGoogleMaps#116]
`    <GoogleMap @ref="@map" Id="map" Options="@mapOptions" Height="@($"{browser.Height-200}px")"></GoogleMap>
`

Using https://github.com/EdCharbeneau/BlazorSize to get access to browser dimensions.  
It works on initial load, but not after resize event.
I have debugged and ensured that the resize event is happening.

**Comment by valentasm1** [comment]
Looking at this issue resize doesnt looks so trivial. I am not sure it is even possible.
https://stackoverflow.com/questions/743214/how-do-i-resize-a-google-map-with-javascript-after-it-has-loaded

**Comment by valentasm1** [comment]
If you will find more info let me know. I will dig deeper once i will have more freetime. Around july probably :).

**Comment by valentasm1** [comment]
Now i see. I am almost sure this one question was asked some time ago.
You could try dig some old issues and check one.

**Comment by valentasm1** [comment]
I could try to do for you tomorow

**Comment by valentasm1** [comment]
Does this help?
https://github.com/rungwiroon/BlazorGoogleMaps/issues/35

**Comment by kevonh** [comment]
Yes, but as I mentioned over there...  it requires one TINY change to the solution provided.

`    <div style="height:@Height">
        <GoogleMap @ref="@map" Id="map" Options="@mapOptions" Height="100%"></GoogleMap>
    </div>
`

Then do whatever you need to do to bind @Height

I might suggest adding some documentation to the "Height" property, or even remove it so that it's always 100%.  If you do this then you will FORCE users down the path of using a parent DIV for the map instead of using your parameter only to find that it does not work like all other types of properties.

Thank you.

**Comment by valentasm1** [comment]
If you want you could make PR.

**Comment by kevonh** [comment]
Done

**Comment by valentasm1** [comment]
Thank you for your time.
