### ISSUE TITLE
No support for set_at, insert_at, and remove_at events on Polygons.

### ISSUE THREAD

**Issue by Mr-Technician** [rungwiroon/BlazorGoogleMaps#121]
I'm using the Polyline demo to add a polygon to my page. The default events work fine when adding new points but don't track any changes to  existing points. According to the Google docs, this is what set_at, insert_at, and remove_at are for. I've tried adding them using a combination of `Event` and `MouseEvent` but to no avail:

```c#
private async Task StartDrawingPolygon()
    {
        polygon = await Polygon.CreateAsync(map1.JsRuntime, new PolygonOptions()
        {
            Draggable = true,
            Editable = true,
            Map = map1.InteropObject
        });
        await polygon.AddListener<MouseEvent>("dragend", async (e) => await OnDrag(e));
        await polygon.AddListener<Event>("set_at", async (e) => await OnDrag2(e));
        await polygon.AddListener<MouseEvent>("insert_at", async (e) => await OnDrag(e));
        await polygon.AddListener<MouseEvent>("remove_at", async (e) => await OnDrag(e));

        path.Clear();
    }
```

How do I track changes to the polygon? If I can find the right event I can call GetPath and get a copy of its location that way.

**Comment by valentasm1** [comment]
Ahaa. It is a bit different story. 
If you know how Observable collection works so it is close to that. It is not directly relate to google maps, but more to MVCArray. 
Here is example of google maps
```
google.maps.event.addListener(flightPath.getPath(), "insert_at", getPath);
```
where getPath returns MVCArray and that array triggers event. In BlazorGoogle map it return IEnumerable<LatLang> which dont have such events.
If you need not so technical explanation let me know.
In my knowleadge there is no working solution in BlazorGoogleMaps, but you could make PR. Like i said it is not related to google maps itself

**Comment by valentasm1** [comment]
Here is reference to google documentation
https://developers.google.com/maps/documentation/javascript/reference/event#MVCArray

**Comment by Mr-Technician** [comment]
I don't know much about MVCArray so more information would be helpful if you have it.

**Comment by valentasm1** [comment]
set_at, insert_at, and remove_at
are array function
https://developers.google.com/maps/documentation/javascript/reference/event#MVCArray-Events
Currently there is no such functionality in this library and it is out of scope. 

You could do it two way. Either use all new fresh cordinates or create you own custom js library which will handle such case.

**Comment by Mr-Technician** [comment]
I realized that adding a save button to the map is a perfectly workable solution. I allow users to add up to three points using the click handler, after which they must use the tools on the map to adjust the points. Clicking save will call `polygon.GetPath()` to return the current state.

**Comment by valentasm1** [comment]
But you wont know which coordinates were added. You will need to resave all.
You could check with existing coordinates and then all which dont match treat as new.

So could i close issue?
