### ISSUE TITLE
Context Menu?

### ISSUE THREAD

**Issue by Enritski** [rungwiroon/BlazorGoogleMaps#122]
Hi, I am trying to add a right-click context menu to my Blazor page that has a BlazorGoogleMaps control on it.
I can successfully add an event listener for the "rightclick" or "contextmenu" events but, as far as I can tell, I can only pass the `GoogleMapComponents.Maps.MouseEvent` type as a parameter to my hander.  This type lets me access the `LatLng` for the point on the map where I clicked but does not provide access to the pixel location so that I could draw my context menu in the correct place.

Is there any way to get at the pixel coordinates (top, left) from the click event?

Many thanks!

```
await _map1.AddListener<MouseEvent>("contextmenu", OnRightClick);
...
private void OnRightClick(MouseEvent args)
{
    var location = args.LatLng; //This is the map coordinate of the click
    _mapContextMenu?.Show();    //I also need to know the pixel coordinates so I can show my menu in the correct place
}
```

**Comment by valentasm1** [comment]
I think you are mixing smth. You want screen coordinate where user clicked and it has nothing to do with map itself.
What are business case?
Why drowing some pop up in coordinate on map does not suit you?

**Comment by Enritski** [comment]
Thank you for the quick reply!

What I actually need to do is to allow the user to add a marker to the map when they right-click on it.  The marker could be be one of several types - hence I need the context-menu so they can specify what type of marker to add.  I *will* need the lat/lng for the location, but I also need to draw the pop up in the correct screen position.

As you said, I may well be mixing things up, and I almost certainly am making things more complex than they need to be.

**Comment by valentasm1** [comment]
Sorry i wont help at this issue. This is not google map functionality which is missing. There are couple examples which shows smth related to that.
Maybe you could add pin on right click, then show pin info window with pin type selection

http://jsfiddle.net/refhat/XW35W/2/
https://stackoverflow.com/questions/51569798/google-maps-api-custom-popups-example-code-breaks-in-vuejs-single-file-compone
https://stackoverflow.com/questions/44853418/engaging-the-right-click-on-google-maps
https://stackoverflow.com/questions/5147923/show-context-menu-on-click-marker

**Comment by Enritski** [comment]
Thanks again.  I was hoping that I would be able to have my BlazorGoogleMaps event handler be able to get both the map coordinate (as it does now) *and* the mouse position relative to the map component's bounding `div`.  I'm sure I'll work it out eventually.
Thanks for your help anyway.  I'll close the issue now.

**Comment by valentasm1** [comment]
If you have time and will remember this it would be great if you could post solution here. Maybe one day someone will have same issue.
