### ISSUE TITLE
Readme for setting up clustering for a blazor webassembly app could be clarified

### ISSUE THREAD

**Issue by mlinnen** [rungwiroon/BlazorGoogleMaps#123]
The docs mention adding a script tag for clustering to work, however the example only works in server side blazor due to the use of the @ symbol in the url.  For blazor webassembly project the script should be:
`
<script src="https://unpkg.com/@googlemaps/markerclustererplus/dist/index.min.js"></script>
`

**Comment by mlinnen** [comment]
I would be glad to take this issue and submit a PR for it.

**Comment by valentasm1** [comment]
Always wellcome :)

**Comment by valentasm1** [comment]
Honestly i am accepting almost all PR.
