### ISSUE TITLE
Marker Cluster On Click Event

### ISSUE THREAD

**Issue by Mr-Technician** [rungwiroon/BlazorGoogleMaps#126]
I'm writing an app where people can enter their location down to the city. This means several markers may be located in the exact same space. Is it possible to attach an onclick event to a marker cluster to represent all of them?

**Comment by valentasm1** [comment]
Is it possible in original one?
I am not very familiar with clustering.
You could check solution here and then i could implement it in this library
https://developers.google.com/maps/documentation/javascript/marker-clustering

**Comment by valentasm1** [comment]
Any update?

**Comment by Mr-Technician** [comment]
Hey sorry, this got pushed to the back burner! I will check later today or tomorrow...

**Comment by valentasm1** [comment]
Any update?

**Comment by Mr-Technician** [comment]
No, sorry, I'll close this... 😄
