### ISSUE TITLE
Route creation

### ISSUE THREAD

**Issue by komirineni** [rungwiroon/BlazorGoogleMaps#13]
Hi Team,

Is it possible to create Route with blazer google maps? my requirement is to create a route between two locations in blazor app. am using your package since 3 months onwards for my project for all maps services. let me know when this feature will be available if it is not available now?

**Comment by cyberyaga** [comment]
Well... I had the same question and saw that the classes for DirectionsService where not yet complete. So I decided to fork this and add the feature.

Here is my fork: https://github.com/cyberyaga/BlazorGoogleMaps

There is a example in the readme on how to do a route. 

Thanks

**Comment by valentasm1** [comment]
I will update this issue as soon as generous @cyberyaga  will make a pull request. After that i will update nuget and readme.

**Comment by cyberyaga** [comment]
Great... Let me button up some stuff... Make sure my code is pretty 😁 and I'll make the pull request.

**Comment by komirineni** [comment]
> Well... I had the same question and saw that the classes for DirectionsService where not yet complete. So I decided to fork this and add the feature.
> 
> Here is my fork: https://github.com/cyberyaga/BlazorGoogleMaps
> 
> There is a example in the readme on how to do a route.
> 
> I'm currently working on adding the Place autocomplete search as well, so that might be coming soon.
> 
> Hopefully, my code can be merged into this branch.
> 
> Thanks

really thanks for your quick help let me know once you have done all the changes. currently a using route option changes from your code.
Thanks a lot !

**Comment by komirineni** [comment]
> Well... I had the same question and saw that the classes for DirectionsService where not yet complete. So I decided to fork this and add the feature.
> 
> Here is my fork: https://github.com/cyberyaga/BlazorGoogleMaps
> 
> There is a example in the readme on how to do a route.
> 
> I'm currently working on adding the Place autocomplete search as well, so that might be coming soon.
> 
> Hopefully, my code can be merged into this branch.
> 
> Thanks

can we get the estimated time between two locations  like google.maps.DistanceMatrixService()

**Comment by cyberyaga** [comment]
That might be a little tough... It is not possible now, but I also need that for my project. I wanted to focus on getting the map to display the routes and waypoints first... So, I will look at a way to implement returning the direction back to blazor.

**Comment by valentasm1** [comment]
I updated nuget to BlazorGoogleMaps 0.4.8-alpha. Will update samples later.

**Comment by valentasm1** [comment]
@komirineni i will try to look for estimate time functionality. I will try to give estimate today.

**Comment by valentasm1** [comment]
@cyberyaga if you are ok i could include you as contributor. It would be easier to release updates. Is it ok with you?

**Comment by cyberyaga** [comment]
@valentasm1 Sure... That would be great... Thanks

**Comment by valentasm1** [comment]
@rungwiroon Maybe you could add as contributor @cyberyaga as well. Guy works actively on functionality could help a lot :).

**Comment by valentasm1** [comment]
@komirineni is it everything ok with route functionality?
I create new issue for route estimate https://github.com/rungwiroon/BlazorGoogleMaps/issues/15

**Comment by komirineni** [comment]
> @komirineni is it everything ok with route functionality?
> I create new issue for route estimate #15

Route creation working fine as per my testing ,but estimate time functionality not available. am using google map api nuget in my blazor to get the estimate duration between two locations.

**Comment by cyberyaga** [comment]
ok... I got a little confused with the DistanceMatrixService bit... My assumption was that you wanted to get the estimated time and distance for a route. I don't know if that's what you are looking for.

But never the less, I've added code on my fork that returns the DirectionsResult from the GMap API.

Here is a snippet of how to get the distance and duration of a route:
```
	private async Task AddDirections()
	{
		//Adding a waypoint
		var waypoints = new List<DirectionsWaypoint>();
		waypoints.Add(new DirectionsWaypoint() { Location = "Bethlehem, PA", Stopover = true } );

		//Direction Request
		DirectionsRequest dr = new DirectionsRequest();
		dr.Origin = "Allentown, PA";
		dr.Destination = "Bronx, NY";
		dr.Waypoints = waypoints;
		dr.TravelMode = TravelMode.Driving;
		
		//Calculate Route
		DirectionsResult result = await dirRend.Route(dr);

		if (result.Routes.Count() > 0)
		{
			distance = result.Routes.ElementAt(0).Legs.ElementAt(0).Distance.Text;
    		        duration = result.Routes.ElementAt(0).Legs.ElementAt(0).Duration.Text;
		}
		
	}		
```
Once I've done proper testing of this, I'll make a pull request to the main project.

**Comment by cyberyaga** [comment]
I've created a pull request to merge this functionality with this project.

**Comment by valentasm1** [comment]
@komirineni happy to announce that @cyberyaga added functionality of routes.
There are also duration and distance for routes. You could check samples or readme file
