### ISSUE TITLE
When to use `Map` vs `GoogleMap`?

### ISSUE THREAD

**Issue by MrYossu** [rungwiroon/BlazorGoogleMaps#130]
When I first started using this package, I used the `mapEvents` sample as a basis, and so had a local variable of type `GoogleMap`

I now want to get the map zoom, and have found that you can't do this with a `GoogleMap` (unless I've missed something), but rather need a `Map` object, which is creating differently.

Please can you provide some guidance as to when you would use one over the other?

**Comment by valentasm1** [comment]
You are right. You should use GoogleMap and then get zoom by calling map1.InteropObject.GetZoom().
GoogleMap inherits Map.
You could not create Map so straight forwrard as google map.

**Comment by MrYossu** [comment]
Thanks for the reply. Please can you update the samples, as it's pretty confusing right now.

**Comment by valentasm1** [comment]
Updated readme saying that you should check server side samples.
If you want you could make PR with updated samples
