### ISSUE TITLE
Resizing a GroundOverlay

### ISSUE THREAD

**Issue by taylorjimbo** [rungwiroon/BlazorGoogleMaps#132]
I was wondering if there is a better way of doing this. 

Currently, I have draggable and resizable rectangle with a listener for bounds changed. When the bounds changes I remove the current overlay and add it back with the new bounds. 

``` 
 private async Task OnBoundsChanged()
    {
        if (rectangle != null)
        {
            Debug.Print("Bounds changed -> ");
            var bounds = await rectangle.GetBounds();
            Debug.Print("        North = " + bounds.North);
            Debug.Print("        South = " + bounds.South);
            Debug.Print("        East = " + bounds.East);
            Debug.Print("        West = " + bounds.West);

            if (_mapoverlay != null)
            {
                await _mapoverlay.SetMap(null);
                //_mapoverlay.Dispose();
                _mapoverlay = null;
                await AddOverlay(bounds);
            }

        }

        StateHasChanged();
    }

    private async Task AddOverlay(LatLngBoundsLiteral _bounds)
    {
        _mapoverlay = await GroundOverlay.CreateAsync(map1.JsRuntime, "office.jpg", new LatLngBoundsLiteral()
        {
            North = _bounds.North,
            South = _bounds.South,
            East = _bounds.East,
            West = _bounds.West
        }, new GroundOverlayOptions()
        {
            Opacity = 0.9,

        });

        await _mapoverlay.SetMap(map1.InteropObject);
    }

**Comment by valentasm1** [comment]
What is use case?

**Comment by taylorjimbo** [comment]
> What is use case?

To overlay a blueprint of a building, or part of the building on the map.

**Comment by valentasm1** [comment]
Honesly i dont know. I used very similar technique to yours in mobile. Always delete and add new.

Based on google reference there is no out of the box solution
https://developers.google.com/maps/documentation/javascript/reference/image-overlay#GroundOverlay

You should search javascript solution. If you found that one than you could adopt to blazor pretty fast.

**Comment by valentasm1** [comment]
Have you found working example?

**Comment by taylorjimbo** [comment]
Nothing yet, I’m still having issues with dragging the overlay. Sometimes the dragging leaves a copy. So, I end up the multiple overlays.

**Comment by valentasm1** [comment]
Any update?
