### ISSUE TITLE
Marker.GetIcon doesn't return the expected Symbol object

### ISSUE THREAD

**Issue by sburgin** [rungwiroon/BlazorGoogleMaps#133]
Steps to reproduce:

- Create a new marker while initializing the marker's Icon property with a Symbol instance (i.e. Icon = new Symbol())
- Call GetIcon() via the resulting marker.
- Note the resulting OneOf type (string, Icon, or Symbol)

Currently the resulting OneOf type will be string instead of the expected Symbol (per initialization). In fact, reading out the string's contents appears to be the json representation of the underlying js object? That's about as deep into the implementation as I went.

This currently makes it somewhat difficult to "get" a .NET Symbol object representation without resorting to storing the initialized object in a .NET collection or reconstructing it manually from the json.

**Comment by valentasm1** [comment]
Good catch. 
Summer. Holiday season. Will take a look on september. 
I think it is bug that on creating (serializing) it dont set key "dotnetTypeName" to object, so when deserializing it dont find and return string.
Helper.cs:263

**Comment by sburgin** [comment]
I think the deserialization to Symbol fails because property Path is of type OneOf, which throws a NotSupported exception (OneOfConverter only implements serialization).

It seems the OneOfConverter will need implementation of ReadJson (a more general deserialization solution) or Symbol itself needs specialized deserialization to Path property.

**Comment by valentasm1** [comment]
Closed since migrated to system.text.json
