### ISSUE TITLE
Marker.SetIcon is missing the Symbol overload

### ISSUE THREAD

**Issue by sburgin** [rungwiroon/BlazorGoogleMaps#134]
There are marker SetIcon overloads for string and Icon, but oddly enough Symbol is missing.

Given Symbol seems to work during marker initialization, it seems odd not to support its setter.

**Comment by valentasm1** [comment]
Look related to Marker.GetIcon doesn't return the expected Symbol object #133

**Comment by valentasm1** [comment]
Closing since migrated to system.text.json. Not relavant
