### ISSUE TITLE
Can we style a marker label?

### ISSUE THREAD

**Issue by MrYossu** [rungwiroon/BlazorGoogleMaps#135]
Not sure if this question is directly related to the package, or a more general maps one, but I thought I'd start off here and see.

I create markers as follows...

```c#
        Marker marker = await Marker.CreateAsync(_map.JsRuntime, new MarkerOptions {
          Position = new LatLngLiteral(s.Longitude, s.Latitude),
          Map = _map.InteropObject,
          Label = s.FullName,
          Animation = Animation.Drop,
          Icon = "http://maps.google.com/mapfiles/ms/micons/blue-dot.png"
        });
```

..and then add them to a collections, which is shown on the map (using clustering) as follows...

```c#
    MarkerClustering markerClustering = await MarkerClustering.CreateAsync(_map.JsRuntime, _map.InteropObject, _markers);
```

This all works fine, but the marker labels aren't very easy to read. Is there any way to set styling on them? I tried inspecting them with the browser tools, but it didn't reveal much.

Thanks for any help.

**Comment by valentasm1** [comment]
Check this sample
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapInfoWindow.razor

**Comment by MrYossu** [comment]
@valentasm1 Thanks for the quick reply, but that's not what I meant. That sample adds a marker with a label of "Test 0" abd so on. It's that label that I want to style. I'm not using a pop-up window when you click on the marker, as I have a separate panel that shows more info, it's the actual marker label that isn't very clear.

Any idea how I style the marker label itself? Thanks

**Comment by valentasm1** [comment]
Do you have example on javascript?

**Comment by MrYossu** [comment]
@valentasm1 Not sure what you mean. I'm doing pretty much what you saw in my first post to create the markers, basically what you do in the sample. All I want to do is be able to style the label that is added to the marker.

Please can you clarify what you meant?

**Comment by valentasm1** [comment]
Forget blazor. Try to find how archieve your desired functionality in google maps javascript. Maybe someone had exact same problem. Then we just need to port it to blazor.

**Comment by MrYossu** [comment]
@valentasm1 Ah, I see what you mean. Will see what I can find. Thanks

**Comment by MrYossu** [comment]
@valentasm1 Looks like there are a few ways of doing it...

[SO question, with a few answers](https://stackoverflow.com/questions/42323569/customize-google-map-api-v3-marker-label)

Not sure which fits better with your package.

**Comment by valentasm1** [comment]
What about this one?
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ClientSideDemoNet5/Pages/MapMarker.razor

**Comment by MrYossu** [comment]
@valentasm1 What about it? That's the one I used as a basis for my code, and suffers from exactly the issue I am trying to get around. The label is plain black text, which can be quite hard to read, depending on what map features are around and below it. I want to be able to style that label so it can be read more clearly.

**Comment by valentasm1** [comment]
So changing font size, color isnt enough for you.
Please check this
https://github.com/rungwiroon/BlazorGoogleMaps/issues/85

**Comment by MrYossu** [comment]
@valentasm1 That's exactly what I want. I didn't see that issue. I also didn't realise that the `Label` property in `Marker` can be a `MarkerLabel` instead of a string.

Please can you update the samples to show this as well. Given the lack of documentation, the samples are the only docs, and if useful features like this are missing, we don't get to find out about them.

Thanks

**Comment by valentasm1** [comment]
You could make PR if you want.

**Comment by valentasm1** [comment]
I have time only for mosst important stuff like bugfix, answer issues and small features. 
Documentation is so bad since i dont gave time. I totally agree that it couldbe way better

**Comment by MrYossu** [comment]
@valentasm1 Don't get me wrong, I wasn't complaining, the package is brilliant, and the fact that you respond to issues so quickly is better than a lot of people!

I'm not sure I have the confidence to improve the samples myself, but I'll have a look and maybe do a PR.

Thanks again

**Comment by MrYossu** [comment]
@valentasm1 Hmm, just been playing with this, and the class doesn't seem to work. I modified the MapMarker sample, changing [lines 102-112](https://github.com/rungwiroon/BlazorGoogleMaps/blob/d16fb0acdcea718c280cb27a35bfabac86c6d739/ServerSideDemo/Pages/MapMarker.razor.cs#L102-L112) to look like this (commented-out code omitted)...

```c#
var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
{
    Position = latLngLiteral,
    Map = map,
    Label = new MarkerLabel {
      ClassName = "marker-label",
      Text = $"Test {markers.Count}"
    },
});
```

I also added the following to the `.razor` file...

```css
<style>
  .marker-label {
    color: red;
  }
</style>
```

...but the class was ignored.

If I set the colour and font weight in the `MarkerLabel` itself, it works, but I want more control over the styling than just the few properties that class offers.

Any ideas? Thanks again.

**Comment by valentasm1** [comment]
![image](https://user-images.githubusercontent.com/8047891/128815950-4b8631ff-a890-4df7-91b7-0707474866f5.png)
It looks like working. Like in issue #85 says it could be related to versioning.
Updated server side demo with Add styled font marker option which seem to work
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarker.razor

**Comment by MrYossu** [comment]
@valentasm1 OK, something weird going on then. I just downloaded the latest version of the code and ran the server-side demo, and now the marker doesn't have any label at all...

![Capture](https://user-images.githubusercontent.com/10185332/128875974-00b5d8e3-f4e1-4575-9829-9aa6ccb812a6.png)

To repeat, this is the latest code, downloaded about five minutes ago, unchanged by me, running the server-side demo project, and displayed in Edge 92.0.902.62.

Any ideas? Thanks again.

**Comment by valentasm1** [comment]
Are you sure you pressed "Add styled font marker" button?

**Comment by MrYossu** [comment]
Duh!!!!!

OK, so I'm sleepy, missed that bit.

Thanks again.
