### ISSUE TITLE
Can we suspend updating the map until all markers are added?

### ISSUE THREAD

**Issue by MrYossu** [rungwiroon/BlazorGoogleMaps#141]
My map can have a couple of hundred markers, and these are added quite slowly.

Is there a way to add them without the map being updated, then telling the map to redraw afterwards? That way, it would only redraw once, after all markers were added?

Or, is there a better way to add a lot of markers without it taking a long time?

Thanks

**Comment by valentasm1** [comment]
Have you used MarkerList?
https://github.com/rungwiroon/BlazorGoogleMaps/wiki/MarkerList-for-multi-markets-manipulation

**Comment by MrYossu** [comment]
@valentasm1 Thanks for the pointer, I hadn't noticed that feature.

How would I add a listener when adding the markers that way? The way I'm doing it now, I create the marker, add the listener, then add the marker to the map. I don't see any way to add a listener when creating a dictionary as in that sample you linked.

Thanks again.

**Comment by valentasm1** [comment]
I dont have code with me, but when you  add items you assign some id and then based on that id you could attach events. Or smth like that.
If you wont find let me know. I will take a look at code tomorrow.

**Comment by valentasm1** [comment]
So like i said there is function AddListeners which accept same keys and event name to attach
