### ISSUE TITLE
Bug. Drawing Control DrawingControlOptions with DrawingModes returns console errors

### ISSUE THREAD

**Issue by Mr-Technician** [rungwiroon/BlazorGoogleMaps#142]
I have a polygon that closely models the one in the Polyline/Polygon example in the demo site. However, it always closes after adding the third point. I can keep adding additional points if I keep clicking but it's not a very intuitive experience.

Alternatively, I could use a polyline, but there doesn't seem to be a way to join the first and last points together to "close" the polyline. Maybe I could add a button to add a final point at the same position as the first point to mimic this...

The end goal is to allow the user to draw any shape on the map. (This is used to define the borders of a roadway project.)

How would you handle this scenario?

**Comment by valentasm1** [comment]
You could use DrawingManager to let draw any shape.
Personally never used so not sure how it works, but it looks like it would suit your needs.
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/DrawingManagerPage.razor.cs

**Comment by Mr-Technician** [comment]
Perfect, thanks!

Do you know of a way to load a polygon back onto the map using drawingmanager? It would also be nice if the polygon were editable after creation, but that's not absolutely necessary.

**Comment by valentasm1** [comment]
What i get DrawingManager it is just a tool to get polygons, rectangles, polylines, circles, and markers on the map. You get any of these objects and save them accordingly and then create as casual object. 
For example you draw polyline, save it, then next time load it and Editable=true via PolylineOptions on creating. You need to play around with options.
Here comes another problem. How to know which coordinates was changed which not. What i did for my project just delete old coordinates in db and save new.

**Comment by Mr-Technician** [comment]
I think that makes sense, thanks.

I've run into another issue though: If I provide Drawing Control options the drawing manager UI suddenly disappears. Take a look at DrawingManagerPage.razor.cs and uncomment the drawing control options line to see what I mean:

```csharp
List<OverlayType> overlayTypes = new List<OverlayType>();
            overlayTypes.Add(OverlayType.Polygon);

            var drawingControlOptions = new DrawingControlOptions()
            {
                Position = ControlPosition.TopCenter,
                DrawingModes = overlayTypes
            };

            managerOptions = new DrawingManagerOptions()
            {
                Map = map1.InteropObject,
                PolygonOptions = polygonOptions,
                DrawingMode = OverlayType.Polygon,
                DrawingControl = true,
                DrawingControlOptions = drawingControlOptions
            };

            drawingManager = await DrawingManager.CreateAsync(JsRuntime, managerOptions);
```

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.1.3

**Comment by Mr-Technician** [comment]
Fantastic, that solves the issue I was having, thank you!
