### ISSUE TITLE
DrawingManager.SetDrawingMode doesn't work

### ISSUE THREAD

**Issue by Mr-Technician** [rungwiroon/BlazorGoogleMaps#144]
I'm trying to make custom buttons to trigger the drawing mode of the drawing manager, but when I set the mode to polygon, the polygon control isn't activated on the map.

```csharp
await DrawingManager.SetDrawingMode(OverlayType.Polygon); //has no visible effect, though it does seem to set the mode in the Csharp object
```
This should be possible according to the stackoverflow and codepen:
https://stackoverflow.com/questions/9417872/custom-drawing-control-google-maps-v3-drawing-library
https://codepen.io/bozdoz/pen/jZNXNP?editors=0010

Also, it looks like there should be a null option to set the drawing manager back to a normal "grab hand" cursor so the user can interact with the map without drawing.

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.1.4
