### ISSUE TITLE
Rotating a GroundOverlay...

### ISSUE THREAD

**Issue by taylorjimbo** [rungwiroon/BlazorGoogleMaps#145]
This issue should not have been closed, because to implement this trick will require access to the onAdd() method of a Custom Overlay. Maybe I'm missing something obvious.  

Previously discussed... #120

> https://stackoverflow.com/questions/52948764/google-map-how-to-rotate-groundoverlay-need-trick

from @valentasm1
    your c# class

``` 
private async Task AddOverlay()
            {
                _mapoverlay = await GroundOverlay.CreateAsync(map1.JsRuntime, "https://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg", new LatLngBoundsLiteral()
                {
                    North = 40.773941,
                    South = 40.712216,
                    East = -74.12544,
                    West = -74.22655
                }, new GroundOverlayOptions()
                {
                    Opacity = 0.5
                });
    
                await _mapoverlay.SetMap(map1.InteropObject);
    
                await _jsObjectRef.InvokeAsync<string>("rotateOverlay", _mapoverlay.Guid);
    
            }
``` 
app.js (your js file)

```
function rotateOverlay(mapOverlayId){
  const mapOverlay = window._blazorGoogleMapsObjects[mapOverlayId];
  //Here you could manipulate it as google.maps.OverlayView object
}
```

It is more or less just and idea.
you could get access to google.maps.OverlayView and then try to manipulate it same as in some JavaScript solution examples.

**Comment by taylorjimbo** [comment]
I do need to add that I am able to rotate the entire map with the code below, but I want to rotate only the overlay.

```
function rotateOverlay(mapOverlayId) {
    const mapOverlay = window._blazorGoogleMapsObjects[mapOverlayId];

    document.getElementById('overlayslider').addEventListener("input", function () {
        mapOverlay.j.innerContainer.style.transform = 'rotate(' + this.value + 'deg)';
    });
}

```

**Comment by valentasm1** [comment]
Do you have fully working example in javascript?

**Comment by taylorjimbo** [comment]
The function posted “rotateOverlay” is the only JavaScript.

**Comment by valentasm1** [comment]
But you said it rotates map instead overlay. 
Also what are these elements "overlayslider"

**Comment by taylorjimbo** [comment]
overlayslider Is an input slider. See the example you pointed me to on stackoverflow.


This is without the slider, rotates everything 45 degrees.

```
function rotateOverlay(mapOverlayId) {
    const mapOverlay = window._blazorGoogleMapsObjects[mapOverlayId];

mapOverlay.j.innerContainer.style.transform = 'rotate(45deg)';
   
}
```

**Comment by valentasm1** [comment]
I just checked and it dont work. It rotates everything.
So do you  have WORKING example in javascript?

**Comment by taylorjimbo** [comment]
That is the issue. It rotates everything, I only want to rotate the overlay. What object is the div element for the overlay?

**Comment by valentasm1** [comment]
You could try to debug javascript and find out.  Sorry my time is very limited and i could help with debuging.

**Comment by valentasm1** [comment]
Closing due inactivity
