### ISSUE TITLE
GetPaths not working correctly

### ISSUE THREAD

**Issue by Mr-Technician** [rungwiroon/BlazorGoogleMaps#147]
I'm attempting to use `SetPaths` on a polygon and then Get the path again, like so:

```csharp
private async Task SetPath(List<IEnumerable<LatLngLiteral>> paths)
        {
            await polygon.SetPaths(paths);
            var test = await polygon.GetPaths();
            Console.WriteLine(test);
        }
```

Calling `GetPaths` results in this error but doesn't crash the Blazor circuit:

![image](https://user-images.githubusercontent.com/26885142/133669696-e589e72b-78bc-4704-8c4b-baa1f54cb5d1.png)

The `paths` object I am passing in is a valid set of coordinates.

**Comment by Mr-Technician** [comment]
Ok, the issue with `SetPaths` was on me but `GetPaths` still causes an error.

**Comment by valentasm1** [comment]
I will take a look on sunday.

**Comment by valentasm1** [comment]
Could not reproduce
https://github.com/rungwiroon/BlazorGoogleMaps/blob/3b10cef4508682e895dcddb11cd4fb458dcabc34/ServerSideDemo/Pages/MapPolyline.razor#L207
