### ISSUE TITLE
Intermittent error with MapClusterer

### ISSUE THREAD

**Issue by Enritski** [rungwiroon/BlazorGoogleMaps#149]
Hi,

I've noticed that there is sometimes a javascript exception thrown when using MapClustering - especially on mobile devices, if the phone has gone to sleep and is then woken up while viewing the page.  The following is the exception:
```
blazor.server.js:19 [2021-09-22T15:08:00.820Z] Error: Microsoft.JSInterop.JSException: MarkerClusterer is not defined
ReferenceError: MarkerClusterer is not defined
    at Object.addClusteringMarkers (https://dev-app.workmirror.com/_content/BlazorGoogleMaps/objectManager.js:567:31)
```
Turns out that it is a simple thing to fix - just ensure that the line to load the markerclustererplus javascript library appears _before_ the one for loading the objectManager, like this:
```
<script src="https://unpkg.com/@googlemaps/markerclustererplus/dist/index.min.js"></script>
<script src="_content/BlazorGoogleMaps/objectManager.js"></script
```
I recommend that the documentation and the demo projects are updated to reflect this.  Apologies, I am tied up with other things right now, so won't be able to submit a PR for this documentation change for about a week, at least.  Thought I'd flag this as an issue in case you have time to make the change before I do.

Thanks!

**Comment by valentasm1** [comment]
Great. Thank you

**Comment by valentasm1** [comment]
Updated server side sample
