### ISSUE TITLE
Typo in objectManager.js in OverlayType.MARKERL

### ISSUE THREAD

**Issue by joubierjc** [rungwiroon/BlazorGoogleMaps#152]
Hi 🙂

Sorry in advance for not doing this in a pull request, but i'm not really familiar with the concept of forking yet.

There's a typo inside **objectManager.js** that prevent you from switching to the overlay MARKER

Line 99:
```
case "google.maps.drawing.OverlayType.MARKERL":
	item2 = google.maps.drawing.OverlayType.MARKER;
	break;
```
should be MARKER instead of MARKERL:
```
case "google.maps.drawing.OverlayType.MARKER":
	item2 = google.maps.drawing.OverlayType.MARKER;
	break;
```

I'm looking forward for the fix. 
Thanks a lot for this repository !

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.1.8

**Comment by valentasm1** [comment]
Thank you very much for detailed instructions
