### ISSUE TITLE
undefined 'defaultView'

### ISSUE THREAD

**Issue by SykesJohn** [rungwiroon/BlazorGoogleMaps#158]
How do I figure out why I am seeing this failure:
common.js:formatted:3782 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'defaultView')
    at new _.Zha (common.js:formatted:3782)
    at it.i (map.js:formatted:3252)
    at js?key=AIzaSy....w&v=3:152

**Comment by valentasm1** [comment]
Could you give more context?
