### ISSUE TITLE
Can we suspend updating the map until all markers are added?

### ISSUE THREAD

**Issue by MrYossu** [rungwiroon/BlazorGoogleMaps#159]
@valentasm1 Note that this is a follow-up to a [previous question](https://github.com/rungwiroon/BlazorGoogleMaps/issues/141) that I had, that you closed too quickly.

My question was (and still is)...

_My map can have a couple of hundred markers, and these are added quite slowly._

_Is there a way to add them without the map being updated, then telling the map to redraw afterwards? That way, it would only redraw once, after all markers were added?_

_Or, is there a better way to add a lot of markers without it taking a long time?_

You pointed me to the [wiki page for `MarkerList`](https://github.com/rungwiroon/BlazorGoogleMaps/wiki/MarkerList-for-multi-markets-manipulation). However, that page has exactly the same issue that I had originally. Even when I use a `MarkerList`, the markers take a long time to appear.

Looking in the network tab of the browser dev tools, I can see that the reason is that for each marker, I get two XHR network calls, one with a link like https://localhost:1234/_blazor?id=PVnWb6yglfvaSh_HdH1bUA, without a response, but with a payload like this...

>}ÀµEndInvokeJSFromDotNetÌÉÃÙ][201,true,{"south":50.3590327,"west":-4.323901999999999,"north":55.9380253,"east":0.5637536}]

...and one with a similar link https://mypropertysurvey.uk/_blazor?id=PVnWb6yglfvaSh_HdH1bUA&_=1635696351949 but with a response like this...

>©À°JS.BeginInvokeJSÌË¾googleMapsObjectManager.invokeÙm[["bc194157-c925-4a16-89c7-6be69dd9ce87","extend","{\u0022lat\u0022:51.1351313,\u0022lng\u0022:-0.1580743}"]]

These alternate, so it looks like the first is the marker data, and the second is the JS call to make it visible. With 200 markers, I get 400 XHR calls, which amounts to about 400Kb and a very slow response.

Again, is there a way to speed this up? Apart from the fact that the `MarkerList` sample doesn't cluster (which is important given how many markers I will have), it sets the visibility of each one individually, which is very slow. Isn't there a way to do one call to set the visibility of all of them in one go?

I haven't posted code as I copied the wiki code exactly, just substituting my data access code to build by location list instead of your `Stops` collection.

Thanks

**Comment by valentasm1** [comment]
Sorry i am not js guy. I dont have any suggestions. 
I suggest you could look at javascript google solution and then we could move it here.

**Comment by MrYossu** [comment]
@valentasm1 I'm also not a JS guy, that's one reason I use Blazor!

Doesn't your package handle anything like this? As it stands, the code you show is only usable for a fairly low number of markers. As soon as you get anything like a realistic number, it grinds along very slowly.

Thanks

**Comment by valentasm1** [comment]
You could subscribe to map move event (or how it is called) and only if conditions are met draw markers.

**Comment by valentasm1** [comment]
I heard that .net 6 will speed up communications for blazor > js, but not sure if it is applicable here. If i remember correctly it is mostly for file download. Maybe you could find that guy who made MultiList PR since he had same issue and ask him personally.

**Comment by valentasm1** [comment]
https://github.com/RobertoMilani

**Comment by valentasm1** [comment]
https://github.com/rungwiroon/BlazorGoogleMaps/pull/52

**Comment by MrYossu** [comment]
@valentasm1 Thanks for the link. Didn't realise you didn't write the `MarkerList` code. I've asked in that PR issue, so will see if he responds.

**Comment by valentasm1** [comment]
I would say i wrote 0.1% of code here.  MarkerList doesnt do anything fancy. If you have problems with 200 markers I think issue is somewhere else

**Comment by MrYossu** [comment]
@valentasm1 Like what? I'm using code that is copied from your sample and/or the wiki.

**Comment by valentasm1** [comment]
I dont understand where you get 400kb request. I just created demo with adding 200 markers and it is far from that. I am doing smth wrong.
Could you give screenshots?

**Comment by MrYossu** [comment]
@valentasm1 Interesting. I tried it on another PC and there were hardly any network calls, very little bandwidth and a much better speed.

I think it's the Internet filter on this machine. Not sure why it would do that, but it looks like that's causing the extra calls.

Thanks anyway.

**Comment by valentasm1** [comment]
Uf. Great is works. Could we close issue?

**Comment by MrYossu** [comment]
Guess so. Thanks again.
