### ISSUE TITLE
Markers Hide and show

### ISSUE THREAD

**Issue by komirineni** [rungwiroon/BlazorGoogleMaps#16]
Hi Team,

do we have the functionality to hide the marker and show back based on map pin click/dblcick events?

**Comment by cyberyaga** [comment]
So if I'm getting your question straight... You want to be able to add a marker onclick of the map... and remove the marker when you click on said marker?

Let me know...

**Comment by komirineni** [comment]
Let me ask this way , I have already added markers on the map. I want to hide/show the markers on the map.

**Comment by cyberyaga** [comment]
That's easy to do... So, taking the example from [https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarker.razor](url)

You can create iterate through the collection of markers on the map, and if you want to hide just do
SetMap(null) or if you want to show, you can do SetMap(map1.InteropObject)

Like this:
`
	private void HideAllMarkers()
	{
		foreach (var m in markers)
		{
			m.SetMap(null);			
		}
	}

	private void ShowAllMarkers()
	{
		foreach (var m in markers)
		{
			m.SetMap(map1.InteropObject);			
		}
	}

`
