### ISSUE TITLE
Feature. Check for supporting .net6 and .netstandart2.1 at  same time

### ISSUE THREAD

**Issue by valentasm1** [rungwiroon/BlazorGoogleMaps#161]
Check if or any changes is necessary to support both nuget packages for .net6 and .netstandart 2.1. For sure it will be need to customize nuget package build options.
Ticket for discussion and comments

**Comment by valentasm1** [comment]
Any volunteer is appreciated :D. Personally i could check that in november.

**Comment by rungwiroon** [comment]
My idea is to migrate the code to use new C# language features.
Right now our code is C# 8, if we want to do multi framework target we have to stick to C# 8
and not get any benefits from new language features.
For official nuget package should stick to .net standard 2.1 until .net core 3.1 end of support.
After that we can migrate to .net 6 completely.

**Comment by rungwiroon** [comment]
This is my new plan

v1.xx 
- [ ] Upgrade to .net standard 2.1
- [ ] Implement IAsyncDisposable instead of IDisposable
- [ ] Change Task to ValueTask
- [ ] Unit tests

v2.xx
- [ ] Use new .NET 6 API
- [ ] Migrate to use IJSObjectReference
- [ ] Use System.Text.Json

**Comment by valentasm1** [comment]
Upgrade to 2.1 is easy peasy. Will do when i finish with current PR.
IAsyncDisposable  exists in .netst2.1 so not issue.
In my understanding ValueTask benefits when sometimes return is returned instantly without awaiting. Which isnt the case since we do js interop. I never understand ValueTask clearly. So i could be wrong.
I agree for unit testing, but there is not much to test since most of the stuff is just like proxy. But ea, any tests would help

Regarding .net6 i still curious if or any edge cases where people wont be able to use lib because of that. Maybe some mobile blazor or smth similar library wont work. Of course always could revert  back :).

Great that you have time and will to add more features.

**Comment by rungwiroon** [comment]
The JsInterop invoke method already return ValueTask this will reduce GC pressure especially on Blazor WASM
Caution is when use it we must await or return it immediately.

**Comment by rungwiroon** [comment]
I'm already working with 
- Use new .NET 6 API
- Migrate to use IJSObjectReference
- Use System.Text.Json
Just finished migrated Map and Marker.
Still needs a ton of work with other types.
you take a look at it in dotnet-6 branch.

**Comment by valentasm1** [comment]
Quick not. Use System.Text.Json implemented.

**Comment by valentasm1** [comment]
After .net 8 release i am planning to migrate all solution from .net2.1 to .net 8. ~ Dec

**Comment by valentasm1** [comment]
Migration to .net 8 done. Supporting .net standart and 8 wont happen :). I am too lazy and everybody i asked here had no complain with only 8net.
