### ISSUE TITLE
Add GetProjection to map object

### ISSUE THREAD

**Issue by joe-shapiro-biz** [rungwiroon/BlazorGoogleMaps#163]
Thanks again for a great package.

I need a method to convert a latlng to a pixel x y on the map.

It would be great if the map interface had such a method, and/or you could expose getProjection and the projection object.

Thanks again.

**Comment by valentasm1** [comment]
Could you give some examples or use case?
I dont understand what you mean by expose?

**Comment by joe-shapiro-biz** [comment]
When I listen for click events on the map itself, all is good, I get pixel xy in the event args.

When I listen for click events on a object like a marker, there is a pixel xy but it is invalid. The latlng is valid. I want to translate the latlng into pixel xy so I can place an html element in the right place on top of the map.

The js Map object has a method getProjection but the Map object in your package does not. GetProjection returns a projection object with which you can convert latlng into pixel xy.

See https://developers.google.com/maps/documentation/javascript/reference/map#:~:text=MapTypeId%7Cstring%20optional-,getProjection,-getProjection()

**Comment by valentasm1** [comment]
I get projection part. Still not sure what you expect from me about pixel xy. Maybe when i implement projection it will be enough?

**Comment by joe-shapiro-biz** [comment]
I think so, and I will let you know as soon as I can.
Just make sure projection.fromLatLngToPoint(latlng x) is included.

**Comment by valentasm1** [comment]
I will implement in one month period.

**Comment by joe-shapiro-biz** [comment]
Many thanks.
________________________________

**Comment by valentasm1** [comment]
Mostly faster. It is worst case scenario :).

**Comment by joe-shapiro-biz** [comment]
That would be great. Thanks again.
________________________________

**Comment by thepigeonfighter** [comment]
+1 on this, and thank you for taking this on. This package has been a lifesaver <3

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.4.0

**Comment by thepigeonfighter** [comment]
Updated packages and am now getting this error: 

[2021-12-07T20:06:15.842Z] Error: Microsoft.JSInterop.JSException: Could not find 'googleMapsObjectManager.createObject' ('googleMapsObjectManager' was undefined).
findFunction/<@https://localhost:5001/_framework/blazor.server.js:1:497
findFunction@https://localhost:5001/_framework/blazor.server.js:1:465
E@https://localhost:5001/_framework/blazor.server.js:1:2606
beginInvokeJSFromDotNet/s<@https://localhost:5001/_framework/blazor.server.js:1:3494
beginInvokeJSFromDotNet@https://localhost:5001/_framework/blazor.server.js:1:3475
_invokeClientMethod/<@https://localhost:5001/_framework/blazor.server.js:1:71773
_invokeClientMethod@https://localhost:5001/_framework/blazor.server.js:1:71759
_processIncomingData@https://localhost:5001/_framework/blazor.server.js:1:69801
Tt/this.connection.onreceive@https://localhost:5001/_framework/blazor.server.js:1:64201
connect/</o.onmessage@https://localhost:5001/_framework/blazor.server.js:1:48517


   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)

   at GoogleMapsComponents.Helper.MyInvokeAsync[TRes](IJSRuntime jsRuntime, String identifier, Object[] args)

   at GoogleMapsComponents.JsObjectRef.CreateAsync(IJSRuntime jsRuntime, Guid guid, String functionName, Object[] args)

   at GoogleMapsComponents.Maps.Map.CreateAsync(IJSRuntime jsRuntime, ElementReference mapDiv, MapOptions opts)

   at GoogleMapsComponents.MapComponent.InitAsync(ElementReference element, MapOptions options)

   at GoogleMapsComponents.GoogleMap.OnAfterRenderAsync(Boolean firstRender)

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by valentasm1** [comment]
Could you give minimum sample?

**Comment by thepigeonfighter** [comment]
I found the issue, 
`<script src="_content/BlazorGoogleMaps/objectManager.js"></script>`
 needed changed to 
`<script src="_content/BlazorGoogleMaps/js/objectManager.js"></script>`

Guess the main doc needs updated. I jumped from 1,2 so that must have been something that was changed in 1.3

**Comment by valentasm1** [comment]
Updated readme.

**Comment by thepigeonfighter** [comment]
Thanks for the quick help, it looks like everything I've used so far is working! Not sure if you want to add this in an example script or something? But I am sure that other people might find it useful. Here is how to convert local to and from local points. 
~~~C#
        private async Task<Point> LatLng2RelativePoint(Projection projection, LatLngLiteral latLng)
        {
            var bounds = await map1.InteropObject.GetBounds();
            var zoom = await map1.InteropObject.GetZoom();
            var topRight = await projection.FromLatLngToPoint(new LatLngLiteral(bounds.East, bounds.North));
            var bottomLeft = await projection.FromLatLngToPoint(new LatLngLiteral(bounds.West, bounds.South));
            var scale = Math.Pow(2, zoom);
            var worldPoint = await projection.FromLatLngToPoint(latLng);
            var point = new Point { X = (worldPoint.X - bottomLeft.X) * scale, Y = (worldPoint.Y - topRight.Y) * scale };
            return point;
        }

        private async Task<LatLngLiteral> RelativePoint2LatLng(Projection projection, Point point)
        {
            var bounds = await map1.InteropObject.GetBounds();
            var zoom = await map1.InteropObject.GetZoom();
            var topRight = await projection.FromLatLngToPoint(new LatLngLiteral(bounds.East, bounds.North));
            var bottomLeft = await projection.FromLatLngToPoint(new LatLngLiteral(bounds.West, bounds.South));
            var scale = Math.Pow(2, zoom);
            var worldPoint = new Point { X = point.X / scale + bottomLeft.X, Y = point.Y / scale + topRight.Y };
            var latLng = await projection.FromPointToLatLng(worldPoint);
            return latLng;
        }
~~~

**Comment by joe-shapiro-biz** [comment]
One thing to watch out for:  If you zoom the map with the scroll wheel, the zoom value will not be an integer, and map1.InteropObject.GetZoom()will crash.

**Comment by thepigeonfighter** [comment]
Hey thanks for the heads up! 
Are there certain scenarios where this occurs? I have only been using the scroll wheel for setting zoom and I have not experienced a crash yet?

**Comment by valentasm1** [comment]
Added sample for conversion
And Changed GetZoom arg from int to double
https://www.nuget.org/packages/BlazorGoogleMaps/1.4.1

**Comment by valentasm1** [comment]
Could i close issue?

**Comment by thepigeonfighter** [comment]
Solved as far as I go. 
Thanks!

**Comment by joe-shapiro-biz** [comment]
Thanks!
________________________________
