### ISSUE TITLE
Get Reference to Google Map  Instance in JS

### ISSUE THREAD

**Issue by thepigeonfighter** [rungwiroon/BlazorGoogleMaps#165]
I may be missing something, but is there a way to get a javascript reference to a google map you are using? By guid or something like that? 
I would either like to be able to pass this reference to a javascript function via interop like  
`JS.InvokeAsync<Point>("customFunc", map1.JsReference);`
or  be able to get a reference to the rendered map it via javascript like 
`let map = GetMap(guid)`

It seems like there has to be something already built in to do this, but I seem to be missing it. 

Thanks

**Comment by valentasm1** [comment]
All map objects is stored in array (i assume) _blazorGoogleMapsObjects in javascript.
All objects (c#) have Guid readonly property. So you could access any object _blazorGoogleMapsObjects[guid]. Just pass guid to any js function via invoke and then you could access objects.
```
addImageLayer(args) {
        let map = _blazorGoogleMapsObjects[args[0]];
        let elem = _blazorGoogleMapsObjects[args[1]];

        map.overlayMapTypes.push(elem);
    },
```

**Comment by thepigeonfighter** [comment]
Thanks!
