### ISSUE TITLE
How to show a Trail/track, like a jogger or biker

### ISSUE THREAD

**Issue by weedkiller** [rungwiroon/BlazorGoogleMaps#167]
Hello can you share some information on how to show a trail of dots or a line that someone has been jogging/biking on

**Comment by valentasm1** [comment]
Play with
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapPolyline.razor
Especially this part
```
 private void AddArrowsToPolyline()
    {
        foreach (var polyline in polylines)
        {
            polyline.SetOptions(new PolylineOptions
            {
                Icons = new IconSequence[] {
                    new IconSequence { Icon=new Symbol { Path=SymbolPath.FORWARD_CLOSED_ARROW }, Offset="100%" },
                    new IconSequence { Icon=new Symbol { Path=SymbolPath.FORWARD_OPEN_ARROW }, Offset="80%" },
                    new IconSequence { Icon=new Symbol { Path=SymbolPath.FORWARD_OPEN_ARROW }, Offset="60%" },
                    new IconSequence { Icon=new Symbol { Path=SymbolPath.FORWARD_OPEN_ARROW }, Offset="40%" },
                    new IconSequence { Icon=new Symbol { Path=SymbolPath.FORWARD_OPEN_ARROW }, Offset="20%" },
                }
            });
        }
    }
```

**Comment by valentasm1** [comment]
![image](https://user-images.githubusercontent.com/8047891/146726660-4cfd1153-61c2-4e16-9b52-21f11f80a1a6.png)

**Comment by valentasm1** [comment]
Related to https://github.com/rungwiroon/BlazorGoogleMaps/issues/105

**Comment by weedkiller** [comment]
ohh wow thanks!!

how do a `heat trail`, where the latest foot print is hot RED dots, and the 15 mins ago, to fading green
Imagine path of hurricane or jogger etc,

Also `do I need to redraw `every dot every time? `is it possible to draw just new ones` and let the old ones fade for rendering efficiency.


![image](https://user-images.githubusercontent.com/21086190/146866786-7f752ca0-990b-4282-993b-be2431895abd.png)

**Comment by valentasm1** [comment]
I doubt it is heat trail. I think it is just circles with computed fill color.
I dont understand what do you mean be redraw. You either draw on map or remove from map. You could do based on zoom level.
Sorry but i couldnt suggest exact solution. You better look on internet for javascript solution and then apply here.
