### ISSUE TITLE
Delete vertices of polyline/polygon

### ISSUE THREAD

**Issue by Mr-Technician** [rungwiroon/BlazorGoogleMaps#171]
I was looking at the Google Maps documentation and ran across this: https://developers.google.com/maps/documentation/javascript/examples/delete-vertex-menu

Is something like this possible with BlazorGoogleMaps? I am able to add polygons and polylines but it would be nice to be able to modify their points afterward.

**Comment by valentasm1** [comment]
As you see it is very custom solution. Putting this into library would be right way.
Personally i use custom solution to delete lines with right click on circle. Easy to implement.

Here is just rought idea. Wont go into details
```
 await _polyline.AddListener<PolyMouseEvent>("rightclick", async (x) =>
                {
                    var allPath = await _polyline.GetPath();
                    var allPathList = allPath.ToList();
                    var removedCount = allPathList.RemoveAll(y => Math.Abs(y.Lng - x.LatLng.Lng) < 0.0001 && Math.Abs(y.Lat - x.LatLng.Lat) < 0.0001);

                    await _polyline.SetPath(null);
                    await _polyline.SetPath(allPathList);
                });
```
