### ISSUE TITLE
Maui Blazor

### ISSUE THREAD

**Issue by curelom** [rungwiroon/BlazorGoogleMaps#172]
With MAUI coming up, it allows blazor within the mobile app.  Would be nice to be able to use blazor google maps in Maui, but it shows as unavailable for iOS and Mac.  I suspect it's a compiling issue and that there isn't a compiled version for those frameworks.

**Comment by valentasm1** [comment]
Library is .netstandart 2.1 so it should be already compatible.
Could you give more details and error msg?

**Comment by curelom** [comment]
Error	CS0246	The type or namespace name 'GoogleMapsComponents' could not be found (are you missing a using directive or an assembly reference?)	AppName (net6.0-ios), AppName (net6.0-maccatalyst)

**Comment by valentasm1** [comment]
Could you give steps to reproduce or solution.
I think you are targeting beta version of MAUI, so this could be fixed in future releases.

**Comment by curelom** [comment]
Create a new Maui Blazor Project from the latest template and VS2022.  Nuget the GoogleMapsComponents package into the app.  The next step may not be necessary, but add GoogleMapsComponent to a blazor page such as Shared\Index.razor.
Will show up in the Errors list and if you open Dependencies\net6.0-ios\Packages or Dependencies\net6.0-maccatalyst.  You will see the package with a warning icon.  Shows correctly on the android and windows versions

**Comment by valentasm1** [comment]
Sorry wont investiage more. MAUI is still in beta and need another visual studio.
Could be related to this.
https://developercommunity.visualstudio.com/t/Bug-in-Visual-studio-2022--Xamarin--Si/1528510

**Comment by curelom** [comment]
Ok, thanks for the quick response anyway.

**Comment by valentasm1** [comment]
Like i said it is moslty related to other things not directly library.
