### ISSUE TITLE
LatLngLiteral constructor's parameters are in the wrong order

### ISSUE THREAD

**Issue by SocVi100** [rungwiroon/BlazorGoogleMaps#173]
The constructor of the LatLngLiteral requires the Longitude passed as the first parameter and the Latitude as the second one, which is just the opposite of it's name suggests and what's stated in the google maps examples.
So, please, swap them! That's completely unintuitive and has no sense anyway. I've had a hard time guessing the problem on my tests and the problem was that markers where appearing just in the opposite hemisphere...

Thanks in advance

**Comment by valentasm1** [comment]
If you help fix demos i alway in.

**Comment by valentasm1** [comment]
I know it is wrong order but it could be huge breaking change for many dependand projects.
I market as obsolete. So it will generate error. Maybe one da when i will be brave i will change

**Comment by DarknSolid** [comment]
Thanks to the obsolete marking I realized this early and went the safe way of writing:
var x = new LatLongLiteral(){
   Latitude = myObj.Lat
   Longitude = myObj.Lon
}

**Comment by valentasm1** [comment]
Your day has come :D
