### ISSUE TITLE
Bug. Remove event listener dont work

### ISSUE THREAD

**Issue by vinco83** [rungwiroon/BlazorGoogleMaps#176]
I'm wondering if it's possible to remove an event listener once one has been added

I added an event listener like so:

await _map.InteropObject.AddListener<MouseEvent>("click", async (e) => await MapClicked(e));

So that I can get the Lat/Lon when the map is clicked, but I need to be able to remove the listener so that clicking on the map will no longer do anything. 

I tried calling the Dispose() method on the returned MapEventListener, but that didn't seem to work.

Is this simpler than I'm making it, or should this functionality be added to the library?

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.5.4
Demo
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMapControlEvents.razor
