### ISSUE TITLE
Geocoding ?

### ISSUE THREAD

**Issue by GillesFr06** [rungwiroon/BlazorGoogleMaps#178]
Hi,

Great job for google Maps :)

Is the Geocoding API working ? (Translate address into Lat/Lng)
If yes, how ?
If no, is it planned ? When ?

Best,
Gilles

**Comment by valentasm1** [comment]
Could you give some examples?

**Comment by GillesFr06** [comment]
https://developers.google.com/maps/documentation/javascript/geocoding

**Comment by GillesFr06** [comment]
Thanks for your answer, and the link.
I asked because I saw Geocoder.cs, GeocoderAddressComponent.cs... in the sources.
Sorry for noise, and thank you again.
Gilles
