### ISSUE TITLE
Slow respons time After populating map with multiply markers

### ISSUE THREAD

**Issue by MrDanLeaf** [rungwiroon/BlazorGoogleMaps#189]
Hello i have a question regarding Many markers (2000) on map. I have been in contact with Rungwiroon and he suggestied to contact you others. Great work you all doing!, My problem is when populating map with many markers, 2000 the map respons is very slow on zooming and panning, this is the big ISSUE. it also takes a while to populate map. But that is not a huge problem for now. I have tried other Nugets and they works better when zooming and panning. But your stuff is better for my project!. Does anyone of you tried to populate map with many markers?. Markers is made from a list of objects with longitude, latitude and name. Here is a code snippet.

foreach(var item in entityDtos)
            {
                LatLngLiteral latLngLiteral = new LatLngLiteral()
                {
                    Lat = item.Latitude, 
                    Lng = item.Longitude,
                };
                 var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
                {
                    Position = latLngLiteral,
                    Map = map1.InteropObject,
                    Label = item.Name,
                });
                markers.Push(marker);
              }

markers is a Stack<Marker> markers

I am using preview of visual studio 2022 and .NET Maui.

Some tip or ideas?. 
/Best regards Daniel.

**Comment by valentasm1** [comment]
Have you tried to use 
https://github.com/rungwiroon/BlazorGoogleMaps/wiki/MarkerList-for-multi-markets-manipulation

**Comment by valentasm1** [comment]
And this example
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarkerListPage.razor.cs

**Comment by valentasm1** [comment]
To speed up map actions you could try to group icons with clusters. Demo here
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarker.razor

**Comment by valentasm1** [comment]
Closing due inactivity
