### ISSUE TITLE
spiderfier effect to our map

### ISSUE THREAD

**Issue by komirineni** [rungwiroon/BlazorGoogleMaps#19]
I want spiderfier effect to our blazor google maps. is there any solution to achieve this.
https://github.com/jawj/OverlappingMarkerSpiderfier

**Comment by valentasm1** [comment]
Sorry but i dont see reason to spend time for this. It could be very time consuming to add this feature. It is very fragile functionality and not necessary for most user cases. 
Technically it could work as you could get map object from jsInterop accessing it by guid. Then then use provided library. But like i said it could have many issues to finish.
I think someone with basic knowledge of blazor could do it in 1-2 working days. If you want i could help somehow for some reward.

**Comment by valentasm1** [comment]
Closing due inactivity.
