### ISSUE TITLE
Memory leak deleting maps

### ISSUE THREAD

**Issue by kevinarthurackerman** [rungwiroon/BlazorGoogleMaps#191]
There is an open issue with Google Maps API for years that removing a map completely is not supported, and it keeps the map object in memory even after removing the element it is attached to. Their recommended approach has been to pool and reuse map objects. It warrants more testing, but looking through the source code it looks like maps are disassociated from the manager when disposed, but are not pooled for reuse.

**Comment by valentasm1** [comment]
Honesly not gonna do due limited time and complicated solutions. PR is welcome.

**Comment by kevinarthurackerman** [comment]
I started implementing a solution for this that basically tracks components that reference a map and then when a map is disposed it actually returns it to a pool and then calls dispose on all the related assets. Then when a new map is created it will check the pool first for an existing one and reuse it if there is one.

The problem I ran into is first that there are a ton of components that reference a map (big surprise), but then secondly that apparently the map registers other events and such that would also need to be cleaned up. While it seems like a fix is technically viable, it seems like it would take an incredible amount of effort to fix what is at it's root Google's bug.

For now I'm thinking about going with a solution where I cache the map and component object for a page in static variables, and then do some hackery to to move the map HTML element out of the page into a hidden div before unloading the page and then moving it back in. That, or just dispose all the components and suffer the memory leak on the map itself.

I created a branch if your interested in seeing the beginning of a partial solution, but I don't have permissions. Let me know if I should push it.

**Comment by valentasm1** [comment]
I couldnt give permission since i am not owner but you could fork it to your repositories and show.
Would be great to see.

**Comment by kevinarthurackerman** [comment]
In these changes I only currently handle cleaning up markers and the map itself, but you can see how it would be applied to all the other components. I also haven't tested the code yet, so this is more a demonstration of how it could work in theory. The important aspects are that it tracks components related to a map and pools maps, cleans up the components when a map is removed and pools the map for reuse.

https://github.com/rungwiroon/BlazorGoogleMaps/compare/master...kevinarthurackerman:feature/pool-maps?expand=1

**Comment by valentasm1** [comment]
Do you have any official google issue number?

**Comment by valentasm1** [comment]
Closing due inactivity
