### ISSUE TITLE
Add PolygonList as feature

### ISSUE THREAD

**Issue by eptgrant** [rungwiroon/BlazorGoogleMaps#193]
Hello,

Is there a reason as to why there isn't a "PolygonList" class implemented?

I might have a go at implementing it if there isn't.

Cheers

**Comment by valentasm1** [comment]
Laziness :). Let me know if you need some info or examples.
If you could give google implementation i could maybe find smth good start in our solution

**Comment by valentasm1** [comment]
Closing due inactivity
