### ISSUE TITLE
google map init

### ISSUE THREAD

**Issue by michalkubis** [rungwiroon/BlazorGoogleMaps#20]
I think that googleapis script needs to be in `<head>`, otherwise google maps may not be ready yet. It fails to load the maps when I try /maps directly in incognito window.

Ideally, we would need something like this:
`<script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">`

**Comment by valentasm1** [comment]
Will do tomorrow. 
Thank you for use case and recommendation.

**Comment by valentasm1** [comment]
I thought you are talking about library. But it looks like you meant Demo projects.
I update script location in both demos and in readme file.

It is ok or you mean other things?

**Comment by michalkubis** [comment]
Sorry, I wasn't clear. I meant ServerSideDemo. 

Simple `<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY">` in `<head>` would work fine.

To implement the one with async defer and callback I suggested before would require more changes, but it may speed up loading.

**Comment by valentasm1** [comment]
I added defer and async and comited.
It is just demos and every solution is different. Despite that thank you for suggestions

**Comment by michalkubis** [comment]
In that case, please remove defer and async, otherwise it may fail again on /maps. 
I tested on my side and it failed because Google script was not loaded yet.

Without async defer, it will load the script in head first, so you can call google maps without problem.

If you wanted to keep async defer, you would have to implement that callback.

Sorry for confusion...

**Comment by valentasm1** [comment]
No worries. I appreciate feedback
I didnt have any issues, but probably because of super fast network. Reverted to without async and defer.
