### ISSUE TITLE
Major problem after upgrading to the latest version

### ISSUE THREAD

**Issue by MrYossu** [rungwiroon/BlazorGoogleMaps#201]
I just upgraded a project from BlazorGoogleMaps 1.0.16 to 2.2.1. I needed a couple of adjustments to get it to work, but it mostly seems to be working now.

However, there is one major issue. I don't know if the background map is in the wrong place, or the markers are incorrectly placed, but instead of them appearing around the UK as they should...

![Correct](https://user-images.githubusercontent.com/10185332/178779287-4cefb0d1-9ebc-4daa-9441-faa19e6b5d4f.png)

...they appear somewhere north-west of the Seychelles...

![Incorrect](https://user-images.githubusercontent.com/10185332/178779373-1ab6f78c-05bc-4975-b64f-1fc0c8d66e97.png)

Not only that, if you look at the markers, they aren't even spread out the same. The first shot was taken from the live site, and the second was taken from my local upgrade, but pointing at the same database, so the information should be the same. However, a quick count seems to show that the live site displays 268 markers, but the upgraded local one only shows 161.

My `_Host.cshtml` file contains the following...

```html
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=@GoogleMapsHelper.ApiKey&v=3"></script>
<script src="https://unpkg.com/@@googlemaps/markerclusterer/dist/index.min.js"></script>
<script src="_content/BlazorGoogleMaps/js/objectManager.js"></script>
```

I tried changing the middle link to `https://unpkg.com/@@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js` as shown on the [marker clustering page](https://github.com/rungwiroon/BlazorGoogleMaps/wiki/Marker-Clustering), but that gave an exception "_Microsoft.JSInterop.JSException: markerClusterer is not defined_"

The code in my `.razor` file looks like this...

```html
<GoogleMap @ref="@_map"
           Id="map1"
           Options="@_mapOptions"
           OnAfterInit="AfterMapInitAsync"
           Height="100%" />
```

The code behind looks like this (irrelevant bits missed out for clarity)...

```c#
private GoogleMap _map;
private MapOptions _mapOptions;

protected override async Task OnInitializedAsync() {
  _mapOptions = new MapOptions {
    MapTypeId = MapTypeId.Roadmap,
    Styles = BuildStyles()
  };
}

private MapTypeStyle[] BuildStyles() {
  GoogleMapStyleBuilder styleBuilder = new();
  styleBuilder.AddStyle(@"[{ ""featureType"": ""poi"", ""stylers"": [ { ""visibility"": ""off"" } ] }]");
  return styleBuilder.Build();
}

private async Task AfterMapInitAsync() =>
  await _map.InteropObject.AddListener<MouseEvent>("click", _ => {
    SelectedSurveyor = null;
    ActiveTabIndex = 0; // Used in a tab strip to show details
  });

// This method is called when the user clicks a search button.
// The OnClick method builds a list of the surveyors to show and passes it in here...
private async Task ShowMarkers(List<Surveyor> surveyors) {
  _searching = true;
  await ClearMarkers();
  foreach (Surveyor s in surveyors) {
    Marker marker = await Marker.CreateAsync(_map.JsRuntime, new MarkerOptions {
      Position = new LatLngLiteral(s.Longitude, s.Latitude),
      Map = _map.InteropObject,
      Label = new MarkerLabel {
        ClassName = "marker-label",
        Text = s.Company
      },
      Title = s.Company,
      Icon = "http://maps.google.com/mapfiles/ms/micons/blue-dot.png",
      Visible = false
    });
    await marker.AddListener<MouseEvent>("click", async e => {
      SelectedSurveyor = surveyors.Single(su => su.Id == _guids.Single(g => g.Guid == marker.Guid).Id);
      ActiveTabIndex = 1;
      await e.Stop();
    });
    _guids.Add((s.Id, marker.Guid));
    _markers.Add(marker);
  }
  _markerClustering = await MarkerClustering.CreateAsync(_map.JsRuntime, _map.InteropObject, _markers);
  if (surveyors.Count == 0) {
    await _map.InteropObject.SetZoom(6);
    await _map.InteropObject.SetCenter(new LatLngLiteral(-4, 54.5));
    _inform.Display("No surveyors found, please modify your search");
  } else if (surveyors.Count == 1) {
    await _markerClustering.FitMapToMarkers(1);
    await _map.InteropObject.SetZoom(11);
  } else {
    await _markerClustering.FitMapToMarkers(1);
  }
  foreach (Marker marker in _markers) {
    await marker.SetVisible(true);
  }
  _searching = false;
}
```

None of the code behind has changed since before the upgrade.

Any idea what's gone wrong? Thanks

**Comment by valentasm1** [comment]
Rest will check later this week

**Comment by MrYossu** [comment]
Thanks for the fast reply.

That solved a lot of the problem, in that the markers are now all in the UK, and look to be in the right positions. I'm still seeing a different number of markers, but I suspect that's nothing to do with your component. I need to check this more and will let you know.

Thanks again

**Comment by MrYossu** [comment]
Ah, I changed the connection string, but forgot to restart the local site! Was still using the local database, not the live one.

As far as I can see, all is working fine now.

Thanks again for the help.

**Comment by valentasm1** [comment]
also there was PR for marker clustering updates. I think these one
https://github.com/rungwiroon/BlazorGoogleMaps/pull/192
https://github.com/rungwiroon/BlazorGoogleMaps/pull/184
