### ISSUE TITLE
[Bug] MarkerClustering Redraw() do not work

### ISSUE THREAD

**Issue by markschroeder77** [rungwiroon/BlazorGoogleMaps#204]
Can anyone confirm if the markerClustering.Redraw method works.

I'm trying to hide  a marker and refresh the clustering.

Calling

await marker.SetVisible(value);
await markerClustering.Redraw();

Doesn't work, but calling

await marker.SetVisible(value);
await markerClustering.ClearMarkers();
await markerClustering.AddMarkers(markers);

does work.

**Comment by valentasm1** [comment]
I couldnt find that option in documentations
https://googlemaps.github.io/js-markerclusterer/
@TheAtomicOption maybe you know more about redraw?

**Comment by markschroeder77** [comment]
Yeah, it looks like that redraw method was available a long time ago, but it's gone now. [https://groups.google.com/g/google-maps-js-api-v3/c/kspTUjVcFsY](url) 

Rather than calling ClearMarkers() and adding all the markers back with AddMarkers(), I'm rather just going to remove the updated markers with RemoveMarkers() and then add only the update ones back in with AddMarkers().

There was a problem with the RemoveMarkers() method though.
The fix is here [https://github.com/markschroeder77/BlazorGoogleMaps](url)

**Comment by valentasm1** [comment]
I will try review your changes and and merge

**Comment by TheAtomicOption** [comment]
Your links aren't working for me but...

I know this was working 6months ago when I was last doing a lot of work on this project. Looks like the current method to redraw is now `render()` on the js side. (https://googlemaps.github.io/js-markerclusterer/interfaces/Renderer.html#render) and it gets called automatically if you pass `false` to the `NoDraw` parameter for Add/RemoveMarker(s) functions (https://github.com/googlemaps/js-markerclusterer/blob/main/src/markerclusterer.ts#L115). 

so presumably the text string here https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/Maps/MarkerClustering.cs#L143
should be updated to "render"

**Comment by valentasm1** [comment]
I updated redraw to render
https://www.nuget.org/packages/BlazorGoogleMaps/2.2.4
