### ISSUE TITLE
Custom overlays

### ISSUE THREAD

**Issue by samberk1** [rungwiroon/BlazorGoogleMaps#208]
Hi

Can we add overlays with our custom html using this blazor library? 
Like this: https://developers.google.com/maps/documentation/javascript/examples/overlay-popup?hl=en

Thanks

**Comment by valentasm1** [comment]
You could use ground overlay, but it think it would be better use marker with custom info window.
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapGroundOverlayPage.razor

Info about bootstrap into info window and how to show always info window
https://github.com/rungwiroon/BlazorGoogleMaps/issues/83
https://github.com/rungwiroon/BlazorGoogleMaps/issues/62

**Comment by samberk1** [comment]
Thank you will try it out.
