### ISSUE TITLE
WASM: Microsoft.JSInterop.JSException: Could not find 'googleMapsObjectManager' in 'window'

### ISSUE THREAD

**Issue by brmdbr** [rungwiroon/BlazorGoogleMaps#21]
I'm using client side blazor and implemented accoring to the examples in this project. I get the following error when it tries to laod the map: blazor.webassembly.js:1 WASM: Microsoft.JSInterop.JSException: Could not find 'googleMapsObjectManager' in 'window'

is this a knows issue? what is the way to work around it?

Thanks.

**Comment by valentasm1** [comment]
Could you post all call stack?

**Comment by valentasm1** [comment]
I have feeling that you didnt set your key in your solution. But while i wont see stack i could prove it.
If you need help colecting debug info let me know. Maybe i could help.

**Comment by brmdbr** [comment]
Hello, sorry for my late response. I can't provide you with a stacktrace right now but I got the error when creating a blank blazor wasm app from vs. I followed the instructions in the repo.

**Comment by valentasm1** [comment]
Could you post your page? I need somehow reproduce error

**Comment by brmdbr** [comment]
I managed to fix it. The following line was missing in the index.html. 

`<script src="_content/BlazorGoogleMaps/objectManager.js"></script>`

From reading the readme I assumed that was only needed on server side Blazor projects but apparently it isn't.

**Comment by valentasm1** [comment]
Thank you for noticing it. Our demos run since we link project file not nuget package.
I updated client side demo and readme file
Again thank you for taking you time to investigate
