### ISSUE TITLE
Map problem in MapRoutes.razor 

### ISSUE THREAD

**Issue by Pedrinhown** [rungwiroon/BlazorGoogleMaps#210]
On the MapRoutes.razor file, the GoogleMap component don't work due to ownership "Height", it doesn't show any error, but it also doesn't show the map

**Comment by valentasm1** [comment]
I shows for me. What i am doing wrong?
![image](https://user-images.githubusercontent.com/8047891/188962215-507227cf-586d-41ca-9de1-df8fbf380f40.png)

**Comment by Pedrinhown** [comment]
If I left the "height" property on the component, the map didn't show up for me. I just cloned the repository and didn't change anything in the source code, just added my google maps api key
Here on MapRoutes.razor,  <GoogleMap @ref="@map1" Id="map1" Options="@mapOptions" Height="350" OnAfterInit="@(async () => await OnAfterInitAsync())"></GoogleMap>
If I remove "height" it works

**Comment by valentasm1** [comment]
Server side example 
```
Height="350px" 
```

Property comment
```
  /// <summary>
    /// Default height 500px
    /// Used as style atribute "height: {Height}"
    /// </summary>
```

I think you missed Height units.
