### ISSUE TITLE
How to add Polygon Click event?

### ISSUE THREAD

**Issue by metallicamu** [rungwiroon/BlazorGoogleMaps#211]
Hi There,
How can I add Click event to Polygon when finished drawing?
I tried to add this event same as Polyline but not worked:
`await polygon.AddListener("click", () =>
        {
            Console.WriteLine($"polygon clicked");
        });`
Cheers

**Comment by valentasm1** [comment]
Strange. I added same and it works. Do you have full example?
https://github.com/rungwiroon/BlazorGoogleMaps/commit/82e1e7bce4cc0bc63d2f22adcd313602fd1f9e6b

**Comment by metallicamu** [comment]
Hi valentasm,
Thanks for your reply.
It worked well now.
