### ISSUE TITLE
Exist DistanceMatrix service?

### ISSUE THREAD

**Issue by mirkotnn** [rungwiroon/BlazorGoogleMaps#212]
Exist DistanceMatrix service in this library?

**Comment by valentasm1** [comment]
Could you give more information or examples?

**Comment by mirkotnn** [comment]
example in Js:

var service = new google.maps.DistanceMatrixService();
var origins = [];
origins.push(new google.maps.LatLng(lat, lng));

function getDistance(place) {
	var destinationA = new google.maps.LatLng(place.geometry.location.lat(), place.geometry.location.lng());

	service.getDistanceMatrix({
		origins: origins,
		destinations: [destinationA],
		travelMode: 'DRIVING',
		unitSystem: google.maps.UnitSystem.METRIC,
	}, callback);
}

function callback(response, status) {
	if (status == 'OK') {
		...
	}
}

**Comment by valentasm1** [comment]
No it dont exists. Sorry.
As always PR is wellcome.
