### ISSUE TITLE
Remove Route returning error on browser console

### ISSUE THREAD

**Issue by Pedrinhown** [rungwiroon/BlazorGoogleMaps#214]
It happens in "Remove Route", on  /mapRoutes
InvalidValueError: setDirections: not an Object

![image](https://user-images.githubusercontent.com/51038351/192031679-c69577ef-6c0b-4caa-a0da-39f047638885.png)

**Comment by valentasm1** [comment]
Could you provide fulll example?

**Comment by Pedrinhown** [comment]
it is the same that is available in the repository in MapRoutes.razor, i tried some changes but none worked

**Comment by valentasm1** [comment]
Could you provide fulll example?
