### ISSUE TITLE
GeoJson support

### ISSUE THREAD

**Issue by bryanrcarlson** [rungwiroon/BlazorGoogleMaps#215]
Hello -- Excellent library! I'm interested in creating polygons with geojson input. It looks like there's planned support via [Maps.MapData.AddGeoJson](https://github.com/rungwiroon/BlazorGoogleMaps/blob/82e1e7bce4cc0bc63d2f22adcd313602fd1f9e6b/GoogleMapsComponents/Maps/Data.cs#L77). I'm wondering if implementation of this function is planned for the near future? 

I don't want to sound ungrateful by asking for more features. I am willing to contribute, provided I free up some time, but am not sure about API specifications, etc. I may need some guidance, but I suspect providing that may take longer than just implementing it directly 🤣 Maybe I can write some post-hoc tests as a thank you?

**Comment by valentasm1** [comment]
Hi. Maybe it is just copy paste from some auto scaffolded api. It is not planned in near future and mostly this lib is just in support status. Not actively developing.
You could try to provide as much as possible information for implementing and then we could see if i will do now or you could make PR

**Comment by bryanrcarlson** [comment]
Thanks, that's all good to know. If the comments were generated from scaffolding then maybe some of the specifications are not valid? E.g. no need to pass "parsed JSON"? 

I'll plan to look into how it could be implemented and either create a PR or report back (if it's beyond me).

Thanks!

**Comment by valentasm1** [comment]
I would say a lot of specifications not valid :).
At first i suggest provide more info and maybe i could try to do.

**Comment by bryanrcarlson** [comment]
That'd be great!

Specifically, I have a geojson string (a polygon, but I don't think that matters) that I would like to display on the map. The `google.maps.Data` class in the Javascript api has a `addGeoJson` function ([reference](https://developers.google.com/maps/documentation/javascript/reference/data#Data.addGeoJson)). You can see it in action in [this example](https://developers.google.com/maps/documentation/javascript/earthquakes#maps_earthquake_circles-typescript).

It looks like implementing it would be a matter of adding the following to your [stub](https://github.com/rungwiroon/BlazorGoogleMaps/blob/82e1e7bce4cc0bc63d2f22adcd313602fd1f9e6b/GoogleMapsComponents/Maps/Data.cs#L77):

```
return _jsObjectRef.InvokeAsynce<??>("addGeoJson");
```

I'm not sure how to handle the data being passed around though.

Thanks!

**Comment by valentasm1** [comment]
Hm.
Added sample, but not sure why it dont works. I have no idea when i will have more time to look into it. You could play around and maybe find out smth.
https://github.com/rungwiroon/BlazorGoogleMaps/commit/4174d70491d14a7f5ad98fd8d25807270bddc096
https://stackoverflow.com/questions/38491370/how-to-add-geojsonmultilinestring-layer-to-a-google-map

**Comment by bryanrcarlson** [comment]
Thanks @valentasm1 ! I'm hoping to find some time today to work on this.

**Comment by bryanrcarlson** [comment]
Looks like just a slight issue with the geojson string. I created a PR #218 .

I appreciate you!

**Comment by valentasm1** [comment]
I think it is possible to do in clean strongly typed manner, buuut like i said i dont have much time. Just left some working version of way to do with dictionary.
I saw that error appears in console but looks like it coming from .net side. 
Would be cool if you just drop changes which you will implement of find on the way working with GeoJson

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/2.3.1
