### ISSUE TITLE
GetCenter() function return lng value minor than -180 to Japan or Asian coordinates.

### ISSUE THREAD

**Issue by fabiansanchez18** [rungwiroon/BlazorGoogleMaps#216]
GetCenter() function return longitude value minor that -180 to Japan or Asian coordinates.
Is this is an issue or it is intended behavior and we must calculate correct value.
this is happening to me with lates nuget packet installed (2.2.6) and calling it from interop:
LatLngLiteral Center = await map.InteropObject.GetCenter();
when center to Tokyo,Japan from google search coordinates on response, the Center variable gets 
Lat = 35.67619189999998, Lng = -220.3496894

Workaround:
            if(Center.Lng < -180)
            {
                Center.Lng = 360 + Center.Lng;
            }

**Comment by valentasm1** [comment]
I get some rought idea, but not sure how to reproduce. Could you provide full sample code and/or steps to reproduce

**Comment by valentasm1** [comment]
Closing due inactivity
