### ISSUE TITLE
Contextmenu / rightclick to show information

### ISSUE THREAD

**Issue by kvenda** [rungwiroon/BlazorGoogleMaps#219]
Great package - Big fan!  I'm using Using Blazor/net6 & Mudblazor (trying to stay open source), and was able to map my data points following the code examples (and I'm a newbie so ...). Would gladly put up some simple, functional examples.  Would also like to see an example showing how to customize the contextmenu/rightclick to show a bubble of information...

**Comment by valentasm1** [comment]
There quite many examples in server side. 
https://github.com/rungwiroon/BlazorGoogleMaps/tree/master/ServerSideDemo

Regarding right click. Do you have any offical examples?

**Comment by valentasm1** [comment]
Closing due inactivity. Feel free to open.
