### ISSUE TITLE
How to remove route created on the map

### ISSUE THREAD

**Issue by komirineni** [rungwiroon/BlazorGoogleMaps#22]
Hi Team,
could you please help me how to remove map route.
I have used below code to create route:

dirRend = await DirectionsRenderer.CreateAsync(map1.JsRuntime, new DirectionsRendererOptions()
		{
			Map = map1.InteropObject
		});
//Direction Request
		DirectionsRequest dr = new DirectionsRequest();
		dr.Origin = "Allentown, PA";
		dr.Destination = "Bronx, NY";
		dr.Waypoints = waypoints;
		dr.TravelMode = TravelMode.Driving;
		
		//Calculate Route
		var directionsResult = await dirRend.Route(dr);

// to remove route,  tried with below code but no luck. could you please help on this.
 await dirRend.SetDirections(null);
        await dirRend.SetMap(null);

**Comment by valentasm1** [comment]
@cyberyaga  any ideas on this?
If not i will take a look then

**Comment by valentasm1** [comment]
I will try to take a look this weekend. Worst on monday.

**Comment by komirineni** [comment]
Any update on this and appreciate for your help

**Comment by valentasm1** [comment]
I just take you example and it works. I update route demos with route remove button. Let me know if it remove route from map or not

**Comment by komirineni** [comment]
sorry, I did not understand your reply. let me know where is the code fix you have done/code to remove the route map?

**Comment by valentasm1** [comment]
Lets take server side project.
Pages > MapRoutes.razor > RemoveRoute method

**Comment by komirineni** [comment]
I am also doing the same code. I missed some steps in my code. it is working now. thanks for the quick help.

**Comment by valentasm1** [comment]
As i understand if you remove route and then you need to create new route, then you need to create layer which isnt good for performance. I saw some ideas which setting new route without directions could also remove route but next time no need to create new layer. Just ideas, not sure if it could work in BlazorMaps
