### ISSUE TITLE
Could not find 'googleMapsObjectManager.createObject' ('googleMapsObjectManager' was undefined).

### ISSUE THREAD

**Issue by YodasMyDad** [rungwiroon/BlazorGoogleMaps#222]
I'm following your example below to get a simple map showing in a Blazor Client Side app. I have added your latest Nuget package and added the using statements in the _Imports file.

I have added the Google maps script tag in the head section of my index.html file with the correct API key. I have then added the following in the bottom of the index.html file under the Blazor js file like you have in your demo example

`<script src="_content/BlazorGoogleMaps/js/objectManager.js"></script>`

I have the following code

```
<div style="height:400px;">
<GoogleMap @ref="@map1" Id="map1" Options="@mapOptions" Height="100%"></GoogleMap>
</div>
```

And the @code is 

```
  private GoogleMap map1;
  private MapOptions mapOptions;	

  protected override void OnInitialized()
  {
    mapOptions = new MapOptions
    {
      Zoom = 13,
      Center = new LatLngLiteral
      {
        Lat = 13.505892,
        Lng = 100.8162
      },
      MapTypeId = MapTypeId.Roadmap
    };
  }
```

I run the app and get the following error. Are you sure the JS file is correctly packaged in the Nuget package?

> Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: Could not find 'googleMapsObjectManager.createObject' ('googleMapsObjectManager' was undefined).
>       Error: Could not find 'googleMapsObjectManager.createObject' ('googleMapsObjectManager' was undefined).
>           at https://localhost:44307/_framework/blazor.webassembly.js:1:328
>           at Array.forEach (<anonymous>)
>           at a.findFunction (https://localhost:44307/_framework/blazor.webassembly.js:1:296)
>           at _ (https://localhost:44307/_framework/blazor.webassembly.js:1:2437)
>           at https://localhost:44307/_framework/blazor.webassembly.js:1:3325
>           at new Promise (<anonymous>)
>           at Object.beginInvokeJSFromDotNet (https://localhost:44307/_framework/blazor.webassembly.js:1:3306)
>           at Object.Rt [as invokeJSFromDotNet] (https://localhost:44307/_framework/blazor.webassembly.js:1:59738)
>           at _mono_wasm_invoke_js_blazor (https://localhost:44307/_framework/dotnet.6.0.10.ab6o20rtby.js:1:195300)
>           at wasm://wasm/00971d2a:wasm-function[219]:0x1a492

**Comment by valentasm1** [comment]
Does latest 2.4.2 nuget solve issue?
https://www.nuget.org/packages/BlazorGoogleMaps/2.4.2

**Comment by YodasMyDad** [comment]
I installed 2.4.3 and that resolved the issue. Thanks.

**Comment by valentasm1** [comment]
I need more details. Please open new issue.

**Comment by SykesJohn** [comment]
I have the same problem simply updating to version 3.0.6 from 2.2.6.

Any progress on this?

**Comment by SykesJohn** [comment]
Solved the problem! Simply do a hard refresh and cache flush. Looks like some stale bits were hanging around.
