### ISSUE TITLE
ArgumentNullException when calling DirectionsRenderer.GetMap when Map is not set.

### ISSUE THREAD

**Issue by Curlack** [rungwiroon/BlazorGoogleMaps#224]
The following code snippet produces an `ArgumentNullException`:

```csharp
//with a GoogleMap component on the page with @ref="map1"...

var directionsRenderer = await DirectionsRenderer.CreateAsync(map1.JsRuntime);
await directionsRenderer.SetMap(map1.InteropObject);
var checkNull = await directionsRenderer.GetMap();
await directionsRenderer.SetMap(null);
checkNull = await directionsRenderer.GetMap(); //<-- Exception here
```
![argumentnullexception](https://user-images.githubusercontent.com/298525/204581987-53a05f22-6db3-417d-a15e-3580ae8e88e1.png)

It seems to be on this line of code: https://github.com/rungwiroon/BlazorGoogleMaps/blob/5b11820d6c03d31df7b2eef28ec312296d6c8d48/GoogleMapsComponents/Helper.cs#L140

The issue seems to be when result from a javascript function call is null, the JsObjRef ecosystem still expects a guid. Issue goes away by changing it to:
```csharp
return guid == null ? default : (TRes)JsObjectRefInstances.GetInstance(guid);
```

**Comment by valentasm1** [comment]
Does latest 2.4.2 nuget solve issue?
https://www.nuget.org/packages/BlazorGoogleMaps/2.4.2
