### ISSUE TITLE
DirectionsRenderer.setDirections(null) doesn't seem to be supported anymore.

### ISSUE THREAD

**Issue by Curlack** [rungwiroon/BlazorGoogleMaps#225]
I saw `DirectionsRenderer.setDirections(null)` in the sample projects, but it causes Google Maps to complain:
![null_directions_not_supported](https://user-images.githubusercontent.com/298525/204584643-3268658a-a512-4f41-8e6b-995b589ac1ed.png)

**Comment by Curlack** [comment]
Don't worry. I've got all three new issues (I've logged) covered...

**Comment by valentasm1** [comment]
Does latest 2.4.2 nuget solve issue?
https://www.nuget.org/packages/BlazorGoogleMaps/2.4.2
