### ISSUE TITLE
Usage Example in Readme does not work

### ISSUE THREAD

**Issue by NiklasTaube** [rungwiroon/BlazorGoogleMaps#227]
At 3. Route Direction Example, the value 350 is assigned to the attribute Height of GoogleMap, then in the code block a variable "Height " is created. However, the variable is never used and you also try to assign 300px to a string (does not work).

**Comment by NiklasTaube** [comment]
README.md, lines 64 and 76

**Comment by valentasm1** [comment]
I will remove it at all. README is just for basic information.
Please check server side samples https://github.com/rungwiroon/BlazorGoogleMaps/tree/master/ServerSideDemo which are most to date

**Comment by valentasm1** [comment]
Removed route part from readme
