### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by valentasm1** [rungwiroon/BlazorGoogleMaps#228]
@rungwiroon 
Hi

Please enable github pages from gh-pages branch
https://stackoverflow.com/a/72587603/1371962

This links should work (i assume)
https://rungwiroon.github.io/BlazorGoogleMaps/m1.png

**Comment by rungwiroon** [comment]
Already enabled it.
Please check if it works correctly.
https://rungwiroon.github.io/BlazorGoogleMaps/

**Comment by valentasm1** [comment]
Working. Awesome. Will update little by little.
