### ISSUE TITLE
Programmatically Closing Info Window throws error

### ISSUE THREAD

**Issue by komirineni** [rungwiroon/BlazorGoogleMaps#23]
Hi Team,

I have created info window on top of the marker and i was able to close the window using close icon which top right of the info window. but when am trying to close info window explicitly like infowind.close() not working. it was throwing null value not convert to system.boolean.

**Comment by valentasm1** [comment]
I will try take a look tomorrow.

**Comment by komirineni** [comment]
@valentasm1  did you get any time to look into the issue fix?

**Comment by valentasm1** [comment]
It was simple. When you call close it call method with return value true/false. In general method dont return any value and when you try parse nothing to true/false you get error.
More info here 
https://developers.google.com/maps/documentation/javascript/reference/info-window#InfoWindow.close
Will update nuget today later and project.
Will inform here

**Comment by valentasm1** [comment]
Added nuget
https://www.nuget.org/packages/BlazorGoogleMaps/0.5.2

Lets me know if you still have this issue.

**Comment by komirineni** [comment]
It worked.Really thank you so much for the quick help.

**Comment by komirineni** [comment]
Fix resolved the issue
