### ISSUE TITLE
How can I trigger a Marker Click Event?

### ISSUE THREAD

**Issue by ChristophWeigert** [rungwiroon/BlazorGoogleMaps#232]
In Javascript/Typescript I would use:

```typescript
    const marker: any = this.markers.find((ma) => ma.customerUniqueId === customerUniqueId); // customerUniqueId  is a custom property on each marker.
    google.maps.event.trigger(marker, "click");
```

In Blazor I have a field with all markers. And I use a button to trigger a marker click event based on a List of Customers:

```c#
// test 1
            DotNetObjectReference<Marker> jsToDotNetBridgeReference = DotNetObjectReference.Create(currentMarker);
            await this.JsRuntime.InvokeVoidAsync("google.maps.event.trigger", jsToDotNetBridgeReference.Value, "click").ConfigureAwait(true);
// test 2
            DotNetObjectReference<Marker> jsToDotNetBridgeReference = DotNetObjectReference.Create(currentMarker);
            await this.JsRuntime.InvokeVoidAsync("google.maps.event.trigger", jsToDotNetBridgeReference, "click").ConfigureAwait(true);
// test 3
            await this.JsRuntime.InvokeVoidAsync("google.maps.event.trigger", currentMarker, "click").ConfigureAwait(true);
```

Any guidance how I can solve this?

**Comment by valentasm1** [comment]
What are you trying to solve? Use case?

**Comment by jacksonsfaria** [comment]
Use AddListener

```
await marker.AddListener<MouseEvent>("click", async (e) => await OnTrackerClick(e));

 async Task OnTrackerClick(MouseEvent e)
    {

    }
```

**Comment by valentasm1** [comment]
Like this?
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarker.razor.cs#L277

**Comment by ChristophWeigert** [comment]
I know how to listen to the click event.

> What are you trying to solve? Use case?
My usecase is that I have a list of customers as a list and as a pin. When I click the Customer in the list I want to "trigger" the click event to show the InfoWindow of the marker (that is already working as a click event with the above mentioned AddListener Event)

**Comment by valentasm1** [comment]
So basicaly you want to show custom window when client click on pin. Isnt it?
Maybe this would help?
https://github.com/rungwiroon/BlazorGoogleMaps/issues/54#issuecomment-660923605

**Comment by jacksonsfaria** [comment]
Your list is in another component. Do you want to show the info referring to the customers that were clicked on?
If so, I'll make an example for you.

**Comment by ChristophWeigert** [comment]
@valentasm1 Thanks this example is working for me already when I click the pin on the map.
But I need a second way to open the InfoWindow when I select a customer from a List.

1. On Page Load I load all Customers + create the Markers and save them In two fields.
2. I click the "+" Button
![image](https://user-images.githubusercontent.com/996391/206727645-6d149b84-d991-434c-8723-f3b169847d34.png)
3. A command is fired, I search for the correct marker.
4. **Not Working** I cannot trigger the "click" event manually. 


Why:
By triggering the click event the map automatically:
- centers the marker in the map even when the marker is not in the visible bounds.
- shows the correct InfoWindow.

**Comment by ChristophWeigert** [comment]
Oh the solution was quite simple.
I just use a InfoWindow and use "SetContent", "SetPosition" and then Open the InfoWindow.
