### ISSUE TITLE
Distance Matrix API example?

### ISSUE THREAD

**Issue by michaelcsikos** [rungwiroon/BlazorGoogleMaps#237]
Is the [Distance Matrix API](https://developers.google.com/maps/documentation/javascript/examples/distance-matrix) supported? Is there an example of calculating a route distance between two locations using only the Distance Matrix API, and not the Directions API?

**Comment by valentasm1** [comment]
There are no DistanceMatrixService implementation.

**Comment by valentasm1** [comment]
Closing due inactivity
