### ISSUE TITLE
Bug - Marker.ClearListeners() has no effect.

### ISSUE THREAD

**Issue by james-llo** [rungwiroon/BlazorGoogleMaps#246]
When I #ClearListeners() from a marker object nothing happens

I have the following applied to "marker"
`await marker.AddListener<MouseEvent>("click", async _ => await ClickDealMarker(deal, marker));`

at the end of that  function I added the following code
```
var before = marker.EventListeners;
await marker.ClearListeners("click"); 
var after = marker.EventListeners;
```

before count is 1 and  the key of item 0 is "click",
after count is 1 and the key of item 0 is "click"

I have not attached any other listeners to the markers.

**Comment by valentasm1** [comment]
You should mention that console throws errors, since clearListeners method dont exist in js.
