### ISSUE TITLE
MarkerClustering Options - MaxZoom is not used in library

### ISSUE THREAD

**Issue by joe-shapiro-biz** [rungwiroon/BlazorGoogleMaps#252]
No Matter what I supply as a value for MaxZoom, the cluster seems to explode at the same zoom level.
[BlazorApp1.zip](https://github.com/rungwiroon/BlazorGoogleMaps/files/11028913/BlazorApp1.zip)

**Comment by valentasm1** [comment]
Will take a look till sunday

**Comment by valentasm1** [comment]
It is not used in library. I market is obsolete. Will remove in future releases.
https://www.nuget.org/packages/BlazorGoogleMaps/3.0.1

We use this library.
https://www.npmjs.com/package/@googlemaps/markerclusterer

Here is example how to use custom renderer
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarker.razor.cs#L139
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/wwwroot/js/serverSideScripts.js
