### ISSUE TITLE
OnAfterInit not being called

### ISSUE THREAD

**Issue by MrYossu** [rungwiroon/BlazorGoogleMaps#253]
I have a map component as follows...

```html
<GoogleMap @ref="@_map" Options="@_mapOptions" OnAfterInit="AfterMapInit" />
```

...and the following in my code-behind...

```c#
  private GoogleMap _map = null!;
  private MapOptions _mapOptions = null!;

  protected override async Task OnInitializedAsync() {
    _mapOptions = new MapOptions {
      Zoom = 13,
      MapTypeId = MapTypeId.Roadmap
    };
    // Other stuff here
  }

  private async Task AfterMapInit() {
    Console.WriteLine($"AfterMapInit - {Transactions.Count} transaction(s)");
    // Code to populate the map with markers
  }
```

When I load the page with the map on, I can see that the `AfterMapInit` method is not being called, so the map is not being set up. I haven't included the code in `AfterMapInit` as it's not relevant, as the method never gets called.

Any idea why it's not being called? Obviously I don't get a map. Thanks

**Comment by valentasm1** [comment]
This one works
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapLegendPage.razor.cs

**Comment by MrYossu** [comment]
I know that one works, but that doesn't help me. Mine doesn't work!

Please don't close issues as son as you've answered them. Maybe you think it's done with, but if my code isn't working, then it's not. Your demo works fine, but that doesn't help me fix my code, which was copied form your demo.

Please can you explain under what circumstances `AfterMapInit` doesn't get fired.

Thanks

**Comment by valentasm1** [comment]
I dont understand how to help. 
Probably there are some issue with your code misconfiguration. 
If there is issue with library i could try to help, but need to reproduce first.

**Comment by valentasm1** [comment]
You could try run demo at your computer and find differencies.

**Comment by MrYossu** [comment]
Well, having spent ages trying to build a repro, my original code now works! No idea what I've changed, but it's working, so this can be closed.

Thanks

**Comment by valentasm1** [comment]
Happy that you resolved.
