### ISSUE TITLE
Geocode. Get GPS coordinates from address

### ISSUE THREAD

**Issue by ALMLAMBO** [rungwiroon/BlazorGoogleMaps#26]
I want to ask why I cannot visualize a place and how to use MapAutocomplete component?

**Comment by valentasm1** [comment]
Could you give use case?
Also example in JavaScript or elsewere?

**Comment by ALMLAMBO** [comment]
This is the code in the browser.
```
GoogleMap map1;
	MapOptions mapOptions;

	bool showCustomerLogin = false;
	bool showPersonalLogin = false;
	AddRepairBindingModel repair =
		new AddRepairBindingModel();

	protected override async Task OnInitializedAsync() {
		MapsCoordinatesBindingModel mapsCoordinates =
			await Task.Run(() => {
				return service
					.GetCoordinates("СПИДИ София - Младост 3 (жк), бл. 319, ж.к. Младост 3, София")
					.Result;
			});

		mapOptions = new MapOptions() {
			Zoom = 13,

			Center = new LatLngLiteral() {
				Lat = mapsCoordinates.Lat,
				Lng = mapsCoordinates.Lng
			},
			MapTypeId = MapTypeId.Sattellite
		};
	}
}
```
I am using Geocoding to get coordinates of a place.

**Comment by valentasm1** [comment]
Thank you. I will take a look today.

**Comment by valentasm1** [comment]
Could you provide full example? You could remove or change sensitive data.
I dont understand what is service. What is MapsCoordinatesBindingModel. Also i dont understand what you are trying to archive.
Maybe you could try to download GitHub solution and tryout MapAutocomplete page on server side. You could debut it and it will help you find how it works. I think you need Autocomplete.GetPlace method call.

**Comment by willapp** [comment]
To make Autocomplete work, you need something like the following:

```
<input type="text" @ref="this.searchBox" id="searchBox" />
<GoogleMap @ref="@map1" Id="map1" Options="@mapOptions" Height="500" OnAfterInit="@(async () => await OnAfterMapInitAsync())"></GoogleMap>

@code {
  private GoogleMap map1;
  private MapOptions mapOptions;
  private ElementReference searchBox;
  private Autocomplete autocomplete;

  protected override void OnInitialized()
  {
    this.mapOptions = new MapOptions
    {
        Zoom = 13,
        Center = new LatLngLiteral
        {
            Lat = 40.621875,
            Lng = -74.125255
        },
        MapTypeId = MapTypeId.Roadmap
    };
  }

  private async Task OnAfterMapInitAsync()
  {     
    this.autocomplete = await Autocomplete.CreateAsync(this.map1.JsRuntime, this.searchBox, new AutocompleteOptions
        {
            StrictBounds = false
        });

    await this.autocomplete.AddListener("place_changed", async () => await this.MapSearchPlaceChanged());
  }

  private async Task MapSearchPlaceChanged()
  {
    var place = await this.autocomplete.GetPlace();

    if (place?.Geometry?.Location != null)
    {
      // do something with the place.Geometry.Location
    }
  }
}
```

**Comment by ALMLAMBO** [comment]
I want to ask how I can use MapAutocomplete from the library?

**Comment by valentasm1** [comment]
Could you confirm it is it what you want to do.
Pass address name "СПИДИ София - Младост 3 (жк), бл. 319, ж.к. Младост 3, София" or similar
Get first coordinates (lat, lng) from result 
Return that coordinates

Am i right?

**Comment by ALMLAMBO** [comment]
Yes.

**Comment by valentasm1** [comment]
It looks like you need geocoding which is not implemented in here. It is not directly related to google maps. I dont want to spend time implementing it here since there are already libraries who does that. 
After you get lat lng then you could set it to map
await this.map1.InteropObject.SetCenter(new LatLngLiteral(){ Lat = 12.12 , Lng = 25.25});

Here is nuget for that
https://github.com/chadly/Geocoding.net

Examples on stackoverflow
https://stackoverflow.com/questions/16274508/how-to-call-google-geocoding-service-from-c-sharp-code

**Comment by valentasm1** [comment]
Closing due innactivity.
