### ISSUE TITLE
Show marker

### ISSUE THREAD

**Issue by ALMLAMBO** [rungwiroon/BlazorGoogleMaps#27]
Hi,
I want to know how can I show the red marker?

**Comment by valentasm1** [comment]
Could you give example in any application or picture ?

**Comment by ALMLAMBO** [comment]
I would like my position with marker. 
![image](https://user-images.githubusercontent.com/36967653/76018229-90bf2d00-5f28-11ea-8538-641af64ee14f.png)

**Comment by valentasm1** [comment]
Like here ?
[https://developers.google.com/maps/documentation/javascript/examples/marker-simple](url)
![image](https://user-images.githubusercontent.com/8047891/76020680-260bf280-5f24-11ea-85e9-22800b9e3678.png)

**Comment by ALMLAMBO** [comment]
I would like to do this with C#.

**Comment by valentasm1** [comment]
I understand that you want to do in c#, but is it you want to get?

**Comment by ALMLAMBO** [comment]
Yes, I want to get a visualisation of this marker with C# resources.

**Comment by valentasm1** [comment]
Is there anything how i can help you?

**Comment by ALMLAMBO** [comment]
Thank you a lot.
