### ISSUE TITLE
Add support for KML files

### ISSUE THREAD

**Issue by turner11** [rungwiroon/BlazorGoogleMaps#271]
As described in  [Google's documentation](https://developers.google.com/maps/documentation/javascript/kml#setting_up_the_kml_file_for_import).  

Thanks for the great package and the time and effort you put into it!

**Comment by valentasm1** [comment]
Hm. Doesn't look like smth very different to existing functionality. It is summer time so mostly in some day of august i will have some time.

**Comment by Nickztar** [comment]
@turner11 I've added support for this, maybe you can try it out and let me know what the use case for something like this is and if what i've implemented can fullful that 👍🏼

**Comment by valentasm1** [comment]
Big big thank you @Nickztar you are guys heros of this lib. 
https://www.nuget.org/packages/BlazorGoogleMaps/3.1.2
