### ISSUE TITLE
Screen size less than 600px (width) doesn't show the map.

### ISSUE THREAD

**Issue by WebMat1** [rungwiroon/BlazorGoogleMaps#278]
When the component is rendered in screen with less than 600px (width), the map is not shown.

**Comment by valentasm1** [comment]
Have you tried modify Height prop?

https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/GoogleMap.razor#L41

**Comment by WebMat1** [comment]
Yes, i have tried this.

my solution was change de cssclass tag to set "min-width:600px;"... and it works fine.

**Comment by valentasm1** [comment]
Soo what you expect from me?
I think it is html related issue or google map library.

**Comment by WebMat1** [comment]
I think you can change de `private string CssStyle` to public and parameter.

**Comment by valentasm1** [comment]
it is public and parameter. Which part are you talking about?
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/GoogleMap.razor#L32C24-L32C24

**Comment by WebMat1** [comment]
StyleStr ?

**Comment by valentasm1** [comment]
It is CssClass. Please open links and you will see
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/GoogleMap.razor#L32C24-L32C24
