### ISSUE TITLE
InvalidValueError when calling SetClickable or SetVisible method of a Marker Instance.

### ISSUE THREAD

**Issue by char8cter** [rungwiroon/BlazorGoogleMaps#28]
When I try to call the SetClickable or SetVisible methods of an instance of a Marker that I have added to a map, I get an exception that states that I passed an invalid value and that it was not a boolean even though I use the boolean literal true or false.

I create a Marker:
`//Origin Marker
        this._OriginLocationMarker = await Marker.CreateAsync(this._TrackingMap.JsRuntime, new MarkerOptions()
        {
            Position = new LatLngLiteral(),
            Visible = false,
            Map = this._TrackingMap.InteropObject,
            Title = "Origin",
            Label = "Origin"          
        });`

Then I try to make it Visible:
`await this._OriginLocationMarker.SetVisible(true);`

Error:
InvalidValueError: setClickable: not a boolean

**Comment by valentasm1** [comment]
I will try to reproduce today and let you know.

**Comment by valentasm1** [comment]
Updated and released nuget. Let me know if it fixed.
https://www.nuget.org/packages/BlazorGoogleMaps/0.5.5

Was error when bool args was converted to string.

**Comment by char8cter** [comment]
I can confirm that the setVisible and setClickable functions now work as expected. Thank you for fixing this.
