### ISSUE TITLE
Rectangle borders' ZIndex

### ISSUE THREAD

**Issue by gitamo626** [rungwiroon/BlazorGoogleMaps#280]
Is there a way to control the effective ZIndex of rectangle's borders? When I draw some markers and then a rectangle, the rectangle's borders are shown behind the markers' icons. I've tried setting the rectangle's ZIndex (both higher and lower than the ZIndex of markers) but still the same behavior is observed (the markers are in the forground while the rectangle's border is shown in the background). I need the rectangle to be shown top-most (above the markers). Thank you.

**Comment by valentasm1** [comment]
Hm. First you should find asnwer on javascript google maps.
It states _The zIndex compared to other polys._ i assume it is not valid for marker. 
https://developers.google.com/maps/documentation/javascript/reference/polygon#RectangleOptions

**Comment by valentasm1** [comment]
It is out of our control of this library. Please let know if you will find asnwer.

**Comment by gitamo626** [comment]
Ok, I'll do my research and respond with a solution (if I find it). Perhaps you can then work it into the library. Thank you.
