### ISSUE TITLE
Migration to .net 8

### ISSUE THREAD

**Issue by valentasm1** [rungwiroon/BlazorGoogleMaps#286]
Created issue to get some opinions.
My plan is to migrate ALL parts to .net 8 in end of dec or jan 2024.

**Comment by valentasm1** [comment]
@Nickztar @turner11 @Enritski @TheAtomicOption @Curlack

**Comment by Curlack** [comment]
I think it's a great idea. Looked into converting some blazor projects to .net 8 myself.
I couldn't convert the aspnet core hosted blazor web assembly though, because aspnetcore does not support it. Not sure if I'm missing something, just wanted to mention it here.

**Comment by Nickztar** [comment]
Sounds like a good plan! Have upgraded some other projects and the breaking changes are close to non-existent.

**Comment by Enritski** [comment]
Yep, this is definitely something I would like to see.

**Comment by valentasm1** [comment]
Here is .net8 version.
Migration was pretty straightforward. 
https://www.nuget.org/packages/BlazorGoogleMaps/4.0.0

**Comment by TheAtomicOption** [comment]
My company also plans to update the project using this to .NET8 soon.

That said, Microsoft intends .NET6 support through Nov.12, 2024 and .NET7 through May 14, 2024. (see: https://dotnet.microsoft.com/en-us/download/dotnet) I think as a public nuget we'd ideally maintain multi-targeting (or at least publish patches for any bugs we find to versions that support .NET6/7) through those dates. We should probably be able to do that by just having multi-framework targeting in the project file.

**Comment by valentasm1** [comment]
@TheAtomicOption PR is welcomed.

**Comment by valentasm1** [comment]
@TheAtomicOption created other issue regarding multi framework support.
https://github.com/rungwiroon/BlazorGoogleMaps/issues/313
