### ISSUE TITLE
Google Maps is not displayed

### ISSUE THREAD

**Issue by HiZackDavid** [rungwiroon/BlazorGoogleMaps#287]
## Google map is not being displayed in our pages : 
![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/87014651/edad1fbf-a637-4a8c-a259-721278f19b27)

## To check if we have anything wrong in our implementation, we copied the sample code for mapEvents, and we still run into the same issue.
![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/87014651/c9510320-e4b5-41f4-83d8-b4422a4d513f)

## We receive the following errors : 
![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/87014651/0dfdac6f-c8fb-4186-830e-d2e6379099f5)
![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/87014651/98f47863-df24-45db-94c6-4724aca85ec4)
![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/87014651/41a99947-1169-4882-8d5d-1da90faa3588)
![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/87014651/4104b414-dfc8-4746-a3f6-4481f7eae779)

## The demo seems to be working (at least it shows the map)
![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/87014651/df2b1aa0-d028-4ecf-81d7-21a5ab82b17b)

## Other(s)
- We tried to use the demo Api Key, but we still run into the same issue

**Comment by valentasm1** [comment]
What could i say. Wish you luck finding it. I am out of the ideas :).
IMO try using pure js map first. If it fails than it is zero related to blazor.

**Comment by HiZackDavid** [comment]
> What could i say. Wish you luck finding it. I am out of the ideas :). IMO try using pure js map first. If it fails than it is zero related to blazor.

You mention being out of ideas, have you ever run into this issue before ?

**Comment by valentasm1** [comment]
Surprisingly i dont use blazor maps. I have very small project where i come up once/twice a year. Thats all. So i couldnt comment from practical side. I still do work on this lib when have time or review PR. From that side didnt get such issues. 
403/401 looks like some intranet filtering or some missing checkbox in google console. I doubt it will come from library itself.

Maybe this
https://github.com/rungwiroon/BlazorGoogleMaps/issues/44

**Comment by HiZackDavid** [comment]
I managed to fix the issue using a very specific version of the google maps api. This is thanks to the suggestion made for this stackoverflow question : 
https://stackoverflow.com/questions/76944666/google-map-api-gray-box-map-not-displaying

In short, instead of : 
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{API_KEY}}&v=3"></script>
I used : 
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={{API_KEY}}&v=3.53"></script>

It still has one issue I am trying to figure out but at least it is now showing a map.

For more info on google api versioning : https://developers.google.com/maps/documentation/javascript/versions#documentation-for-the-api-versions

**Comment by valentasm1** [comment]
So happy that you solved and even more that you shared knowledge.
Sharing is caring :)
