### ISSUE TITLE
Add possibility to create a Marker Clustering

### ISSUE THREAD

**Issue by flacidsnake** [rungwiroon/BlazorGoogleMaps#29]
Hi,
I could create markers (and they work great). I wonder if it's possible to group the markers into clusters as shown here

[https://developers.google.com/maps/documentation/javascript/marker-clustering](https://developers.google.com/maps/documentation/javascript/marker-clustering)

Thanks in advance

**Comment by valentasm1** [comment]
Sorry to inform but no. There is no such funcionality. But i agree that it should be hard to implement. 
I think it is good idea to create other component and dont overload with unnessary data. 
I think it is doable till this month end. Mostly in two weeks. Will update here

**Comment by flacidsnake** [comment]
Hi back @valentasm1 

Is there any update on this?

Thank you!

**Comment by valentasm1** [comment]
Month hasnt ended :D. I am looking at this issue regularly just hard to find time.

**Comment by valentasm1** [comment]
Good new that i implemented that i very hard core way. Now is just need to find nice working way. Bad news i am not sure when i could find time.
If you want i could give starting point and then if you have basic knowleadge you could finish in 3-8h.

**Comment by valentasm1** [comment]
Yea. I got new job and have some doubts that i ever will find time to finish this one. I will leave it open and maybe one day i will finish.

**Comment by Sathish9222** [comment]
Will marker clustering will be realeased?

**Comment by valentasm1** [comment]
One day. Not sure when. Would be easier to make PullRequest if you need.

**Comment by Sathish9222** [comment]
Sure , I will .

**Comment by valentasm1** [comment]
You wont believe what just happen guys. Added some marker clustering. Let me know if it works for you
https://www.nuget.org/packages/BlazorGoogleMaps/0.8.0
https://github.com/rungwiroon/BlazorGoogleMaps/wiki/Marker-Clustering

**Comment by valentasm1** [comment]
If i wont get any response i will close this thread in couple weeks.

**Comment by simeondahl** [comment]
Can't make it work. I also tried it on the server-side demo, but with no luck. I think this functionality is really need, but I can't make it work.

**Comment by valentasm1** [comment]
Do you get any errors on console?

**Comment by simeondahl** [comment]
> Do you get any errors on console?

Never mind, I can see it works. I'm just stupid :-)

**Comment by simeondahl** [comment]
I see there's only there is a demo for server-side, would the same code also work on client-side? - I'm working on a Blazor WebAssembly project.

**Comment by valentasm1** [comment]
I am lazy person. I just update ServerSide demos.  Changing from ServerToClient should be very minimal.

**Comment by simeondahl** [comment]
> I am lazy person. I just update ServerSide demos. Changing from ServerToClient should be very minimal.

Ok, but there is a problem. When I try to access: https://unpkg.com/@@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js - then I get: 
------------------------------------------------------------------------------------------
Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.
------------------------------------------------------------------------------------------
Can you upload the JS file to this repo?

**Comment by simeondahl** [comment]
Found the problem, the documentation says: https://unpkg.com/@@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js
But it's:
https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js 💯 🍡

**Comment by valentasm1** [comment]
Double @ escape @ it in server side. On client it no needed. Good catch.
