### ISSUE TITLE
Marker "stop" mouse event is showing console error messages

### ISSUE THREAD

**Issue by HiZackDavid** [rungwiroon/BlazorGoogleMaps#291]
**Steps to reproduce :**
1- Run ClientSideDemoNet7
2- Go to "Google map markers"
3- Open browser inspector
4- Add a marker
5- Click on the marker

**Result :**
TypeError: Cannot read properties of undefined (reading 'stop')
![Marker click bug](https://github.com/rungwiroon/BlazorGoogleMaps/assets/87014651/ce570c1a-09bc-4c57-b2f7-7a787a727392)

**Comment by valentasm1** [comment]
Duplicate
https://github.com/rungwiroon/BlazorGoogleMaps/issues/153
