### ISSUE TITLE
Blazor Hybrid

### ISSUE THREAD

**Issue by JeffreyHiscox** [rungwiroon/BlazorGoogleMaps#292]
Hi

Firstly great work on this interop, works exceptionally well.

Only issue I have is that there seems to be a form of snap back when it is used in a Blazor Hybrid project (maybe it is not supposed to be used in this sort of project?).

By snap back I mean that if you pan the map to a new location and then release it snaps back to a previous position that you panned across (not back to the original location but back like half the pan).

Am I doing something wrong or is this a known issue in Blazor Hybrid implementation?

https://github.com/rungwiroon/BlazorGoogleMaps/assets/67780443/bb4f2b08-970d-43d4-988a-6c1868fb4a1c

Thanks

**Comment by valentasm1** [comment]
I never seen anything similar to this. 
Any console logs?
Is it just pure map without any control attached?
Maybe change layer?
Maybe other js is ovveriding.

**Comment by JeffreyHiscox** [comment]
Yeah never mind. Something is overriding it in my project as I just tried it in a brand new project and works fine

Sorry for wasting your time
