### ISSUE TITLE
How do I apply the optional style to make the sample page fill the window

### ISSUE THREAD

**Issue by dutts** [rungwiroon/BlazorGoogleMaps#299]
`MapMarker` contains some optional styles to make the map fill the whole window, but I can't figure out how I actually apply that. I would like the map control to occupy the whole of the space to the right of the navigation bar and below the top title bar, is this possible?

**Comment by valentasm1** [comment]
Sorry but i dont get it. These are different components Marker, map controls, map style. Do you have js example? Or some similar example online? Or worst some vizualization with paint or smth like that?

**Comment by dutts** [comment]
I’m referring to this comment https://github.com/rungwiroon/BlazorGoogleMaps/blob/b7a8b49a93cd37542b93378f39cbbfd469f6a726/ServerSideDemo/Pages/MapMarker.razor#L21C6-L21C6

I would like my map to fill the whole page

**Comment by valentasm1** [comment]
More discussion on issue
https://github.com/rungwiroon/BlazorGoogleMaps/issues/35
