### ISSUE TITLE
WaypointOrder JsonPropery Error

### ISSUE THREAD

**Issue by jacksonsfaria** [rungwiroon/BlazorGoogleMaps#305]
Please add `[JsonPropertyName("waypoint_order")]` in `DirectionsRoute.cs ` tou must have forgotten.

Actual
`public List<int> WaypointOrder { get; set; }`

Expected
```
 [JsonPropertyName("waypoint_order")]
 public List<int> WaypointOrder { get; set; }
```
if you want a PR. I do!

**Comment by valentasm1** [comment]
Thank you vey much
https://www.nuget.org/packages/BlazorGoogleMaps/4.0.3
