### ISSUE TITLE
oderv 10000 Markers

### ISSUE THREAD

**Issue by martinx1941** [rungwiroon/BlazorGoogleMaps#307]
Hi , could you provide me a sample (if its possible) 
to load over 10000 markers from a sql database and show them?
is it possible to load on start all the markers?

**Comment by valentasm1** [comment]
Sorry but i am very very time limited. Dont have time to look up for demos in internet
Here is server side demo how add marker
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarkerListPage.razor.cs

You could load markers in OnAfterRenderAsync method
