### ISSUE TITLE
Not able to run a Blank Project with GoogleMapsComponents

### ISSUE THREAD

**Issue by martinx1941** [rungwiroon/BlazorGoogleMaps#310]
Hi, i have set up a new Project with include your Googlemapscomponents.
i would show the MapDataPage.razor page. i have added the Googlemapscomponents to my project.
but i got always an empty page. 
what could i have missed?
[Blazor_Sample_30012024.zip](https://github.com/rungwiroon/BlazorGoogleMaps/files/14100363/Blazor_Sample_30012024.zip)

**Comment by valentasm1** [comment]
Sorry but i wont open solution. There are two working solutions for demo. Server side and client side for .net 8, so you should compare whats difference.
I have very very limited time and have time only for libraary related issues
