### ISSUE TITLE
Accessing the map object via javascript

### ISSUE THREAD

**Issue by ham187** [rungwiroon/BlazorGoogleMaps#317]
Hello,

Sorry, I know this is a pain,

I need to be able to access the javascript Map object, so that I can run some custom JavaScript Code, is there anyway to do this?

I have been trying like below;
  await JS.InvokeVoidAsync("displayTickerAlert1", pO.Paths, map1.JsRuntime);

and then in a javascript function:
 window.displayTickerAlert1 = (paths, themap) => {
  themap.setCenter(new google.maps.LatLng(-34, 151));
}
setCenter, is just an example of what i'm trying to achieve being able to access the map object and do something with it.

**Comment by valentasm1** [comment]
Sorry i dont have exact example. I could send later since i am unable get it now.

**Comment by ham187** [comment]
Yes please, if you could that would be very helpful

**Comment by valentasm1** [comment]
This is pseudo code.
Sorry that it is not the exact working example. I dont have enough time and will to go into specific details. Use friends and stackoverflow for programing help. 

c#
_jsObjectRef.InvokeAsync("displayTickerAlert1", map.Id);

Js
function displayTickerAlert1(mapId){
  var mapObj = mapObjects [mapId];
}

If you want pass more info to js please read ms documentation
https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0
