### ISSUE TITLE
Multiple Ground Overlays

### ISSUE THREAD

**Issue by ham187** [rungwiroon/BlazorGoogleMaps#319]
Hello, and thank you again,

I have a need for multiple ground overlays, and when the user moves the map it needs to redraw them, the problem is I can't clear the original ground overlay, so its just laying them over the top, until you can't see under it.

I tried adding them to a dictionary and then clearing them, but it doesnt work.

 foreach(var go in dictofGroundOverlays)
 {  
     await go.Value.SetMap(null);
 }

any suggestions?

**Comment by valentasm1** [comment]
It should clear.
Any console errors?
If you do like in this demo does it get cleared?
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapGroundOverlayPage.razor.cs#L47

**Comment by ham187** [comment]
nope no errors, I'm adding satellite imagery to a map, which loads as you scroll around the map, and zoom in and out, but as you zoom out some layers overlap, as it can't remove the existing ones before redrawing,

**Comment by valentasm1** [comment]
I am not sure how i can help. Server side demo works. It should be smth else which dont work for you. Could you provide working demo page?
