### ISSUE TITLE
MarkerClustering - Set Click on Zoom level;

### ISSUE THREAD

**Issue by ham187** [rungwiroon/BlazorGoogleMaps#322]
Is there any way to set the zoom level of click on markerclustering?

_markerClustering = await MarkerClustering.CreateAsync(_map1.JsRuntime, _map1.InteropObject, markers, new()
        {
            RendererObjectName = "customRendererLib.interpolatedRenderer",
            ZoomOnClick = true,
        });

Zoom level = 12?

**Comment by valentasm1** [comment]
I am not very familiar with markerclustering
We user this library. If it is possible there it should be possible here. If smth is missing please provide js sample
https://googlemaps.github.io/js-markerclusterer/modules.html

**Comment by ham187** [comment]
I worked something out you can close :)
