### ISSUE TITLE
Advanced Marker Support

### ISSUE THREAD

**Issue by marco-manfroni** [rungwiroon/BlazorGoogleMaps#327]
Hi, I use this awesome library for most of my projects and I would like to thank you for continuing to develope it.
I've just seen a message in the browser console that says:

_As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. At this time, google.maps.Marker is not scheduled to be discontinued, but google.maps.marker.AdvancedMarkerElement is recommended over google.maps.Marker. While google.maps.Marker will continue to receive bug fixes for any major regressions, existing bugs in google.maps.Marker will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide._

Will you add (when? 😊) support to this new marker that google says it's "_can load up to 66% faster than our traditional markers, and provide faster panning and zooming. 1 The feature also supports fast load times for a larger amount of markers_"

BR
Marco

**Comment by valentasm1** [comment]
It exist already AdvancedMarkerView. I have no idea why we named it "AdvancedMarkerView" not "AdvancedMarker". Probably need to rename in future release.

https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/AdvancedMarkerViewPage.razor

**Comment by marco-manfroni** [comment]
I dont think it's the same.
Advanced Marker uses the class **google.maps.marker.AdvancedMarkerElement** https://developers.google.com/maps/documentation/javascript/reference/advanced-markers?hl=it , while looking at the code inside github AdvancedMarkerView uses _google.maps.marker.AdvancedMarkerView_ 

![Screenshot 2024-05-14 164336](https://github.com/rungwiroon/BlazorGoogleMaps/assets/98948833/f1e0f475-22db-4716-a771-0ea3dea15aa9)

I think it's another google component. I didn't find a reference to it inside all this project

**Comment by valentasm1** [comment]
Renamed 
https://github.com/rungwiroon/BlazorGoogleMaps/releases/tag/4.4.0

**Comment by EGInsider** [comment]
@valentasm1  I'm using recently implemented `AdvancedMarkerElement` class in my code and setting `AdvancedMarkerElementOptions.Content = HTML element` but I'm getting the error `Unhandled exception rendering component: AdvancedMarkerElement: "content" invalid: not an instance of Node;`

**Sample Code:** 

``` 
        this.marker = await AdvancedMarkerElement.CreateAsync(Map.JsRuntime, new AdvancedMarkerElementOptions()
        {
            Position = position,
            Map = this.Map.InteropObject,
            Content = $"<div style='background-color:blue'>{position.Lat},{position.Lng}</div>",
        });
```
