### ISSUE TITLE
Geocoding. Get GPS coordinates from address

### ISSUE THREAD

**Issue by hwang77** [rungwiroon/BlazorGoogleMaps#33]
Is it possible to add geocoding?      Passing an address and return  Latlng obj

**Comment by valentasm1** [comment]
Like i stated in https://github.com/rungwiroon/BlazorGoogleMaps/issues/26 it wont be anytime soon. I always could accept Pull request. It is not directly related to google maps and other libraries already doing this quite well.
Etc
https://github.com/chadly/Geocoding.net

**Comment by valentasm1** [comment]
With some nasty workarounds you could work with autocomple which is implemented
