### ISSUE TITLE
Add way to set AdvancedMarker properties

### ISSUE THREAD

**Issue by valentasm1** [rungwiroon/BlazorGoogleMaps#338]
Currently there are no way to setup property. 
Maybe do check if object has such property and set that. Need to check if it has impact on perfomance
One example would be update position for advancedMarker after it is created. Currently there are only properties

**Comment by orbital-git** [comment]
Waiting for it.

Thanks

**Comment by valentasm1** [comment]
Finished for position
https://www.nuget.org/packages/BlazorGoogleMaps/4.6.1

**Comment by orbital-git** [comment]
Hi,

Very nice! Works great. Thanks

I was wondering if it is possible to add other properties as well. It would be great if we can change the Content property. For instance, I would like to change the Svg to reflect a new status.

**Comment by valentasm1** [comment]
Added way to set AdvancedMarker content property
https://www.nuget.org/packages/BlazorGoogleMaps/4.6.2

**Comment by Eddie-Hartman** [comment]
@valentasm1 I noticed that Content supports OneOf string or PinElement, but the SetContent method does not support PinElement. I would need that functionality.
