### ISSUE TITLE
Feature: Traffic, Transit and Bicycle Layer

### ISSUE THREAD

**Issue by orbital-git** [rungwiroon/BlazorGoogleMaps#339]
Hi,

I could not find a way to load the traffic layer.

The [Google docs](https://developers.google.com/maps/documentation/javascript/examples/layer-traffic#maps_layer_traffic-javascript) says this:

`
function initMap() {
  const map = new google.maps.Map(document.getElementById("map"), {
    zoom: 13,
    center: { lat: 34.04924594193164, lng: -118.24104309082031 },
  });
  const trafficLayer = new google.maps.TrafficLayer();

  trafficLayer.setMap(map);
}

window.initMap = initMap;
`

Is it possible to load that layer?

Thanks

**Comment by valentasm1** [comment]
Interesting. Why nobody ever needed this. It looks like quite easy to implement.
Will do next week. PR also wellcomed.

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/4.5.0

**Comment by orbital-git** [comment]
That was fast.

Thanks
