### ISSUE TITLE
Add support for rotation on Marker icon 

### ISSUE THREAD

**Issue by mrakowRC** [rungwiroon/BlazorGoogleMaps#340]
As far as I am aware, the rotation property of the marker icon is not yet supported. Are there any plans to implement this?

**Comment by valentasm1** [comment]
Do you have js code for this functionality?
I dont see this property in marker.
https://developers.google.com/maps/documentation/javascript/reference/marker

**Comment by mrakowRC** [comment]
my mistake i think its for symbols sorry about that
