### ISSUE TITLE
Run js quality check with ChatGpt or similar quality tool

### ISSUE THREAD

**Issue by valentasm1** [rungwiroon/BlazorGoogleMaps#341]
Better finish or add more test in test-all page and only then do js cleanup/optimization

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.0

**Comment by vinco83** [comment]
This seems to have broken some stuff, at least for me. 

It removed the checks that google.maps.places != undefined, i.e.

google.maps.places !== undefined && obj instanceof google.maps.places.PlacesService

This is causing an exception.

**Comment by valentasm1** [comment]
What about now
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.1

**Comment by vinco83** [comment]
That fixed it, thank you!

Although now I'm receiving a different exception. It's unrelated to this, I believe--creating a new Issue to ask for help
