### ISSUE TITLE
Property 'marker' not found Error

### ISSUE THREAD

**Issue by vinco83** [rungwiroon/BlazorGoogleMaps#343]
I'm receiving an exception in objectManager, stringToFunction when attempting to create a new AdvancedMarkerElement:

Property 'marker' not found Error: Property 'marker' not found at stringToFunction (https://localhost:44392/_content/BlazorGoogleMaps/js/objectManager.js:8:23) at Object.createObject (https://localhost:44392/_content/BlazorGoogleMaps/js/objectManager.js:324:35) at https://localhost:44392/_framework/blazor.web.js:1:3244 at new Promise (<anonymous>) at y.beginInvokeJSFromDotNet (https://localhost:44392/_framework/blazor.web.js:1:3201) at gn._invokeClientMethod (https://localhost:44392/_framework/blazor.web.js:1:62841) at gn._processIncomingData (https://localhost:44392/_framework/blazor.web.js:1:60316) at connection.onreceive (https://localhost:44392/_framework/blazor.web.js:1:53957) at i.onmessage (https://localhost:44392/_framework/blazor.web.js:1:82102)

My code to create the element is as follows:
```

        var marker = await AdvancedMarkerElement.CreateAsync(_jsRuntime, new AdvancedMarkerElementOptions
{
    Position = coords,
    Content = ""
});
```

**Comment by valentasm1** [comment]
I dont get this error with your code. 
I think you missing Map and content should be ""
What are you trying to archive?

**Comment by vinco83** [comment]
I apologize for the lack of info--been debugging this for hours now.  I've copied over the example from here: https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapAdvancedMarkerViewPage.razor#L28

So that my code now looks like this:

![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/14079021/b35087f3-5e62-4eed-bf9a-161719057731)

![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/14079021/0cdd8320-8874-4e16-bb95-d961aee67b5c)

But when it attemps to create the marker, it throws the exception mentioned in my initial post:

![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/14079021/cff69260-fda5-4157-920c-b21dd167f960)

I've tried clearing cache, clearing nuget references, re-installing nuget, etc etc...can't seem to figure this one out

**Comment by valentasm1** [comment]
Is it server side or client side?
Ar you able run sample?
Please next time paste code not screenshots.

**Comment by vinco83** [comment]
I managed to figure this issue out (finally).  Seems another dev changed how we're loading the google map javascript. I had to add "&libraries=marker" to our script tag, i.e.

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key={KEY}&libraries=marker"></script>

This issue can be closed. Thanks!!
