### ISSUE TITLE
How to locate Label on top of Icon

### ISSUE THREAD

**Issue by vitalybrandes** [rungwiroon/BlazorGoogleMaps#345]
How to locate Label on top of Icon 
![image](https://github.com/rungwiroon/BlazorGoogleMaps/assets/61165619/49152748-09b0-452f-bced-606a7011ab2b)

```
 string icon = station.IsOnline ? "Img/pin/green-48.png" : "Img/pin/red-48.png";
            LatLngLiteral point = new LatLngLiteral
                {
                    Lat = station.Location.Latitude,
                    Lng = station.Location.Longitude
                };
var marker = await Marker.CreateAsync(_map1.JsRuntime, new MarkerOptions()
    {
        Animation = GoogleMapsComponents.Maps.Animation.Bounce,
        Position = point,
        Map = map, 
        **Label = "label1"**
        Icon = new Icon()
        {
            Url = icon
        }
    });
var infoWindow = await InfoWindow.CreateAsync(_map1.JsRuntime, new InfoWindowOptions()
    {
        Position = point,
        MaxWidth = 250,
    });

```

**Comment by valentasm1** [comment]
I assume you want to show label above marker. Isnt it?

**Comment by vitalybrandes** [comment]
> I assume you want to show label above marker. Isnt it? Not sure how i can help it. Check js examples and try to apply here. I dont know exact implementation. Need to play around to find out

@valentasm1 yap, need the label to be on top of pin

**Comment by valentasm1** [comment]
Here you go
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarker.razor.cs#L211

**Comment by vitalybrandes** [comment]
Thanks @valentasm1
