### ISSUE TITLE
Long Click Listener

### ISSUE THREAD

**Issue by mrakowRC** [rungwiroon/BlazorGoogleMaps#347]
Hi i was just wondering if there is OnMapLongClickListener anywhere in this package? Heres the docs if you dont have it https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/GoogleMap.OnMapLongClickListener

**Comment by valentasm1** [comment]
It is android version not javascript. Do you have javascript version?

**Comment by mrakowRC** [comment]
So from what i m seeing its just a time set on a click event. Which it looks like you have already
