### ISSUE TITLE
Add ability to set AdvancedMarkerElement Draggable Property

### ISSUE THREAD

**Issue by Eddie-Hartman** [rungwiroon/BlazorGoogleMaps#349]
Similar to #338 and #346. I'm migrating from Marker to AdvancedMarkerElement and need the ability to change the draggable property of a marker.

The issue exists because ListableEntityOptionsBase can be set in the constructor, but afaik there is no way to change it after. So the above ask kind of goes for all of those properties. Clickable, Draggable, Map, Visible,

I also noticed there is a GmpDraggable and the other Draggable and I'm not currently sure of the difference.

**Comment by valentasm1** [comment]
Will do this month. Mostly end of it. PR is always wellcome/

**Comment by valentasm1** [comment]
Add ability to set AdvancedMarkerElement draggable, clickable and content(pin element) property via methods https://github.com/rungwiroon/BlazorGoogleMaps/issues/349

https://www.nuget.org/packages/BlazorGoogleMaps/4.7.4

I also dont know why google got rid of Clickable and added GpmClickable. I assume that element is different html element type and they dont want mix it. I tried to find reasons, but could find in 5min. Overall i am curious too.
