### ISSUE TITLE
Blazor United

### ISSUE THREAD

**Issue by KingdomHearts** [rungwiroon/BlazorGoogleMaps#352]
Hello all,

I am trying to use this in my Blazor United app.
But although I think it should work. It doesn't I also don't get errors so that makes debugging kinda hard.
Maybe I do something wrong. I tried multiple things.

https://github.com/KingdomHearts/GoogleMapsTestUnitedApp

**Comment by valentasm1** [comment]
I dont undestand issue. Do you have error code or sample solution?

**Comment by KingdomHearts** [comment]
https://github.com/KingdomHearts/GoogleMapsTestUnitedApp

I've created a repo with my Blazor United App where I tried to use this.

**Comment by valentasm1** [comment]
And what is current result and what is desired result?

**Comment by KingdomHearts** [comment]
Current result is no Map. No Error, nothing. And desired result is at least the Google Maps through this packages. Everything else I can figure out through the samples like markers. So even showing the Google Map is already something. Maybe I forgot something or did something wrong but I don't know what.

In /map page I hoped to find at least Google Maps.
![afbeelding](https://github.com/user-attachments/assets/e280c948-48b1-4877-954e-9335e6eb5e65)

**Comment by valentasm1** [comment]
I tried for 15min and could not find. 
I almost sure this one could help
https://github.com/rungwiroon/BlazorGoogleMaps/issues/342

**Comment by KingdomHearts** [comment]
Thanks. This looks like the answer. I got it working!

**Comment by valentasm1** [comment]
I am curious how often people building this kind solution.
Maybe i should include this in troubleshooting part.

**Comment by KingdomHearts** [comment]
I think it will be more popular in the future. Ofcourse it is relative new so people are looking at what it will be in the future and has a lot of "problems" now. But for Blazor projects this will surely grow over the years.

**Comment by valentasm1** [comment]
I mean not Blazor i mean "Blazor United" or "Blazor Web App". Blazor itself is ok.
