### ISSUE TITLE
Option to set language

### ISSUE THREAD

**Issue by chaoserene** [rungwiroon/BlazorGoogleMaps#356]
Hi - I didn't find anything in the closed issues. Is there any option to set the map language (override the one in the browser)? Here are some examples in Google's documentation: https://developers.google.com/maps/documentation/javascript/localization

**Comment by valentasm1** [comment]
Nickztar did PR and now should be option to set it.
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.8

**Comment by chaoserene** [comment]
@valentasm1 thanks, it looks like this created an issue. On 4.7.7, all was good, but then when upgrading to 4.7.8, I started getting the error below in the browser's console:

![Screenshot 2024-08-28 at 19 16 12](https://github.com/user-attachments/assets/342fc985-2fdd-487d-a397-4d47c3f318bb)

Because of this, my custom events to the map don't work anymore (for example, drag end). Rolling back to 4.7.7 gets rid of the problem. Is there any change that needs to be done from the app side with this new package?

**Comment by valentasm1** [comment]
Agree
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.9
Fixed

**Comment by Nickztar** [comment]
Weird! Will check it out and make a fix tomorrow to make sure that doesnt break. Sorry 😄

**Comment by chaoserene** [comment]
@valentasm1 @Nickztar thanks! it looks like the error is gone now.
