### ISSUE TITLE
Option to remove AdvancedMarkerElement from cluster

### ISSUE THREAD

**Issue by chaoserene** [rungwiroon/BlazorGoogleMaps#359]
Hi all - I didn't find any issue related. Is there any reason why RemoveMarkers only works with an IEnumerable of Markers and it doesn't have an override for an IEnumerable of AdvancedMarkerElement? I wanted to remove elements from my clusters without having to clear the entire cluster so I could create it again (gives a bad UX, since the map markers flicker for 1ms).

Thanks

**Comment by valentasm1** [comment]
Good catch.
Let me know if it works
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.10

**Comment by chaoserene** [comment]
To fully test this, I wanted to ask if you can extend your change to 
`public virtual async Task AddMarkers(IEnumerable<Marker>? markers, bool noDraw = false) `
as well.

**Comment by valentasm1** [comment]
Added 
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.11

**Comment by chaoserene** [comment]
@valentasm1 thanks, it worked perfectly, and no weird errors in the browser's log.
