### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by SeidenstickerLinus** [rungwiroon/BlazorGoogleMaps#362]
Hi all, 
I noticed an issue when trying to render the Map. Everytime I try to do so, I get the following Exception `Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'split')` at Object.initMap

I see this happen from version 4.7.8 onwards. 

My guess would be, that the changes in #358 caused this, more specifically, [the change to apiOptions libraries in the objectManager.js](https://github.com/rungwiroon/BlazorGoogleMaps/pull/358/files#diff-79f1ab0b4c96e080517bf21bd3b2fbfdc041a9fa93848307a388912ef40485b9R320) Unless I'm mistaken property accessors are case sensitive.

Thank you for developing this package btw, it really helps a lot.

**Comment by valentasm1** [comment]
Could you try 4.7.11 version.  Maybe you need clear cache?

**Comment by SeidenstickerLinus** [comment]
I cleared the cache and double checked for every version after 4.7.8, unfortunately the issue persists.

**Comment by valentasm1** [comment]
I need to reproduce it. So far it works on server side. 
How you initilize map? Via config or url?

**Comment by SeidenstickerLinus** [comment]
I always connected via config so far since the docs mention the url being legacy and not recommended, switching to url does the trick and the map renders properly without any issues. Can you reproduce it with config?

**Comment by valentasm1** [comment]
Server side uses config too. 
My suggestion is to clone server side demo and find how it differs from yours. 
Like i said i couldnt fix while i couldnt reproduce.

**Comment by Nickztar** [comment]
Well that sounds weird, I had that issue when my script wasn't refreshed in the cache. Can you send the exception log och something like that so we can track it down @SeidenstickerLinus

**Comment by chaoserene** [comment]
This also happened to me the first time I tried the fix for the mentioned error. Make sure to clean your bin/obj folders in your project, do a dotnet restore, and run your project again.

**Comment by Nickztar** [comment]
Yea, this sounds like the browser having cached the objectManager.js file. Not much we can do in those cases, Best case to handle it is to either have a smart web server that makes sure that the browser doesn't cache or when including it in the html doing something like this:
`_content/BlazorGoogleMaps/js/objectManager.js?q=3073f26f3d4442418c71a3ec35848679` where the q= parameter is just a random string to make sure the browser fetches a new version.

**Comment by valentasm1** [comment]
It is called cache busting and surprise surprise blazor dont have anything out of the box :).

**Comment by chaoserene** [comment]
@Nickztar anything like this tag from MVC that could be added from the package side? https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.taghelpers.scripttaghelper.appendversion?view=aspnetcore-8.0

**Comment by SeidenstickerLinus** [comment]
Looking into cache busting, this seems to be the culprit. I added  `@typeof(App).Assembly.GetName().Version` as a query parameter to the `objectManager.js` and now it works without any issues. Thanks all 🙂
