### ISSUE TITLE
Loading polylines as cluster

### ISSUE THREAD

**Issue by ExitSetup** [rungwiroon/BlazorGoogleMaps#363]
Tried to load a huge amount of polylines and got out of memory error.
In AzureMaps this can be achieved by loading all lines to a layer and then load the layer once.
In this project i can't find something like this, therefore every line gets loaded on it's own, this leads to given memory error when loading to much lines.

**Comment by valentasm1** [comment]
Could it be aspnet blazor issue?

**Comment by ExitSetup** [comment]
As i saw this issue in AzureMaps before and could get around it by loading lines as cluster, i don't think it's blazor related.
In AzureMaps im basicly creating a datasource with all polylines as a list in c# and just creating one layer at the end to load into the map instead of one layer per polyline.
I think it's in BlazorGoogleMaps it would be like the AdvancedMarker Grouping. Is it possible to implement something like this for polylines too? 

Unfortunately i don't understand the interaction with javascript enough to implement this myself.

**Comment by valentasm1** [comment]
I think you need this. Am i right?
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/Maps/Extension/PolylineList.cs

**Comment by ExitSetup** [comment]
Hi, indeed this is what i need. But as far as i understand i have to create each polyline first within this:
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/GoogleMapsComponents/Maps/Polyline.cs
Or is there any way to create a Polyline in C# without using the Polyline.CreateAsync Method for each Line? 
Creating each Polyline first with this method is the reason for the memory overflow.

**Comment by valentasm1** [comment]
I dont get where you see that you need to create polyline first. I think you misunderstood since you need to pass Polyline options not itself.
There are many examples of other List type entities creating.
Here is one for circles
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapCircleListPage.razor.cs
