### ISSUE TITLE
Map does not render in blazor web app

### ISSUE THREAD

**Issue by NIZO0** [rungwiroon/BlazorGoogleMaps#364]
### **BlazorGoogleMaps Version 4.7.11**

Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Cannot read properties of undefined (reading 'split')
10:19:20:264	TypeError: Cannot read properties of undefined (reading 'split')
10:19:20:264	    at Object.initMap (https://localhost:44310/_content/BlazorGoogleMaps/js/objectManager.js:315:42)
10:19:20:264	    at https://localhost:44310/_framework/blazor.web.js:1:3047
10:19:20:264	    at new Promise (<anonymous>)
10:19:20:264	    at y.beginInvokeJSFromDotNet (https://localhost:44310/_framework/blazor.web.js:1:3004)
10:19:20:264	    at gn._invokeClientMethod (https://localhost:44310/_framework/blazor.web.js:1:62730)
10:19:20:264	    at gn._processIncomingData (https://localhost:44310/_framework/blazor.web.js:1:60119)
10:19:20:264	    at connection.onreceive (https://localhost:44310/_framework/blazor.web.js:1:53760)
10:19:20:264	    at i.onmessage (https://localhost:44310/_framework/blazor.web.js:1:81866)

**Comment by valentasm1** [comment]
I think it is related
https://github.com/rungwiroon/BlazorGoogleMaps/issues/362
