### ISSUE TITLE
Add a marker on OnInitializedAsync or OnAfterRenderAsync

### ISSUE THREAD

**Issue by DSBhogal** [rungwiroon/BlazorGoogleMaps#37]
I'm trying to add a marker to the map without the need of a button to click. So when someone loads the page the map already has a marker. Is this possible? I couldn't find anything relevant to my issue in the documentation

**Comment by valentasm1** [comment]
It should be avaible. Did you get any  error.
I would suggest use GoogleMap action OnAfterInit
Let me know if it you have other questions and this helps you

```
<GoogleMap @ref="@map1" Id="map1" Options="@mapOptions" OnAfterInit="@(async () => await AfterMapRender())"></GoogleMap>

@code
{
    public async Task AfterMapRender()
    {
        //Add markers here

    }
}
```

**Comment by valentasm1** [comment]
Closing due inactivity.
