### ISSUE TITLE
Add properties to InfoWindowOptions interface

### ISSUE THREAD

**Issue by chaoserene** [rungwiroon/BlazorGoogleMaps#371]
Hi there, is it possible to add all properties that exist within Google Maps' InfoWindowOptions interface? ref.: https://developers.google.com/maps/documentation/javascript/reference/info-window#InfoWindowOptions

Thank you!

**Comment by valentasm1** [comment]
Hopeful didnt miss or misspell.
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.12
