### ISSUE TITLE
libraries and version not passed to init when going from 4.7.7 to later

### ISSUE THREAD

**Issue by KristaNEO** [rungwiroon/BlazorGoogleMaps#372]
![Capture](https://github.com/user-attachments/assets/3763797b-21b6-4417-b3d0-c2acd1330d1b)
Works with 4.7.7 and below, error on .split after as libraries is now null

**Comment by valentasm1** [comment]
Maybe related to cache. 
https://github.com/rungwiroon/BlazorGoogleMaps/issues/362

**Comment by KristaNEO** [comment]
Yes thank you, that was it. Cache busting and clearing obj and bin folders resolved the issue.
