### ISSUE TITLE
Bug. Advanced Marker Element Scaling should be using double

### ISSUE THREAD

**Issue by Schwehmmy** [rungwiroon/BlazorGoogleMaps#375]
Not sure if I'm doing it correctly or not, but when I try to scale an Advanced Marker Element it seems to require an integer for the scale value.  Is there any way to use decimal values to scale items, e.g. I may want a marker to be 70% size so I'd like to be able to use 0.7.  I know this is doable in Javascript with Advanced Marker Elements. Otherwise, I find the BlazorGoogleMaps very helpful so I can keep most of my code in C#!

**Comment by valentasm1** [comment]
You right.
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.13

**Comment by Axium7** [comment]
Hello BlazorGoogleMaps,

Thank you for creating this Library for Blazor.   I am very new to C# and Blazor but I have had success utilizing your library.

I posted a questions on StackOverflow about how can I change the MapTypeID at Runtime?   If any one could kindly respond I would greatly appreciate it.

[https://stackoverflow.com/questions/79052468/how-can-i-change-mapoptions-in-the-blazorgooglemaps-library-at-runtime](url)

Thank you again for creating this Library.  It is very important for the future of Blazor.

**Comment by valentasm1** [comment]
@Axium7 next time create new issue for that.
Demo is the best friend. Even better if you could start them on you machine. Honestly this is one of the best way to learn. 
I think you need this. If not then create new issue
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/Maps.razor#L114

**Comment by Axium7** [comment]
Thanks for your response Valentasm1 on here and on StackOverflow .  I have been utilizing the Server Side Demo on my machine and it's been helpful.  Unfortunately, I never noticed the Toggle Map Type functionality in the Demo.

<<next time create new issue for that.

Issues is where I can ask these kind of Questions?  I thought Issues were for discussing Bugs and Feature Request?  As mentioned I am very new to this ecosystem but eager to learn.

Thanks again Valentasm1

**Comment by valentasm1** [comment]
One issue one topic. If you start putting a lof of different type of info into one issue then it will be hard to find for person like you and person like me

Like i said mostly all project has demo, sample where you could check. Wiki is not always covers most topic if any exist at all.
