### ISSUE TITLE
Cannot extract Text from the MarkerLabel Object.

### ISSUE THREAD

**Issue by Axium7** [rungwiroon/BlazorGoogleMaps#380]
I've only been coding in C# / Blazor for 3 months but I don't believe this is working as intended.  I am unable to extract the Text from the Marker Label.  Please advise.  Thank you for building BlazorGoogleMaps.

// Directly get the MarkerLabel object
var markerLabel = await marker.GetLabelMarkerLabel();

![image](https://github.com/user-attachments/assets/3b8587f3-c619-41da-a847-00026433486c)

// Access the Text property directly
```
strMarkerRank = markerLabel.Text;

strMarkerRank = "{\"color\":\"white\",\"fontSize\":\"12px\",\"text\":\"1\",\"className\":\"markerIconLabel\",\"dotnetTypeName\":\"GoogleMapsComponents.Maps.MarkerLabel\"}"
```

This is how I create my label.
```
var markerOptions = new MarkerOptions
	{
		Position = genCoordinates,
		Map = refGoogleMap.InteropObject,
		Title = generator.GenName,
		Icon = new Icon { Url = "https://maps.google.com/mapfiles/ms/icons/purple.png" },
		Draggable = true,
		Label = new MarkerLabel
		{
			Text = generator.Rank.ToString(),
			Color = "white",
			FontSize = "12px",
			ClassName = "markerIconLabel"
		}
	};
```
// Create the marker
var marker = await Marker.CreateAsync(refGoogleMap.JsRuntime, markerOptions);

**Comment by valentasm1** [comment]
Strange not sure which part to fix. Why js is serilized as element not object or add extra check if if marker response contains dotnetTypeName and then serilize to it.
Probably will do second one since doing fixes in first part could break. Strange it should happen to many more parts.

**Comment by valentasm1** [comment]
Temp solution for you would be serialize to MarkerLabel when found such key in js "dotnetTypeName\":\"GoogleMapsComponents.Maps.MarkerLabel

**Comment by Axium7** [comment]
Thanks for your response Valentasm.  I'll think about what you said tomorrow and attempt to implement.

**Comment by valentasm1** [comment]
Fixed.
Let me know if there is some issues
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.15

**Comment by Axium7** [comment]
Valentasm, I worked around this issue but will check if there are issues with your release later this week.

**Comment by Axium7** [comment]
Valentasm, I worked around this issue but will check if there are issues with your release later this week.

**Comment by Axium7** [comment]
> Fixed. Let me know if there is some issues https://www.nuget.org/packages/BlazorGoogleMaps/4.7.15

Yes.  Works Well!  Thank you Valentasm1.

![image](https://github.com/user-attachments/assets/4e8ce492-e4f0-4cc0-9ab3-4acc7b2dec85)
