### ISSUE TITLE
Setting ColorScheme to Light at runtime doesn't work

### ISSUE THREAD

**Issue by poteb** [rungwiroon/BlazorGoogleMaps#381]
Startup `ColorScheme` is set to `ColorScheme.Light`.
I have a toggle switch that changes my site to dark mode.
I update the map to dark mode like this:

`_map1.InteropObject.SetOptions(new MapOptions{ColorScheme = b ? ColorScheme.Dark : ColorScheme.Light});`

This works fine.
But when I want to change it back to light mode nothing happens.

**Comment by poteb** [comment]
More code that shows how I have checked that the value of `b` is indeed changing.

```
DarkModeHandler.AddListener(b =>
{
    Console.WriteLine($"Setting color scheme to {(b ? "dark" : "light")}");
    _map1.InteropObject.SetOptions(new MapOptions{ColorScheme = b ? ColorScheme.Dark : ColorScheme.Light});
});
```
`DarkModeHandler` is my own class where the switch changes the value.

**Comment by poteb** [comment]
Waaait... is dark mode just using satellite map type to make it darker? It switches to satellite when I change ColorScheme to Dark. And if I set MapTypeId to Roadmap it ignores dark mode.

**Comment by valentasm1** [comment]
_The initial Map color scheme. This option can only be set when the map is initialized._
https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.colorScheme
