### ISSUE TITLE
Toggle Scrollwheel when Map is Maximized

### ISSUE THREAD

**Issue by Axium7** [rungwiroon/BlazorGoogleMaps#382]
Is it possible to capture the event when the Map is maximized in full screen mode?   I would like to toggle the Scrollwheel ON in this state and then turn it OFF when the Map goes out of the Maximized state.

I have been attempting to Turn the scroll wheel ON using the below code.  Please note I am new to C# / Blazor.

```
window.addMaximizeGoogleMapListener = function () {
	const maximizeButton = document.querySelector('.DO NOT Know what to Put Here.  Cannot Inspect Max / Full Screen Button'); 

	if (maximizeButton) {
		maximizeButton.addEventListener('click', function () {
			DotNet.invokeMethodAsync('GoogleMapsComponents', 'ToggleScrollWheel');
		});
	}


[JSInvokable]  
public async Task ToggleScrollWheel()
{
	scrollEnabled = !scrollEnabled;
	mapOptions.Scrollwheel = scrollEnabled;
	await refGoogleMap.InteropObject.SetOptions(mapOptions);
}

await JSRuntime.InvokeVoidAsync("addMaximizeGoogleMapListener");
```

**Comment by valentasm1** [comment]
I dont know how you could not inspect full screen button. I got this button class "_gm-control-active gm-fullscreen-control_"
Aslo dont understand where you want to put scroolbar if map is in full screen.
Often i look for js examples. If it possible to do it there then possible in blazor too.

![image](https://github.com/user-attachments/assets/3447200c-9667-4c33-a294-b6bba1558ecf)

**Comment by Axium7** [comment]
Thanks for you response Valentasm.   '.gm-fullscreen-control' worked. 

I want to enable the ScrollWheel so the user can Zoom in and Zoom out with the their mouse scroll wheel but only in Full Screen Mode.

**Comment by Axium7** [comment]
Valentasm,  I was watching a video from about a month ago and in that video I had the ScrollWheel enabled but the UI was prompting me to Zoom using CTRL+ScrollWheel.  

![image](https://github.com/user-attachments/assets/48f5c45c-32d6-4b80-9ef4-000f2525ea5c)

If I could get CTRL+ScrollWheel to work (ScrollWheel on its own **disabled**) that would be the best solution.

How do I enable CTRL+ScrollWheel but disable just the ScrollWheel on its own?

Thank you.

**Comment by Axium7** [comment]
Thank you Valentasm.  Much appreciated.

**Comment by Axium7** [comment]
Valentasm, thank you for all your responses.  I have discovered the following in regards to Ctrl+Scroll to Zoom in BlazorGoogleMaps.

With a certain degree of Vertical Scrollbar, CTRL+ZOOM is enabled, while Scrollwheel = true.

![image](https://github.com/user-attachments/assets/01b9394a-d736-407a-80f2-fa2555c8a87f)


With a smaller degree of Vertical Scrollbar (25px less than above), CTRL+ZOOM is disabled, and Scrollwheel = true Zooms on it's own.

![image](https://github.com/user-attachments/assets/f68e4417-0c3a-4c95-99b5-41cb955fc042)

Is there a way I can still have CTRL Zoom active even without a Vertical Scrollbar?

Thank again for all your feedback Valentasm.   BlazorGoogleMaps is important for my project and I appreciate your advice.

**Comment by valentasm1** [comment]
Funnily enough i dont work with blazor, nor js on my work or free time. 
Big scroll bar crtl + zoom ok, Small scroll bar crtl + zoom not ok.

Since google map is rendered at OnAfterRenderAsync(bool firstRender) even maybe if you do some js logic in same even in page even and set mapoptions with correct values it could workout. Problem with that that map even could be trigered first. You should try.

**Comment by Axium7** [comment]
Valentasm1, with the help of AI I was able to arrive at the desired solution.  The key was the GestureHandling Property in MapOptions. I hope this helps others and thanks for your help Valentasm1.

mapOptions = new MapOptions
	{
		Zoom = 18,
		MapTypeId = MapTypeId.Roadmap,
		Center = new LatLngLiteral()
		{
			Lat = 40.603629,
			Lng = -75.472518
		},
		**GestureHandling = "cooperative" // Enable Ctrl+Scroll zoom in all situations.  It's is important that you do not specify ScrollWheel = true because it will override the GestureHandling Property.**
	};

**Comment by valentasm1** [comment]
Cha cha. And still some pp dont use ai. I am gratefull that you share your solution.

**Comment by Axium7** [comment]
AI didn't give me the full solution but it made me aware of GestureHandling and then I looked up that Property in your docs.  AI is definitely useful but it can also waste your time sometimes.  Thanks again for BlazorGoogleMaps!

**Comment by Axium7** [comment]
This is the full solution Valentasm1.  Once again AI helped.  This time Claude AI got the right answer for me.

```
mapOptions = new MapOptions
{
    Zoom = 18,
    MapTypeId = MapTypeId.Satellite,
    GestureHandling = "cooperative" // Enable Ctrl+Scroll zoom
    // It's important that you do not specify ScrollWheel = true because it will override the GestureHandling Property.
};

  /*Hide tooltips */
.gm-style > div > div > p[class^="gm-style-"] {
    opacity: 0 !important;
    display: none !important;
    visibility: hidden !important;  Changed 'none' to 'hidden' as visibility uses hidden/visible 
}

/* Target shading overlay more specifically */
.gm-style div[aria-hidden="true"][style*="background-color"],
.gm-style div[style*="background-color: rgb(0, 0, 0)"],
.gm-style div[style*="background-color: rgba(0, 0, 0"],
.gm-style > div:nth-child(1) > div:nth-child(3) {
    background-color: transparent !important;
    opacity: 0 !important;
    pointer-events: none !important;
}
```

**Comment by valentasm1** [comment]
I think we could close it.
Let me know if i am wrong

**Comment by Axium7** [comment]
Closing is good.  Thanks Valentasm
