### ISSUE TITLE
AutoComplete Misconfiguration?

### ISSUE THREAD

**Issue by elvogel** [rungwiroon/BlazorGoogleMaps#387]
Hello,

I am working on an application where I am looking to use only Autocomplete. I have followed the instructions you gave regarding configuring the BlazorGoogleMap in the Program.cs, as follows:

```
builder.Services.AddBlazorGoogleMaps(new MapApiLoadOptions("key")
    {
        Libraries = "places",   
        Version = "weekly"
    });
```
On the page where I wish to use Autocomplete, I have the following scripts configured at the bottom of the page:

```
<script loading="async" src="https://maps.googleapis.com/maps/api/js?key=ApiKey&libraries=places,maps"></script>
<script src="_content/BlazorGoogleMaps/js/objectManager.js"></script>

```
In the page where I wish to use Autocomplete, I run into a dilemna:
- if I run it this way, my code runs perfectly fine but I encounter errors in the browser console where it says I am loading the Google API multiple times. The header appears to inject several different JS files repeatedly in the header, with of course the API declaration at the bottom:
![bgm-with-api](https://github.com/user-attachments/assets/9d7a1099-533b-4e3b-966d-ce1f4401422b)

- If I comment out the line where I include include the Google API script, I get nothing. 

Is it possible I have something misconfigured, or not using a component I should be?

**Comment by valentasm1** [comment]
Interesting. Had never seen any inject script issue. Is it server or client side?

**Comment by Nickztar** [comment]
`builder.Services.AddBlazorGoogleMaps` does basically the same as including the script tag `https://maps.googleapis.com/maps/api/js?key=ApiKey&libraries=places,maps`. Those script tags that you then see are the ones that google themself add. There currently is no way to load the `places` library only when you need it, but maybe something that we can add. 

Make sure to remove this part to prevent loading the library twice
`<script loading="async" src="https://maps.googleapis.com/maps/api/js?key=ApiKey&libraries=places,maps"></script>`
and it should be working fine.

**Comment by valentasm1** [comment]
Here is example
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/Maps.razor#L42

**Comment by elvogel** [comment]
Thank you for the responses. Let me clarify a couple of parts to my question:

- It is a server-side application (InteractiveServer)
- only want Autocomplete - no maps (too expensive at scale)
- if I remove the explicit script tag, I get no injected scripts at all. When I add it, I get the injected scripts twice which is ugly in the browser console output but it works fine

Here is the error I get when I remove the script declaration:

```
[09:06:28 ERR] Microsoft.JSInterop.JSException in Google Autocomplete setup: Property 'google' not found
Error: Property 'google' not found
    at stringToFunction (https://localhost:7252/_content/BlazorGoogleMaps/js/objectManager.js:8:23)
    at Object.createObject (https://localhost:7252/_content/BlazorGoogleMaps/js/objectManager.js:355:35)
    at https://localhost:7252/_framework/blazor.web.js:1:2900
    at new Promise (<anonymous>)
    at w.beginInvokeJSFromDotNet (https://localhost:7252/_framework/blazor.web.js:1:2857)
    at vn._invokeClientMethod (https://localhost:7252/_framework/blazor.web.js:1:65750)
    at vn._processIncomingData (https://localhost:7252/_framework/blazor.web.js:1:63139)
    at connection.onreceive (https://localhost:7252/_framework/blazor.web.js:1:56780)
    at i.onmessage (https://localhost:7252/_framework/blazor.web.js:1:80728)
```

**Comment by valentasm1** [comment]
Maybe this helps?
https://github.com/rungwiroon/BlazorGoogleMaps/issues/342

**Comment by elvogel** [comment]
It does not help. I do not want to use the map control - only the autocomplete functionality. The control is designed so they work together, which I understand, but ultimately I'm looking to use Autocomplete without having to incur the cost of loading a Google map, which almost works perfectly well. 

If I have to live with the solution I have, I can - it's just a bit messy and I don't know enough JavaScript to understand what the fix would be here. The autocomplete functionality otherwise works very well, is a fairly elegant solution imo and this project is great for what everyone has put together.

**Comment by valentasm1** [comment]
I just tried to use autocomplete without google map. It only works with providing <script loading="async". No need map
This is "issue" with InteractiveServer and probably this issue is similar since there double renders.
https://github.com/rungwiroon/BlazorGoogleMaps/issues/365

So far noone found solution. @rendermode @(new InteractiveServerRenderMode(prerender: false)) works in some cases but not all.

**Comment by valentasm1** [comment]
Could @elvogel  try this solution?
For me the solution was to add  data-enhance-nav="false" to the url that has the navigation to the map.

<a data-enhance-nav="false" href="/map">Display map</a>

**Comment by elvogel** [comment]
> Could @elvogel try this solution? For me the solution was to add data-enhance-nav="false" to the url that has the navigation to the map.
> 
> [Display map](/map)

Which URL is this? The <script/> URL?

**Comment by valentasm1** [comment]
I found it from related issue
https://github.com/rungwiroon/BlazorGoogleMaps/issues/365#issuecomment-2530949551

**Comment by elvogel** [comment]
It doesn't help me with anything actually. I'm *only* trying to use Places. I don't load maps anywhere. I don't want to incur the cost of loading a map. I'm simply trying to get Autocomplete for addresses. The current Autocomplete functionality is sufficient and good - I just wanted to see if there were something around the issues I kept seeing. 

It looks like all the APIs are changing and it looks like Autocomplete is now turning into its own separate product, so it may be a moot point:

https://developers.google.com/maps/documentation/places/web-service/place-autocomplete
