### ISSUE TITLE
After hiding Map and then Displaying it again refGoogleMap.InteropObject == null?

### ISSUE THREAD

**Issue by Axium7** [rungwiroon/BlazorGoogleMaps#388]
The first time the below GoogleMap is rendered everything works fine.

If I make generatorTarget == null to hide the map and then show the map afterwards for the 2nd time I get the error in the screenshot.

refGoogleMap is still set but refGoogleMap.InteropObject == Null.   

I would like to be able to show the map when generatorTarget != null and hide the map when generatorTarget == null?

How can I achieve the above?

Thank you

```
@if (generatorTarget != null)
{
	<GoogleMap @ref="@refGoogleMap"
			   Id="map1"
			   Options="@mapOptions"
			   OnAfterInit="CreateTargetMarker">
	</GoogleMap>
}
```

![image](https://github.com/user-attachments/assets/3ccf62f7-a221-4fab-b50f-b95f37db1666)

**Comment by valentasm1** [comment]
What is generatorTarget ?

**Comment by Axium7** [comment]
Valentasm,

After your question I decided to create a full example for you and I realized BlazorGoogleMap is Showing and Hiding Properly so the error was on my end.

I am re-using the MapIni() in other parts of the program and it was actually being called twice when the Map was re-rendered the 2nd time.   I provided the solution for the 2nd re-render.

```
//Should only be run after the Map is Initialized.  
if (refGoogleMap != null)
{
	if (refGoogleMap.InteropObject != null)
	{
		//This is only executed if the Map is fully Initialized.  Works if the map is hidden and then shown again
		await MapIni(false);  //false indicates the Map was already initialized and I can skip that part of the code
	}
}

```

**Comment by valentasm1** [comment]
Happy that you shared info and solved it.

**Comment by valentasm1** [comment]
Looks nice. I am more happy about seeing blazor in production than google maps.

**Comment by Axium7** [comment]
Valentasm,

> I am more happy about seeing blazor in production than google maps.

Why is that?  I am curious, since you seem to be the main maintainer of Blazor Google Maps from my experience here.

**Comment by valentasm1** [comment]
I just think blazor is underrated, so each successful project gives more visibility to it. Personally i dont work with blazor in my date to date. Only personal projects

**Comment by Axium7** [comment]
Thanks for sharing your response Valentasm.
