### ISSUE TITLE
Polyline Icon with path as SymbolPath fails render

### ISSUE THREAD

**Issue by SamVanhoutte** [rungwiroon/BlazorGoogleMaps#392]
Hello there , 

I have upgraded to the latest version of `BlazorGoogleMaps` (`4.9.1`) , but when I want to plot a single Polyline on the map, I get a Javascript error in the console and the polyline is not plotted.  

The error is the following: 
```
util.js:354  Uncaught Error: First instruction in path must be "moveto".
    at iJa.parse (util.js:354:2008)
    at THa.parse (util.js:354:609)
    at k1a.Hg (util.js:249:130)
    at poly.js:52:184
    at Array.map (<anonymous>)
    at F_a (poly.js:52:166)
    at poly.js:23:109
```

All code can be found in my repo https://github.com/samvanhoutte/cotacol-site 
And more specifically in the following code files: 
- [MapListService.cs](https://github.com/SamVanhoutte/cotacol-site/blob/main/src/Cotacol.Website/Services/Maps/MapListService.cs)
- [ClimbMapComponent.razor](https://github.com/SamVanhoutte/cotacol-site/blob/main/src/Cotacol.Website/Components/CotacolHunting/ClimbMapComponent.razor)

It used to work before, so I cannot put my finger on what exactly would have been changed, other than upgrade to net8 and the latest BlazorGoogleMaps. 

If you want to see it live at action , this is a sample page: https://cotacol.eu/cotacol/270 
And a screenshot for reference of that page: 

<img width="2543" alt="image" src="https://github.com/user-attachments/assets/8f2a9d0a-2467-44dc-a073-b0b206ca32a6" />

**Comment by SamVanhoutte** [comment]
A bit more information , as it seems to be related to the usage of `Icons` on the `PolyLineOptions` object. 

So, when I have the `showArrow` variable set to `false`, the polyline is plotted. 

But when this part is added, it fails with the exception: 

```csharp
            if (showArrow)
            {
                options.Icons = new[]
                {
                    new IconSequence
                    {
                        Icon = new Symbol { Path = SymbolPath.CIRCLE, Scale = 3f, StrokeColor = "green" },
                        Offset = "0%"
                    },
                    new IconSequence
                    {
                        Icon = new Symbol { Path = SymbolPath.CIRCLE, Scale = 3f, StrokeColor = "red" },
                        Offset = "100%"
                    },
                    // new IconSequence
                    // {
                    //     Icon = new Symbol {Path = SymbolPath.FORWARD_OPEN_ARROW, Scale = 3f},
                    //     Offset = "50%"
                    // },
                };
            }
```

**Comment by valentasm1** [comment]
Try this version
https://www.nuget.org/packages/BlazorGoogleMaps/4.9.2

**Comment by SamVanhoutte** [comment]
I can confirm this works - thanks for letting me know.
