### ISSUE TITLE
Unable to get demo to show map

### ISSUE THREAD

**Issue by RossWright** [rungwiroon/BlazorGoogleMaps#4]
I cloned the repo, opened in VS2019 Preview 3, ran and on the map page I see the buttons, but the map never appears. ideas? Anything else I need to do from a clean pull on a new install to get this going?

**Comment by rungwiroon** [comment]
I can reproduce this issue, I will investigate and fix it.

**Comment by rungwiroon** [comment]
Could you try to run with implement_more_features branch instead.
It seems like master branch is broken.

**Comment by RossWright** [comment]
Can confirm, switching to head of implement_more_features branch works

**Comment by rungwiroon** [comment]
This issue have fixed and merge to master branch.
