### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by vd3d** [rungwiroon/BlazorGoogleMaps#41]
Hi,

In the class JsObjectRef.cs I noticed:

1 - There is a lot of "async" call, but the methods are not async and there are a lot of missing "await" everywhere. Is it normal ?

2 - In the method DisposeAsync(), you call "googleMapsObjectManager.dispose", but it does not exists in the javascript code !

Thanks

**Comment by valentasm1** [comment]
Is something not working?
Are you proposing performance suggestions?

Please be more specific. IMO if something is working even on weird interfaces then just leave it. Except if you could dedicate to spent time to test it and fix it after refactoring (if needed).

**Comment by valentasm1** [comment]
Closing due inactivity.

**Comment by BasKursten** [comment]
Hi,

I can confirm this issue. I have had it as well and there is an error in the JsObjectRef.cs it calls "googleMapsObjectManager.dispose" but that doesn't exist in the javascript code. There it is called "disposeObject". When I changed it I didn't receive the error anymore.

**Comment by valentasm1** [comment]
It was fixed in https://www.nuget.org/packages/BlazorGoogleMaps/0.6.6
