### ISSUE TITLE
Map not rendered

### ISSUE THREAD

**Issue by vd3d** [rungwiroon/BlazorGoogleMaps#44]
Hi,

I have a special case... sorry ;-)

I show a bootstrap modal, this one contains the Google map component.
Just after the modal is shown, I have 2 possibles actions:
1) I center the map to my current lon/lat
```
  await _modal.Show();
  await _modal.Map.Center();
```

2) I try to render a direction
```
  await _modal.Show();
  await _modal.Map.DrawDirections();
```

Case (1), everything goes fine.

Case (2), the map is not always rendered, sometimes 50% of the map is visible only!
Also, it does not zoom around the direction path.

But, noticed that if I force a redraw of the directions (see on the picture, I have a button), it works perfectly then :-P

Do you have any idea of the issue? ( I don't ) :-P

Thx

![image](https://user-images.githubusercontent.com/17200971/83878612-b84aaf00-a73c-11ea-985c-d9de7e313403.png)

**Comment by valentasm1** [comment]
Could you try add Task.Delay(1000) in some locations. Just to be sure if it help. Not to use as main solution. Also could you post a bit more code to help reproduce issue

**Comment by vd3d** [comment]
Thanks,

It does not help, but if I remove the "fade" effect from the modal, it seems to works !

**Comment by valentasm1** [comment]
Sooo it mean no problem then?
Maybe doing smth on OfterRenderAsync could help.

**Comment by vd3d** [comment]
Indeed, playing with AfterRenderAsync  made the trick, thanks ;-)
