### ISSUE TITLE
Is it possible to set an custom marker image?

### ISSUE THREAD

**Issue by Begic** [rungwiroon/BlazorGoogleMaps#46]
Hello, 

I try to change the beachflag marker with a custom image marker, but it doesn't work. 
Google Maps open and works normally but you can't see the custom marker.

Is there a way to change it or can’t it get changed?

        await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions
        {
            Position = new LatLngLiteral
            {
                Lat = (double)lastlatitude,
                Lng = (double)lastlongitude
            },
            Icon = new Icon
            {
                Url = "https://localhost:44329/img/icons/greenMarker.png"
            }
        });

**Comment by valentasm1** [comment]
I assume it is not map component related but blazor itself.
Do you get error in console? Could you access image direcly from browser? Maybe it is too big.

Here is sample which works with custom icon.
```
private async Task AddMarker()
{
	var mapCenter = await map1.InteropObject.GetCenter();

	var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
	{
		Position = mapCenter,
		Map = map1.InteropObject,
		Label = $"Test {markers.Count}",
		Icon = new Icon()
		{
			Url = "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png"
		}
		//Icon = "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png"
	});

	await bounds.Extend(mapCenter);

	var icon = await marker.GetIcon();

	Console.WriteLine($"Get icon result type is : {icon.Value.GetType()}");

	icon.Switch(
		s => Console.WriteLine(s),
		i => Console.WriteLine(i.Url),
		_ => { });

	markers.Push(marker);

	await marker.AddListener<MouseEvent>("click", async e =>
	{
		var markerLabel = await marker.GetLabel();
		_events.Add("click on " + markerLabel);
		StateHasChanged();

		await e.Stop();
	});
}
```

**Comment by Begic** [comment]
There are no errors in the console. And the image is under 1KB.

When i try it with the beachflag it works. But if i change the beachflag with the custom marker does that come.
         

```
Icon = new Icon
            {
                Url = "https://developers.google.com/maps/documentation/javascript/examples/full/images/test12345thisisnotworking.png"
            }
```

![image](https://user-images.githubusercontent.com/67366126/85531936-83c96500-b60f-11ea-964f-2d09a150abb1.png)

**Comment by valentasm1** [comment]
Could you try to save beach flag to localhost and use it from there?
Just to prove point that it isnt about size

**Comment by Begic** [comment]
of corse

            Icon = new Icon
            {
                Url = "https://localhost:44329/img/icons/beachflag.png"
            }

![image](https://user-images.githubusercontent.com/67366126/85538221-f852d280-b614-11ea-8b47-81c9dbbd9c4e.png)

**Comment by valentasm1** [comment]
When i think more it think it is that you pass url which google access and downloads. Since it is on localhost it dont have access.
You could use Symbol which is vector shape or put icon on public url.

**Comment by Begic** [comment]
I found the problem it is between the chair and the monitor. I made a mistake with the path now it works!
Thank you for your support. 
And sry for wasting your time. :)
