### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ozanyasindogan** [rungwiroon/BlazorGoogleMaps#47]
Hi!

Do you have any other documentation than the wiki page on how to use your api?
I have geolocations (lat, long) and I want to draw directions with them instead of
the location name indicated in your sample. I noticed DirectionsGeocodedWaypoint
class but it doesn't have a place to put lat, long data which are probably converted
to PlaceID somehow. I wanted to check if you have any doc explaining how it's done
before diving deep into your code.

Thanks,

Ozan.

**Comment by valentasm1** [comment]
No i dont. You could try playing around with server side samples.
I have feeling that this functionality doenst exist.
@cyberyaga could you check if it possible to provide locations instead name for Routes?
@cyberyaga made pull request for this functionality so maybe he know more.

**Comment by ozanyasindogan** [comment]
Thank you. Looking at the directions Api's documentation, looks like this is possible:

https://developers.google.com/maps/documentation/directions/intro

> waypoints — Specifies an array of intermediate locations to include along the route between the origin and destination points as pass through or stopover locations. Waypoints alter a route by directing it through the specified location(s). The API supports waypoints for these travel modes: driving, walking and bicycling; not transit. You can specify waypoints using the following values:
> Latitude/longitude coordinates (lat/lng): an explicit value pair. (-34.92788%2C138.60008 comma, no space)
> Place ID: The unique value specific to a location. This value is only available only if the request includes an API key or Google Maps Platform Premium Plan client ID (ChIJGwVKWe5w44kRcr4b9E25-Go.
> Address string (Charlestown, Boston,MA)
> Encoded polyline that can be specified by a set of any of the above. (enc:lexeF{~wsZejrPjtye@:)
> For examples and more information on waypoints, see the guide to waypoints below.

I guess this is not covered yet in your api?

Ex:
https://maps.googleapis.com/maps/api/directions/json?
origin=sydney,au&destination=perth,au
&waypoints=via:-37.81223%2C144.96254%7Cvia:-34.92788%2C138.60008
&key=YOUR_API_KEY

**Comment by valentasm1** [comment]
I couldnt say if you are right. If you say so probably you are right. Maybe need some class or some json atributes. Implement new features is quite easy if you know exactly how missing objects looks like.
Would be wonderfull if you could make pull request.

**Comment by ozanyasindogan** [comment]
I just changed it to LatLngLiteral and it's working fine, nothing else needed.

`waypoints.Add(new DirectionsWaypoint()
                {
                    Location = new LatLngLiteral((double)LoadingPlaces[i].GeoData.Longitude,
                        (double)LoadingPlaces[i].GeoData.Latitude),
                    Stopover = true
                });`
