### ISSUE TITLE
Not properly issues, only few suggestions

### ISSUE THREAD

**Issue by RobertoMilani** [rungwiroon/BlazorGoogleMaps#49]
First of all, great works!

**First suggestion:**

Add GUID available to Marker object:
I simply modified in my local GIT Marker class, introducing:

```
public class Marker : IDisposable, IJsObjectRef
    {
        private readonly JsObjectRef _jsObjectRef;

        public Guid Guid => _jsObjectRef.Guid;

```

That allows in Blazor things as:

```
await marker.AddListener("click", async () =>
        {
            CityName = null;
            StopId = null;
            StateHasChanged();

            await JSRuntime.InvokeVoidAsync("openModal", new
            {
                Map = gtfsMap.InteropObject.Guid,
                Marker = marker.Guid
            });

            CityName = Id;
            StopId = Stop.Id;
            StateHasChanged();
        });
```

And JS side things as:

```
function openModal(params) {
    var map = window._blazorGoogleMapsObjects[params.map];
    var marker = window._blazorGoogleMapsObjects[params.marker];

    if (map.getCenter() != marker.getPosition()) {
        map.setCenter(marker.getPosition());
        new google.maps.event.trigger(map, 'dragend');
    }

    $('#markerModal').modal({
        backdrop: 'static',
        keyboard: false
    })

    $('#markerModal').modal('show');
}
```

...and yes... I've implemented a "open a Boostrap Modal Popup instead a InfoWindow object on OnClick event for a marker".
(just below I'll explain why...)

**Second suggestion:**

Before using a Bootstrap Modal Popup I've encountered some issue about set content of a InfoWindow: if it set from Javascript side (exposing InfoWindow GUID too as done for Marker), all was fine, but when set by Blazor code I discovered  some:

```return item.replace(/['"]+/g, '');```

That cause things like:

```<div class="class1 class2">...</div>```

were assigned runtime to InfoWindow content as: 

```<div class=class1 class2></div>```

and interpreted by browser as:

```<div class="class1" class2=""></div>```

with consequently undesiderable appearance effects.

**Third suggestion:**

Globally, library seems to be strong coded, but I feel the shortage of some things, as possibility to create an array of Marker passing an array of MarkerOptions that allows a significant speed up when managing some thousands of markers inside a map (my test case GTFS info for city of Rome, Italy), although I take care to show only markers inside bounds and hide just markers just gone outside bounds and limiting zoom level from 15 to more to show markers.
Pre-creating markers at first page load will allow no needs to marker creations when user moves inside map (dragging, zooming) -> at the moment it takes about 12 seconds but with multiple markers creation (single JSinterobject call) I believe it can be significant faster. 
So, it will be very great can apply to the "behind the scenes" object that contains markers somethings as "SetVisibleMultiple" passing it an array of Marker GUID and a boolean variable regarding visibility to be set instead of doing that inside a loop iterating on markers to be shown or hide involving for for each iteration a JSInterop call.

That's my ideas :)

**Comment by valentasm1** [comment]
I could implement first suggestion. Some classes have this some dont. 
For second and third you need to make pull request. You could always extend functionality in your code, but if you implement nice way in current library i am free to merge.

**Comment by RobertoMilani** [comment]
Thanks for your reply!
Sure!
I can try to write the code for the pull request, sure!
I'll divide in different commits (based on topics / scope) to simplify merge operations.

**Comment by valentasm1** [comment]
My suggestion if/when you write popup changes please keep it css framework agnostic.

**Comment by RobertoMilani** [comment]
I'd like to share an approach regarding my 1st post - 3rd suggestion -> it can be avoid using an approach like:

```
    private async Task<Marker> CreateStopMarkerAsync(GTFSStop Stop, bool visible)
    {
        Marker marker = await Marker.CreateAsync(gtfsMap.JsRuntime, new MarkerOptions()
        {
            Position = new LatLngLiteral(Stop.Longitude, Stop.Latitude),
            Map = gtfsMap.InteropObject,
            Title = Stop.Code,
            Icon = "/images/stop.png",
            Visible = visible
        });

        await marker.AddListener("click", async () =>
        {
            CityName = null;
            StopId = null;
            await base.InvokeAsync(StateHasChanged);

            await JSRuntime.InvokeVoidAsync("openModal", new
            {
                Map = gtfsMap.InteropObject.Guid,
                Marker = marker.Guid
            });

            CityName = Id;
            StopId = Stop.Id;
            await base.InvokeAsync(StateHasChanged);
        });

        return marker;
    }
```

and:

```
                   await MarkersToAdd.ParallelForEachAsync<string>
                    (
                        async Key =>
                        {
                            if (StopMarkers[Key] == null)
                            {
                                GTFSStop Stop = gtfsService.Stops[Id][Key];
                                StopMarkers[Key] = await CreateStopMarkerAsync(Stop, true);
                            }
                            else
                            {
                                await StopMarkers[Key].SetVisible(true);
                            }
                        },
                        maxDegreeOfParallelism: 16 * Environment.ProcessorCount
                    );
```

Or, in other words, implementing an async method to create Marker object and put the "huge quantity" of markers crearion inside a ParallelForEachAsync construct (gently provided by Dasync.Collections namespace) configured with an opportune "maxDegreeOfParallelism" option (16 * Environment.ProcessorCount is good enougth for my Application Server with 8 cores i7-3630QM @ 2.40GHz).

Hope this can help someone when a big quantity of markers needs to be managed on map :)

**Comment by valentasm1** [comment]
Thank you for you code. I just dont understandand what should i do. IMO i think it shouldnt be inside library. If you put effort to make PR then i could try to add. It is very specific case and solution maybe not for everyone.

**Comment by RobertoMilani** [comment]
No, no, it's not for library!
It's an example - usable inside a razor page - that allow quite rapid creation of multiple markers.
So, I'm trying to implement a CreateMultipleAsync paradigm for Marker, but in the meanwhile my previous post code can be a "good enougth" solution to speed up multiple marker creation.
My post was only a "dev" oriented usage suggestion of the library :)

**Comment by valentasm1** [comment]
Oh. I thought you post comment like asking for code review or smth. One day when i wont be lazy and will have free time i will add this to wiki :). I mean code

**Comment by RobertoMilani** [comment]
Oh, now I'm on the right direction to implement an extension class named **MarkerList** usable to manage a big quantity of markers on Google Map.
I've yet created with success the **CreateAsync** functionality, but, first I proceed with my work, I need to an open survey with library maintainers and developers too -> I'll group my open points in three parts (only maintainers, only developers, both of them):

**- For maintainers:**

Due to implementation needs (and to grant code maneageability moving deep versus .net framework native Javascript invocation) after several hours of "meditation" I decided to use for **new** JsObjectRef class method **CreateMultipleAsync** - instead of a params object[] args a **Dictionary<string, object>** args parameter, that I can evolve in an array of Dictionary<string, object> if needed.
Reason of that is exposed below (in the "For both section").
**Is it an acceptable implementation solution?**

**- For developers:**

MarkerList class can be used with a unique call of CreateMultipleAsync => put all markers on map but show only wich we decided to show (inside visible bounds, depending zoom factor and so on).
However I tested locally more instances of markerList class and several lists of markers creation adopting marker sets creation only when needed, but this requires to insert inside our code some more things: a list of all possible markers key, a list of yet created markers, a list of visibile markers, and so on.
Obviously MarkerList class will not implement any external needs regarding high level behaviours as exposing subsets of visible markers and so on.
But...
If that I'm proposing is good enought for maintaner and developers...
I'd like to continue MarkerList implementation, exposing "Get" method as:
```
public async Task<Dictionary<string, Animation>> GetAnimations()
```
Where Key is the same Key of Markers member and Value the corresponding Animation properties of each marker
And the equivalent "Set":
```
public Task SetAnimations(Dictionary<string, Animation> animations)
```
Same things for Opacity, Map, Label, Icon, Draggable, Visible... and other Marker properties.

So... we can create "n" (tested thousands) markers not visible, use the ```OnAfterInit``` event handler to associate our Map object some listener (for istance "zoom_changed", "dragend") than we can implement as below:

- if zoom < 15 => hide all markers
- if zoom >= 15 => show only markers inside map bounds

and our **MarkerList** object will allow that, using:
```public Task<Dictionary<string, LatLngLiteral>> GetPositions()```

Than filtering for markers inside map bounds and building a:
```Dictionary<string, bool> visibles```
to be passed to:
```public Task SetVisibles(Dictionary<string, bool> visibles)```
to set desired markers visibilities.
**Is good enought?**

**- For both:**

Google Maps implementation of Marker does not exhibit any arbitrary field to univoque identitify Marker object (although internally to library we have now a Guid property) so, if a list of markers needs to be binded to an external key (a place id, a bus stop id or other things) when we create a List of marker there are no way to keep toghether with external key. Javascript side is possible to add aribitrary parameter to an object, but .net side it will be a not simple problem to manage, so I decided to implement Marker list class, CreateAsync method having as second parameter: ```Dictionary<string, MarkerOptions> opts``` where string is in my opinion the most versatile key type, so I can have for instance a List of BusStop and I can create the markers as:
```
MarkerList markerList = await MarkerList.CreateAsync
(
	gtfsMap.JsRuntime,
	Stops.ToDictionary(s => s.Id, s => new MarkerOptions
	{
		Position = new LatLngLiteral(s.Longitude, s.Latitude),
		Map = gtfsMap.InteropObject,
		Title = s.Code,
		Icon = "/images/stop.png",
		Visible = true
	})
);
```
quite simple :)
Then... what markerList contains?
I obviously think the accessible member of markerList is a:
```public readonly Dictionary<string, Marker> Markers```
where Key is (in my case) StopId and Value the corresponding Marker object.
**In your opinion, is this choice of implementation valid for the most possible uses of the MarkerList class?**

**Comment by RobertoMilani** [comment]
I'd like to add another comment... 
Well.. yes! It works! And it's very fast too! :)
I've tried to implement, razor side:

```
if (MarkersToAdd.Count > 0)
{
    await markerList.SetVisibles(MarkersToAdd.ToDictionary(e => e, e => true));
}

if (MarkersToDelete.Count > 0)
{
    await markerList.SetVisibles(MarkersToDelete.ToDictionary(e => e, e => false));
}
```

And inside new **MarkerList** class (candidate version):

```
public Task SetVisibles(Dictionary<string, bool> visibles)
{
       Dictionary<string, Guid> internalMapping = visibles.ToDictionary(e => e.Key, e => Markers[e.Key].Guid);
        Dictionary<Guid, object> dictArgs = visibles.ToDictionary(e => Markers[e.Key].Guid, e => (object)e.Value);

       return _jsObjectRef.InvokeMultipleAsync(
           "setVisible",
           dictArgs);
}
```

Then, inside **JsObjectRefClass** (candidate version):

```
public Task InvokeMultipleAsync(string functionName, Dictionary<Guid, object> dictArgs)
{
        return _jsRuntime.MyInvokeAsync(
            "googleMapsObjectManager.invokeMultiple",
            new object[] { dictArgs.Select(e => e.Key.ToString()).ToList(), functionName }
                .Concat(dictArgs.Values).ToArray()
        );
}
```

And finally in objectManager.js script (to be extended):

```
invokeMultiple: async function (args) {
        let args2 = args.slice(2).map(arg => tryParseJson(arg));

        var result = [];
        let objs = [];
        let guids = JSON.parse(args[0]);

        for (var i = 0; i < guids.length; i++) {
            objs[i] = window._blazorGoogleMapsObjects[guids[i]];
            let args3 = [];
            args3.push(args2[i]);

            try {
                result = objs[i][args[1]](...args3);
            } catch (e) {
                console.log(e);
            }
        }                        

        return result;
}
```

Putting all toghether moving inside maps and making markers visible or not if zoom is >= 15 and if markers are inside or not map bounds, is very fast (about 100ms) although I have created on map about 9.5k markers (transit stops for city of Rome).

Seems me the right way, isn't it?

_I'll appreciate a lot, either comments about code implementation approach, or high level developers usability considerations._

**Comment by valentasm1** [comment]
Duude. Relax. You are taking everything way to serious. I appreciate your effort, but just make Pull Request way you think it is good. If i wont see anything serious (mostly will not) then release i'll it. If someone will create issue with complain then we fix it. 
It is not that we have plenty of time to discuss, analyse the best solutions. Time=Money and nobody pays money to spend time one this lib.

**Comment by RobertoMilani** [comment]
Ooook! I'll do! :)
I'm pretty sure of my implementation regards the fact it works (I'm testing it on a quite "extreme" case like lot of static transit stop markers and lot of bus markers in movement).
My doublts was only regarding "change of parameters type" in new methods respect the original one and regarding final dev users whole usability.
I want implement most versatile functionalities, or - in other words - try to "empty my mind from what I need" and try to "keep in mind what can be useful to most users" ;)
Good, then!
I proceed and I'll submit in few days the pull request.

A last thing:
After hopeful pull request integration, and after I clean my personal blazor code from any "personal data and reference", would you I prepare a new "blazor demo" to be sumbitted inside "examples" section to show how use "most of" new functionalities?

**Comment by valentasm1** [comment]
It would be good to get some samples of functionality since you already will knew how it works. No need to have many data, just several point are ok.

**Comment by valentasm1** [comment]
Closing.
