### ISSUE TITLE
Marker Color

### ISSUE THREAD

**Issue by yiyoMX** [rungwiroon/BlazorGoogleMaps#53]
Is it possible to set the default marker color?

**Comment by valentasm1** [comment]
I think if you wont provide market then default is loaded. You could provide marker color by google default marker collection. Basically it is image but google have some presetuped. If it wont help you could create you own images.

You could try to play with similar exaples.
[javascript-change-google-map-marker-color](https://stackoverflow.com/questions/11064081/javascript-change-google-map-marker-color)

**Comment by yiyoMX** [comment]
Thanks fo the fast response, that worked, I was asking because on the native api, you can specify the color by setting color property, and the default Icon changes to the specified color.
