### ISSUE TITLE
Adding listeners for infowindows

### ISSUE THREAD

**Issue by Essum13** [rungwiroon/BlazorGoogleMaps#54]
Hello, I´m looking for a way for styling my infowindows and need some help. My first thought was to create listeners for my infowindows and then later style it on the "domready" event. Like in this example: http://en.marnoto.com/2014/09/5-formas-de-personalizar-infowindow.html. I tried to figure out if it´s possible here with this packages but didn´t find the solution. 

Is it possible to create listeners for my infowindows? If not, maybe you know a better way for styling the "complete infowindow" like in the example i linked above.

Thanks for your time in advance.

**Comment by valentasm1** [comment]
Could you check this guy post. I think he has implemented your requirements. Let me know if it helped.
https://github.com/rungwiroon/BlazorGoogleMaps/issues/49

**Comment by Essum13** [comment]
I did check all the previously Issues before. Maybe one option for me would be to instead of opening a infowindow, opening a modal and then style that.

Do you understand what i wanted to achive in the first place? In my perfect world i wanted to create my marker with my infowindow, adding a listener for that infowindow and whenever it´s "domready", apply some styling. Like this:

```
var marker = await Marker.CreateAsync(map.JsRuntime, new MarkerOptions()
                    {
                        Position = new LatLngLiteral { Lat = klev.Latitude, Lng = klev.Longitude },
                        Map = map.InteropObject,
                        Icon = ""
                    });

var infoWindowContent = "infowindowcontent";

 await marker.AddListener("click", async () =>
                    {
                        infoWindow = await InfoWindow.CreateAsync(map.JsRuntime);

                        await infoWindow.SetContent(infoWindowContent);
                        await infoWindow.SetPosition(await marker.GetPosition());
                        await infoWindow.Open(map.InteropObject);
                    });

/// this is what i would like to add:

google.maps.event.addListener(infowindow, 'domready', function() {

   do stuff here.
});

```
Another thing i wonder which falls into the same category. Is it possible to add domListener to the map div? Didn´t find anything on this either. It´s done here in this example: https://developers.google.com/maps/documentation/javascript/examples/event-domListener

**Comment by RobertoMilani** [comment]
@Essum13 
I found this:
https://stackoverflow.com/questions/5416160/listening-for-the-domready-event-for-google-maps-infowindow-class

And this:
https://developers.google.com/maps/documentation/javascript/reference/info-window

Where is explained that:
![image](https://user-images.githubusercontent.com/46413967/87932321-a07c7f80-ca8b-11ea-96de-992911a2cce2.png)

So, it is implemented in Google Maps API, yes!

Now, you are right: our implementation of InfoWindow leaks a:

```public async Task<MapEventListener> AddListener(string eventName, Action handler)```

implementation, so if @valentasm1 believe can be usefull, I can provide the update of InfoWindow class coherent with the same method inside Marker class (seems me underlying objects are already resilient to it.

**Comment by valentasm1** [comment]
@RobertoMilani np. You could do it. This functionality wont break all system. Just on extra method. Thank you so much.

**Comment by RobertoMilani** [comment]
@valentasm1 Ok, I'll do just after my "work time" ;)

@Essum13 if you want, however, due the "static behaviour" on InfoWindow (in which are injected static HTML), in a personal project I successfull mapped a "click" event on marker that cause the open of a Bootstrap modal with dynamic content (inside modal I put a custom Blazor component initialized by parameters that render a specific content of which marker Guid is only one on them (parameters)). I can share example code fragments if you like / need.
Anyway InfoWindow needs a AddListener method, I only suggest you to think "wider" -> a "static" content may be really your "target" or not (please, do not interpret my words as opinionated, it is not my intention :) )

**Comment by valentasm1** [comment]
https://github.com/rungwiroon/BlazorGoogleMaps/pull/55

**Comment by valentasm1** [comment]
Could i close issue?

**Comment by Essum13** [comment]
Thanks, your implementation solved my problems. You can close the issue!
