### ISSUE TITLE
Remove markers and polylines from map

### ISSUE THREAD

**Issue by yiyoMX** [rungwiroon/BlazorGoogleMaps#57]
Hi, Ive been trying different ways of removing a list of markers and a list of polylines but if I clear the List objects the maps retains all the info, whats the right way? Using blazor server side.
Thanks.

**Comment by valentasm1** [comment]
Could you provide sample of code?

**Comment by yiyoMX** [comment]
<GoogleMap @ref="@map1" Id="map1" Options="@mapOptions"></GoogleMap>
@code {
 private GoogleMap map1;
    private MapOptions mapOptions;
    private List<Marker> markers;
    private List<String> _events = new List<String>();
    private LatLngBounds bounds;
    private List<Polyline> polylines = new List<Polyline>();
    private Polyline polyline;

async Task AddMarkers(List<records> records)
{
for (int i = 0; i < records.Count; i++)
        {
                var markerPosition = new LatLngLiteral { Lat = TelematicsRecords[i].Latitude, Lng = TelematicsRecords[i].Longitude };
                var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
                {
                    Position = markerPosition,
                    Map = map1.InteropObject,
                    Label = $"{i}",
                    ZIndex = records.Count,
                    Visible = true,
                    Icon = "http://maps.google.com/mapfiles/ms/icons/purple-dot.png"
                });
                markers.Add(marker);
        }

}


This adds the markers, how do I remove them? I tried setting markers = null, and doesn't work.

**Comment by valentasm1** [comment]
You should track marker which you want to remove. You could use marker Guid propert.
In your example to remove first marker you could do
```
var firstMarker = markers.FirstOrDefault();
await firstMarker.SetMap(null);

```

**Comment by valentasm1** [comment]
You could check example 
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarker.razor.cs

**Comment by valentasm1** [comment]
Closing.

**Comment by SuganthB2002** [comment]
> polyline

by the way how you initialized the polylines? im struggling with that

**Comment by valentasm1** [comment]
There is sample. Does it help?
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapPolyline.razor
