### ISSUE TITLE
Add markers range

### ISSUE THREAD

**Issue by yiyoMX** [rungwiroon/BlazorGoogleMaps#58]
Is it possible to add a whole list of coordinates at once?
Right now I have a loop that goes through each element of a collection with coordinates and adding them to the markers list, which results in seeing each marker added one by one on the map, this also happens when I remove the markers from the map, is it possible to add them all at once?

**Comment by valentasm1** [comment]
There was one pull request with exact functionality.
Check Wiki page if it makes sense to you. It could have bugs but you should get main point. You need to use new Class MarkerList
https://github.com/rungwiroon/BlazorGoogleMaps/wiki/MarkerList-for-multi-markets-manipulation

**Comment by yiyoMX** [comment]
This pointed me in the right direction! Thanks.
