### ISSUE TITLE
Impossible to add Custom Legends. Controls always null

### ISSUE THREAD

**Issue by Enritski** [rungwiroon/BlazorGoogleMaps#60]
I am trying to add a custom legend to my map, as per the tutorial here : https://developers.google.com/maps/documentation/javascript/adding-a-legend.

I see, though, that the InteropObject.Controls dictionary is always null so I can't do something like 
`
_map1.InteropObject.Controls.Add(ControlPosition.BottomRight, new List<ElementReference> {_legend});
`
Am I going about this the wrong way, or is the Controls dictionary not implemented yet?

**Comment by valentasm1** [comment]
Good catch.
It wont work.  I think it would be easier to add extra methods to add and remove controls. Also some simple js methods to access map controls.
I could do it in two weeks. You could try to make pull request

**Comment by valentasm1** [comment]
I released that I need it for my personal project too. For sure i am gonna implement by myself in best case in two coming week (like i said), or worst case month. Maybe even sooner, which depends on weather outside.

**Comment by Enritski** [comment]
That's great, @valentasm1 !  I'm not going to have time to look at this for a while, but will do as soon as I get the chance.  I expect you will have it implemented long before then.

Thanks again!

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/0.7.1

**Comment by valentasm1** [comment]
```
public partial class MapLegendPage
    {
        private GoogleMap map1;

        private MapOptions mapOptions;

        [Inject] private IJSRuntime jsRuntime { get; set; }

        protected ElementReference legendReference { get; set; }

        protected override void OnInitialized()
        {
            mapOptions = new MapOptions()
            {
                Zoom = 13,
                Center = new LatLngLiteral()
                {
                    Lat = 13.505892,
                    Lng = 100.8162
                },
                MapTypeId = MapTypeId.Roadmap
            };
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await jsRuntime.InvokeAsync<object>("initMapLegend");
            }
        }

        private async Task AfterMapInit()
        {
            await map1.InteropObject.AddControl(ControlPosition.TopLeft, legendReference);
        }
    

> }

```

```
@page "/map-legend"

<h1>Google Map Legend</h1>

<GoogleMap @ref="@map1" Id="map1" Options="@mapOptions" OnAfterInit="@AfterMapInit"></GoogleMap>

<div id="legend" @ref="@legendReference" style="visibility: hidden"><h3>Legend</h3></div>

<style>
    html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        width: 100%;
    }

    #map {
        height: 400px;
        width: 100%;
    }

    #legend {
        font-family: Arial, sans-serif;
        background: #fff;
        padding: 10px;
        margin: 10px;
        border: 3px solid #000;
    }

        #legend h3 {
            margin-top: 0;
        }

        #legend img {
            vertical-align: middle;
        }
</style>
```

**Comment by valentasm1** [comment]
```
function initMapLegend() {
    var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
    var icons = {
        parking: {
            name: 'Parking',
            icon: iconBase + 'parking_lot_maps.png'
        },
        library: {
            name: 'Library',
            icon: iconBase + 'library_maps.png'
        },
        info: {
            name: 'Info',
            icon: iconBase + 'info-i_maps.png'
        }
    };

    var legend = document.getElementById('legend');
    for (var key in icons) {
        var type = icons[key];
        var name = type.name;
        var icon = type.icon;
        var div = document.createElement('div');
        div.innerHTML = '<img src="' + icon + '"> ' + name;
        legend.appendChild(div);
    }
}
```

**Comment by valentasm1** [comment]
Currently you have ability to add legend only. I havent tested other scenarios. Also maybe it is not the best implementation.
When you have time please check and let me know with your ideas.
If not i will close in several weeks

**Comment by Enritski** [comment]
Apologies - have been completely tied up on other work, so haven't had the chance to review this yet.

Thanks for the quick turnaround!  Your support for this package is great!!

**Comment by Enritski** [comment]
I finally got a chance to look at this today.  The updated version seems to work very well!  I added custom legends, a custom search control and a few other controls and all was fine.

Once again, many thanks for the great support.
