### ISSUE TITLE
[Disscussion] Why not to use BrowserInterop JsObjectRef ?

### ISSUE THREAD

**Issue by redradist** [rungwiroon/BlazorGoogleMaps#61]
Hi,

I have found your library and it is very exciting !!
But one thing I noticed among all other Blazor wrappers that each wrapper creates its own JsObjectRef and Reviver ...

Why not to use https://github.com/RemiBou/BrowserInterop reviver ? One advantage of using only one reviver and JsObjectRef is high interoperability between different libraries

Unfortunately Microsoft does not provide standard way of working with JsObjectRef, but we as community can choose on JsObjectRef implementation and stick to it

I have already using this approach in https://github.com/redradist/BlazorGooglePay ;)

Anyway it is discussion ;)

**Comment by valentasm1** [comment]
First of all. It looks more like promotion not suggestion. 
Second. Rewrite all current code base to use yours js interop, sounds way to crazy idea. 
Third i am not sure if library is very usefull in our case. We dont have many broswer interactions. We touch google maps api which results broswers itself.

I am not pro so i could be wrong. If you are wiling you could make pull request.
Despite all library looks cool and could save a lot of time migrating old solutions to blazor.

**Comment by redradist** [comment]
> 
> 
> First of all. It looks more like promotion not suggestion.
> Second. Rewrite all current code base to use yours js interop, sounds way to crazy idea.
> Third i am not sure if library is very usefull in our case. We dont have many broswer interactions. We touch google maps api which results broswers itself.
> 
> I am not pro so i could be wrong. If you are wiling you could make pull request.
> Despite all library looks cool and could save a lot of time migrating old solutions to blazor.

@valentasm1 It is even not my Js interop ))))) I just like it because it provides as well Brower Interop

I just concerned about compatibilities between different libraries

When I was thinking about developing my own BlazorGooglePay wrapper, I also wanted create custom Js interop, but then I have investigated and figured out that all other libraries created already lots of different interops that even not compatible each other ... and I decided to use one that is most general like BrowserInterop because it not only provides bindings, but also provides interaction with Browser ...

Yeah, maybe it is promotion, but I just want compatable solution across libraries )))

**Comment by redradist** [comment]
@valentasm1 Also I noticed that you as all other libraries enforce user to include script tag in html ...

Take a look at https://github.com/redradist/BlazorDependencies for simplifying dependency management

**Comment by valentasm1** [comment]
Thank you for your suggestions.
