### ISSUE TITLE
Open infowindow from code

### ISSUE THREAD

**Issue by yiyoMX** [rungwiroon/BlazorGoogleMaps#62]
Hi, I have a map with several markers, if you click the marker an infowindow opens and displays the data, is there a way to also open the infowindows from code? For example, if I have a grid with a datasource of the markers list, I would want to click on the record and then open the infowindow on the map.
Thanks in advance.

**Comment by valentasm1** [comment]
Here is example of info window from Demo.
As you see info windows doesnt have any direct relation to marker. It just uses marker position to know where to showup on map. If you make await infoWindow.Open(map1.InteropObject); then it will open anytime when you want.
I couldnt provide exact solution but you get the point: create info window, set position and open it.

```
private async Task AddMarker()
    {
        var position = await map1.InteropObject.GetCenter();

        var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
        {
            Position = position,
            Map = map1.InteropObject,
            Label = $"Test {markerCount}"
        });

        var infoWindow = await InfoWindow.CreateAsync(map1.JsRuntime, new InfoWindowOptions()
        {
            Position = new LatLngLiteral()
            {
                Lat = 13.505892,
                Lng = 100.8162
            },
            //Content = "Test"
        });

        var infoWindowContent = $"Test {markerCount}";

        await marker.AddListener("click", async () =>
        {
            await infoWindow.SetContent(infoWindowContent);
            await infoWindow.SetPosition(position);
            await infoWindow.Open(map1.InteropObject);
        });

        markerCount++;
    }
```

**Comment by yiyoMX** [comment]
Solved thanks to your explanation!

**Comment by valentasm1** [comment]
And one more example where guy implemented bootstrap info window. Just go through issue
https://github.com/rungwiroon/BlazorGoogleMaps/issues/49
