### ISSUE TITLE
Think i can´t access the map object.

### ISSUE THREAD

**Issue by Essum13** [rungwiroon/BlazorGoogleMaps#66]
Hey, got some issues with accessing the map object i think. Maybe it´s just me who does this wrong, I´m pretty new with Blazor aswell. I´ll try to explain my problem. 

I got a client-side Blazor project where i split up my c# and razor. My baseclass looks like this:

```
    public class MapBase : ComponentBase
    {
        [Inject]
        protected HttpClient Http { get; set; }
        [Inject]
        public IJSRuntime JSRuntime { get; set; }
        public GoogleMap map;
        public Location activeLocation = new Location();
        public MapOptions mapOptions;
        public List<Location> locations = new List<Location>();
        private Stack<Marker> markers = new Stack<Marker>();
        private InfoWindow infoWindow = null;

        protected override async Task OnInitializedAsync()
        {
            mapOptions = new MapOptions()
            {
                Zoom = 12,
                Center = new LatLngLiteral()
                {
                    Lat = 58.346644,
                    Lng = 12.455974
                },
                MapTypeId = MapTypeId.Sattellite
            };

           // Here im also populating my list "locations" from a async httpcall.
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (!firstRender)
            {
                if (map == null) return;

                foreach (var location in locations)
                {
                    var marker = await Marker.CreateAsync(map.JsRuntime, new MarkerOptions()
                    {
                        Position = new LatLngLiteral { Lat = klev.Latitude, Lng = klev.Longitude },
                        Map = map.InteropObject,
                        Icon = "/images/Scout.png"
                    });

                    markers.Push(marker);

                    // Creating my infoWindow here
                    
                    await marker.AddListener("click", async () =>
                    {
                        if (infoWindow != null)
                        {
                            await infoWindow.Close();
                        }

                        infoWindow = await InfoWindow.CreateAsync(map.JsRuntime);
                        setActiveLocation(location);

                        await infoWindow.SetContent(infoWindowContent);
                        await infoWindow.SetPosition(await marker.GetPosition());
                        await infoWindow.Open(map.InteropObject);
                    });
                }

                await map.InteropObject.AddListener("click", async () =>
                {
                    if (infoWindow != null)
                    {
                        await infoWindow.Close();
                    }
                });
            }
        }

        public void onSelectFilter()
        {
            Console.WriteLine(markers.Count());
        }

        public void setActiveLocation(Location location)
        {
            activeLocation = location;
            StateHasChanged();
        }
    }
```

My MapComponent who inherrit the MapBase class looks like this:

```
@page "/map"

@using GoogleMapsComponents

@inherits MapBase

<SearchComponent/>
<GoogleMap @ref="@map" Id="map" Options="@mapOptions"></GoogleMap>
```
Everything works perfectly. I have my map with markers, working click functions who opens and closes infowindows. Now to my problem. I have a third component who also inherrit the MapBase Component that is kinda simple and looks like this:

```
@inherits MapBase

    <div id="searchComponent">
        <select id="mySelect" @onchange="onSelectFilter" class="form-control">
            <option />
            @foreach (var location in locations)
            {
                <option value="@location.Name">@location.Name</option>
            }
        </select>
    </div>

```

This third component calls the function onSelectFilter who is in my baseclass. It simply writes down the marker count. I get the marker count to be 0. I also tried to do other thinks with my map and markers but i can´t access them. Where am i doing wrong?

**Comment by valentasm1** [comment]
First of all you should use map event to find when map is loaded. Check example in readme(front page)
```
OnAfterInit="@(async () => await OnAfterInitAsync())"
```

Second this is very bad. Component is redrawn each time any value changes and it will be trigered each time. 
```
if (!firstRender)
```

Also you should try debug with edge application and see if any markers is added to markers.
In my opinion you should change and OnAfterInit event and it should work

**Comment by Essum13** [comment]
@valentasm1 m1, thank you for the fast response. I implemented your suggestions but i still got the same problem. 

Since i have the markers written out on the map, shouldnt they exist?
I did a Console.WriteLine(map) in the OnAfterInitAsync() method and in the method onFilterSelected. In the OnAfterInitAsync() method i find the object and get "GoogleMapsComponents.GoogleMap" written out and in the onFilterSelected method it writes out nothing. 

It seems like i still have the same problem accessing the map object..

**Comment by valentasm1** [comment]
If i understand correctly it is not issue with accessing map. There is issue with Stack<Marker> markers .
I think you should create github or zip solution that i could reproduce issue. You could make just part of not working. No need all solution. 
Again i think this is not map issue, but something with lifecycle or business logic. Of course i could be wrong.

**Comment by Essum13** [comment]
@valentasm1, I created a repo with the same problem: https://github.com/Essum13/GoogleMapsBlazorIssues.git
Wrote some comments inside the BaseClass.

(I removed valid google maps api key).

**Comment by valentasm1** [comment]
Thank you for you time preparing github. Now i get it. 
Dont take anything personally. You inheritance is strange. I think i mixed up functionality.  If two components inherit same base it doesnt mean they share same instance. 
SearchComponent < MapBase
AND
Map < MapBase

You see. If you draw smth on map.razor then SearchComponent.razor < Map base doesnt know anything about it.
My suggestion is to create MyMapComponent where you bind Locations via [Parameter] property from parent component. Parent component have all info about locations and it changes then child will update automatically. Then on parent if you change Select control, then you already know info about locations.

My suggestion read this documentations. Especial part about child components which is relavant to you. It a bit hard to grasp so probably you will need to read several times and compare with other recourses.
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-3.1

**Comment by valentasm1** [comment]
Closing

**Comment by Essum13** [comment]
@valentasm1, ahhh that makes sense haha! Thank you for your time! I will solve my problem now.
