### ISSUE TITLE
Plotting Multiple Marker Takes long Time while deployed in server

### ISSUE THREAD

**Issue by Sathish9222** [rungwiroon/BlazorGoogleMaps#67]
Hi ,
When marking multiple markers takes long time while it is deployed on server. It works fine while debugging . Any help would be appreciated.

**Comment by valentasm1** [comment]
Please fallow rough information about how to work with many markers
https://github.com/rungwiroon/BlazorGoogleMaps/wiki/MarkerList-for-multi-markets-manipulation

**Comment by pmagnus2** [comment]
While I can see the Wiki (thanks) I can not find any documentation on the class "MarkerList". Is it a class that used to be part of BlazorGoogleMaps (if so, then is it still there?) or is it a class we should write ourselves?

**Comment by valentasm1** [comment]
Sorry i dont have enough time to support documentation well. You could check server side example which have many examples

**Comment by pmagnus2** [comment]
Thanks! In the example code it was clear. It was a simple using statement that was needed:
`using GoogleMapsComponents.Maps.Extension;`
