### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by bwjunkie** [rungwiroon/BlazorGoogleMaps#69]
getting two build errors:  ( I downloaded the Zip file of all 3 projects in one solution)
ServerSide
VS Commuity 2019 Version 16.7.5 

MapLegendPage.razor 

Line 1
Cannot implicitly convert type 'Microsoft.AspNetCore.Components.ElementReference' to 'GoogleMapsComponents.GoogleMap'	ServerSideDemo	\BlazorGoogleMaps-master\ServerSideDemo\Pages\MapLegendPage.razor	

Line 5
Cannot convert method group 'AfterMapInit' to non-delegate type 'object'. Did you intend to invoke the method?	ServerSideDemo	C:\Users\joshm\Downloads\BlazorGoogleMaps-master\BlazorGoogleMaps-master\ServerSideDemo\Pages\MapLegendPage.razor	

I probably haven't provided enough info, sorry for that.

**Comment by valentasm1** [comment]
Here is top of component MapLegendPage.razor.
I added two usings which was missed. You could add by yousefl or PULL (update) solution from git

```
@page "/map-legend"
@using GoogleMapsComponents
@using GoogleMapsComponents.Maps

<h1>Google Map Legend</h1>

<GoogleMap @ref="@map1" Id="map1" Options="@mapOptions" OnAfterInit="@AfterMapInit"></GoogleMap>

<div id="legend" @ref="@legendReference" style="visibility: hidden"><h3>Legend</h3></div>


```

**Comment by bwjunkie** [comment]
yes that fixed it 
Thank you
