### ISSUE TITLE
Delete package

### ISSUE THREAD

**Issue by valentasm1** [rungwiroon/BlazorGoogleMaps#72]
Please delete package. I accidently posted my personal when mixed repository url
@rungwiroon 
https://github.com/rungwiroon/BlazorGoogleMaps/packages/471229?version=1.0.0-beta-1

**Comment by rungwiroon** [comment]
@valentasm1 
I tried to follow this [documentation](https://docs.github.com/en/free-pro-team@latest/packages/publishing-and-managing-packages/deleting-a-package#about-public-package-deletion) but couldn't find the "Manage versions" button in dropdown.

**Comment by valentasm1** [comment]
Thank you. I think it could be some bug since i post it via cli. I will write to support.

**Comment by valentasm1** [comment]
Just for your knowleadge. No actions need to take
https://stackoverflow.com/questions/59103177/how-to-delete-remove-unlink-unversion-a-package-from-the-github-package-registry

Package versions of a private can be delete by the maintainer:

Via the Github API, see the answer of @Akif
Via the Github Support
Github will add a way to do this comfortably via the Web App soon. (source: support)
**Package versions of a public repository cannot be deleted by the maintainer, i.e.:**

The Github support needs to be contacted to have a package or version removed.

Workaround: make your repository temporarily private for the deletion:

Attention: This results into loss of stars, etc., see Github Warning!
Repository Settings > Danger Zone > Make private
Follow the instructions by @Akif's answer to delete the package versions
Repository Settings > Danger Zone > Make public
