### ISSUE TITLE
DirectionsRenderer.SetDirections  issues in Blazor Client

### ISSUE THREAD

**Issue by RobertmSI** [rungwiroon/BlazorGoogleMaps#74]
Hi, I am having issues with setting directions in Blazor client.

My component has a map and some autocomplete  inputs for start and end place.
When user enters the data, I call DirectionsRenderer.Route(myDirectionsRequest) to get a route. This works OK.
I was planning to save the route from DirectionRenderer to the database and redraw it when client opens the map again later.
Sadly, this does not seem possible. I get an error in the console saying "Cannot read property 'travelMode' of undefined".

Simplest way to reproduce the issue is to get the DirectionResult from renderer and then refreshing the directions on renderer.
Steps to reproduce:

```
private async Task SaveRoute()
{
       DirectionsResult dr = await dirRenderer.GetDirections(
                                            new DirectionsRequestOptions 
                                            { 
                                                      StripOverviewPath = false, 
                                                      StripLegsSteps=false, 
                                                      StripLegsStepsLatLngs=false, 
                                                      StripLegsStepsPath=false, 
                                                      StripOverviewPolyline=false 
                                             }); //getting full DirectionsResult, works OK, gets the result

        Console.WriteLine("Setting directions to null:");
        await dirRenderer.SetDirections(null); //Crash - Not an object

        Console.WriteLine("Setting directions back to previous:");
        await dirRenderer.SetDirections(dr);   //Crash - Cannot read property 'travelMode' of undefined
}
```

Is this aproach wrong? 

![Error](https://user-images.githubusercontent.com/73839647/98369375-23284b00-2039-11eb-9f08-ce3153f33f5b.jpg)

**Comment by RobertmSI** [comment]
Perhaps it has to do something with my configuration...

I also get similar errors when using autocomplete. 
Only way to get the autocomplete to work is to change the api reference from
https://maps.googleapis.com/maps/api/js?key={MyKey}&v=3 to
https://maps.googleapis.com/maps/api/js?key={MyKey}&v=3&libraries=places

The above issue still persists with both references though.

**Comment by valentasm1** [comment]
Could you try instead 
await dirRenderer.SetDirections(null); //Crash - Not an object
try
await dirRend.SetMap(null);

**Comment by RobertmSI** [comment]
Hi valentasm1, thank you for your reply.
SetMap(null) works OK and does not throw an error.
But other two functions still dont work and I cant set the directions when loading data.

**Comment by valentasm1** [comment]
99% sure that is due incorrect parameter parsing in objectManager.js. You could try to debug it and write your own extensions.
I will try to look at this more carefully this week. I am bit busy.

**Comment by RobertmSI** [comment]
OK, no problem.
For now I am saving the DirectionsResult and on loading construct the DirectionsRequest from saved start and endpoint and waypoints. Then I call dirRenderer.Route(request) to get the route. 
A bit of workaround but it works.
Thank you for your help.

**Comment by valentasm1** [comment]
After some time of investiagation it looks like there is some specific cases in this one
I get error. Either setDirections or creating new renderer with routeresult
```
directions.js:44 Uncaught TypeError: Cannot read property 'travelMode' of undefined
```
There is two ways to solve it. I havent tested either one but looks like it could word.
Make custom init method
https://stackoverflow.com/questions/11159786/api-throwing-an-error-when-calling-directionsrenderer-setoptions-before-receivin
or custom setDirections method
https://github.com/googlemaps/google-maps-services-js/issues/161

**Comment by Curlack** [comment]
In case anyone was wondering, `setDirections` expects a full `DirectionsResult`. This includes a `request` property, which is not part of the result returned by the `Route` method. This is where the API is trying to get the `travelMode` property from.
