### ISSUE TITLE
Adding events for ListableEntityListBase

### ISSUE THREAD

**Issue by turner11** [rungwiroon/BlazorGoogleMaps#76]
This is a follow up to #59.
Now that CircleList is implemented, consider the following scenario:
1. A list of many circles are added to the map (tens of thousands in my case ).
2. A click event is attached to each of the circles (of which typically only few will actually be clicked).

Since #64 item 1 is fast, but attaching the events is still done per item - which is very slow.
I'm thinking of something of the sort of:
```C#
            CircleList circles = await CircleList.CreateAsync(JsRuntime, options);
            Action<Circle> clickAction = (circleInstance) =>
            {
                //The circleInstance was Clicked!
            };

            await circles.AddListener("click", clickAction);
```
Where the instance is passed as an argument to the raised event.

Instead of the current:

```C#
            CircleList circles = await CircleList.CreateAsync(JsRuntime, options);
            foreach (KeyValuePair<string, Circle> pair in circles.BaseListableEntities)
            {
                Circle circle = pair.Value;
                Action clickAction = () =>
                {
                    //I got Clicked!
                };

                await circle.AddListener("click", clickAction);
            }
```

@rungwiroon , If I'll find the time I'll implement & open a PR.  
Is there anything I should be aware of?
Any tips?

**Comment by valentasm1** [comment]
@turner11 no worry. I use principle move fast, break things. Open PR and we will see.

**Comment by valentasm1** [comment]
IMO i think it works with nuget 1.0.1. If i wont get answer in 1 week will close.
