### ISSUE TITLE
Marker animation set and get dont work

### ISSUE THREAD

**Issue by markschroeder77** [rungwiroon/BlazorGoogleMaps#84]
Hi,

Can anyone confirm if marker animation works?

I tried:

 var marker = await Marker.CreateAsync(map1.JsRuntime, new MarkerOptions()
{
    Position = mapCenter,
    Map = map1.InteropObject,
    Animation = Animation.Bounce
});

but the marker doesn't bounce.

Thanks

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.0.2
Fixed.

**Comment by markschroeder77** [comment]
Thanks for the change.

It now works when you add the maker with an animation already set, however calling setAnimation() on an existing marker doesn't work.

getAnimation works if you allow for a nullable return type.

`public async Task<Animation?> GetAnimation()
        {
            var animation = await _jsObjectRef.InvokeAsync<string>(
                "getAnimation");

            return Helper.ToNullableEnum<Animation>(animation);
        }`

`internal static T? ToNullableEnum<T>(string str)
            where T : struct
        {
            var enumType = typeof(T);

            if (str == "null")
                return null;

            foreach (var name in Enum.GetNames(enumType))
            {
                var enumMemberAttribute = ((EnumMemberAttribute[])enumType.GetField(name).GetCustomAttributes(typeof(EnumMemberAttribute), true)).Single();
                if (enumMemberAttribute.Value == str) return (T)Enum.Parse(enumType, name);
            }

            //throw exception or whatever handling you want
            return default;
        }`

**Comment by valentasm1** [comment]
I will try to look into more next week

**Comment by valentasm1** [comment]
Reopen if it dont work

**Comment by markschroeder77** [comment]
I can now start the animation, but is there a way to stop it?
The only way I could get it to work was to make the Animation enum nullable and pass it as an int in the js interop.
Here is what I did [https://github.com/markschroeder77/BlazorGoogleMaps](url)

**Comment by valentasm1** [comment]
Thank you very much
https://www.nuget.org/packages/BlazorGoogleMaps/2.2.2
