### ISSUE TITLE
Add a way to clear MarkerClustering

### ISSUE THREAD

**Issue by BigBuckey** [rungwiroon/BlazorGoogleMaps#86]
If I render a map using MarkerClustering and then subsequently remove the markers by setting Marker.SetMap(null), the markers remain on the map when using MarkerClustering. I have not found a way to prevent this.

https://stackoverflow.com/a/8229891/4761420 suggests that setting the MarkerClustering map to null will do the trick.

**Comment by valentasm1** [comment]
Marker clustering pretty new feature and didnt get any feedback from anyone. You are first person who did 👍 
If you couldnt wait then you could make PullRequest. Otherwise i will try to fix this week.

**Comment by BigBuckey** [comment]
Thanks for all your work on this library @valentasm1

**Comment by valentasm1** [comment]
Really sorry i have health issues. I hope it will pass around midweek.
Ps it is not corona :)

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.0.5
seting map to null just clear cluster but leaves markers. Added method clearMarkers based on
https://googlemaps.github.io/js-markerclustererplus/classes/markerclusterer.html#clearmarkers

**Comment by BigBuckey** [comment]
@valentasm1 Nice job, it works well. Thank you!!!
