### ISSUE TITLE
What is the best way to fit all markes on the map view?

### ISSUE THREAD

**Issue by SeppPenner** [rungwiroon/BlazorGoogleMaps#95]
I found your `Recenter` method, but it changes the last marker's position. Is there an easy alternative to center the map around all markers in it?

**Comment by valentasm1** [comment]
Check markers demo page FitBounds
https://github.com/rungwiroon/BlazorGoogleMaps/blob/master/ServerSideDemo/Pages/MapMarker.razor.cs


You could request bounds from markers or group. I dont have exact example but i am sure this page will help

**Comment by SeppPenner** [comment]
Ok, I will need to check this a bit more than :)

**Comment by SeppPenner** [comment]
Sorry :D I didn't find a solution yet, but nobody has complained about it either yet in my project :)

**Comment by valentasm1** [comment]
If it is not secret what kind a project are you working on?

**Comment by SeppPenner** [comment]
> If it is not secret what kind a project are you working on?

Well, it is property of the company I'm working for so I can't share any details. I cann tell you, however, that it's a LoRa application server similar to [Chirpstack](https://www.chirpstack.io/), but written in C# using the [Microsoft Orleans framework](https://dotnet.github.io/orleans/) to handle distributed systems.

And I can tell you, that your map component seems to be the only one that currently works as desired :D Even paid solutions like the one from Syncfusion we tested is not really satifying.
