### ISSUE TITLE
Bind and update markers depending on an ObservableCollection

### ISSUE THREAD

**Issue by aryehsilver** [rungwiroon/BlazorGoogleMaps#97]
Hi,

I have a component that displays listings. They are bound to an `ObservableCollection` how could I bind the markers associated with the listings so that they will be removed or displayed depending on filtering used?

Currently the only way I can find to add or remove markers is to manually call a method that will do this (e.g. `OnAfterMapInit`). Is there any way to bind the markers so that they will auto update depending on an `ObservableCollection`?

Thanks for the great package!

**Comment by valentasm1** [comment]
I think you should load listing in OnAfterMapInit method. 
In my understanding ObservableCollection only one difference from List is that they have event when element is added/removed. So attach to these event "CollectionChanged" and update/remove markers from map accordingly.

https://stackoverflow.com/questions/4588359/implementing-collectionchanged

**Comment by aryehsilver** [comment]
Ok thank you, this has helped me.
